Repository ToucanToco/weaverbird, pull requests merged in 2019-11, with the labels that each got.

#365 Fix top :: Make ColumnPicker not reactive to Multiselect selection
  src/components/stepforms/TopStepForm.vue
Labels: bug, need review

#362 v0.4.0
  CHANGELOG.md
  package.json
Labels: DO NOT MERGE, need review

#368 [doc] fix "filter step" section title
  docs/_docs/user-interface/filter.md
Labels: bug, documentation, need review

#367 [concatenate] fix bad state sync on edition
  src/components/stepforms/ColumnPicker.vue
  tests/unit/column-picker.spec.ts
  tests/unit/concatenate-step-form.spec.ts
Labels: bug, need review

#371 add link to documentation in the README
  README.md
Labels: documentation, need review

#372 remove unused Writable type
  src/components/stepforms/StepForm.vue
  src/lib/steps.ts
Labels: need review

#373 v0.5.0
  CHANGELOG.md
  package.json
Labels: need review

#376 [doc] fix "mongdb" typo in README
  README.md
Labels: documentation, need review

#380 Fix :: step forms validator built too soon with obsolete column names
  src/components/stepforms/StepForm.vue
Labels: bug, need review
