Repository ToucanToco/weaverbird, pull requests merged in 2019-09, with the labels that each got.

#286 FIX :: allow scroll to pipeline steps
  src/styles/Steps.scss
Labels: bug, ui

#289 Do not project the _id column generated automatically by mongo
  src/lib/translators/mongo.ts
  tests/unit/mongo.spec.ts
Labels: enhancement, need review

#290 Do not create conflicting interactions between form fields
  src/components/stepforms/PercentageStepForm.vue
Labels: bug, to merge

#299 Feature :: dataviewer loader spinner
  src/components/DataViewer.vue
  src/store/backend-plugin.ts
  src/store/mutations.ts
  src/store/state.ts
  tests/unit/data-viewer.spec.ts
  tests/unit/store.spec.ts
Labels: enhancement, need review, ui

#302 Tech :: Preparation for NPM Registry
  LICENSE
  package.json
Labels: need review, tech

#305 Enhancement :: Always Display Caret in cell header
  src/components/DataViewer.vue
  src/styles/DataViewer.scss
Labels: design, enhancement, to merge

#307 Fix :: change offset computing method to get the good align right position
  src/components/domutil.ts
Labels: bug, need review, ui

#308 fix tsdoc generation
  package.json
  tsconfig.json
  yarn.lock
Labels: bug, build

#311 Fix :: Playground pipeline initialization
  playground/app.js
Labels: bug, need review

#309 Enhancement :: Always leave tips message under steps on Pipeline
  src/components/Pipeline.vue
  src/styles/Pipeline.scss
  tests/unit/pipeline.spec.ts
Labels: enhancement, need review

#310 [FilterStepForm] Fix :: Set column value with current selected column
  src/components/stepforms/FilterStepForm.vue
  src/components/stepforms/widgets/FilterSimpleCondition.vue
  tests/unit/filter-step-form.spec.ts
Labels: bug, to merge

#312 Improve :: global style scope
  playground/dist/index.html
  src/components/Popover.vue
  src/styles/_variables.scss
Labels: enhancement, need review

#313 version 0.2.0
  CHANGELOG.md
  package.json
Labels: need review

#319 FIX :: Firefox didn't display dataviewer td border
  src/styles/DataViewer.scss
Labels: bug, ui

#317 Simplify replace step
  doc/steps.md
  src/components/stepforms/ReplaceStepForm.vue
  src/components/stepforms/schemas/index.ts
  src/components/stepforms/schemas/replace.ts
  src/lib/steps.ts
  src/lib/translators/mongo.ts
  tests/unit/labeller.spec.ts
  tests/unit/mongo.spec.ts
  tests/unit/replace-step-form.spec.ts
Labels: enhancement
