Repository ToucanToco/weaverbird, pull requests merged in 2019-03, with the labels that each got.

#11 [doc] use TypeDoc to generate project documentation
  README.md
  package.json
  yarn.lock
Labels: documentation, to merge

#12 [doc] document `newcolumn` step
  doc/steps.md
Labels: documentation, need review

#13 Dev :: Storybook environment
  .storybook/addons.js
  .storybook/config.js
  README.md
  package.json
  stories/index.js
  yarn.lock
Labels: tech

#15 Build :: rollup bundle
  .circleci/config.yml
  README.md
  package.json
  rollup.config.js
  src/components/Step.vue
  tsconfig.json
  yarn.lock
Labels: tech

#14 Tech :: CSS to SASS
  package.json
  src/components/DomainSelector.vue
  src/components/Pipeline.vue
  src/components/Step.vue
  src/styles/DomainSelector.scss
  src/styles/Pipeline.scss
  src/styles/Steps.scss
  src/styles/_variables.scss
  src/styles/main.scss
  yarn.lock
Labels: enhancement, need review, tech

#19 tech :: Convert vue components to TypeScript
  .storybook/bundle.ts
  .storybook/rollup.config.js
  README.md
  package.json
  src/components/DomainSelector.vue
  src/components/Pipeline.vue
  src/components/Step.vue
  src/main.ts
  stories/index.js
  yarn.lock
Labels: tech

#17 tech :: update example App component to match valid step types
  src/App.vue
Labels: tech
