Repository ToucanToco/weaverbird, pull requests merged in 2019-12, with the labels that each got.

#384 [git] remove editor/OS-specific paths
  .gitignore
Labels: convention, need review

#385 [tests] remove browser tests for popover
  tests/unit/popover.spec.ts
Labels: need review

#388 Backport v0.5.1 changes into master
  CHANGELOG.md
  package.json
  src/lib/dataset/mongo.ts
  src/lib/translators/mongo.ts
Labels: backport

#381 Allow formula result to overwrite existing column
  src/components/stepforms/schemas/formula.ts
  tests/unit/formula-step-form.spec.ts
Labels: mongo, need review, querytranslate

#392 [playground] circumvent mongodb-download out-of-date URLs
  README.md
  playground/mongo-server.js
Labels: enhancement, playground, to merge

#393 v0.6.0
  CHANGELOG.md
  package.json
Labels: need review, release

#394 [doc] give direct access to documentation from the UI
  CHANGELOG.md
  docs/_data/docs.yml
  docs/_docs/user-interface/delete.md
  docs/_docs/user-interface/fillna.md
  docs/_docs/user-interface/keep.md
  docs/_docs/user-interface/text.md
  docs/_docs/user-interface/top.md
  src/components/QueryBuilder.vue
  src/components/stepforms/AddTextColumnStepForm.vue
  src/components/stepforms/AggregateStepForm.vue
  src/components/stepforms/AppendStepForm.vue
  src/components/stepforms/ArgmaxStepForm.vue
  src/components/stepforms/ArgminStepForm.vue
  src/components/stepforms/ConcatenateStepForm.vue
  src/components/stepforms/ConvertStepForm.vue
  src/components/stepforms/DeleteColumnStepForm.vue
  src/components/stepforms/DomainStepForm.vue
  src/components/stepforms/DuplicateColumnStepForm.vue
  src/components/stepforms/FillnaStepForm.vue
  src/components/stepforms/FilterStepForm.vue
  src/components/stepforms/FormulaStepForm.vue
  src/components/stepforms/FromDateStepForm.vue
  src/components/stepforms/JoinStepForm.vue
  src/components/stepforms/PercentageStepForm.vue
  src/components/stepforms/PivotStepForm.vue
  src/components/stepforms/RenameStepForm.vue
  src/components/stepforms/ReplaceStepForm.vue
  src/components/stepforms/SelectColumnStepForm.vue
  src/components/stepforms/SortStepForm.vue
  src/components/stepforms/SplitStepForm.vue
  src/components/stepforms/StepFormTitle.vue
  src/components/stepforms/SubstringStepForm.vue
  src/components/stepforms/ToDateStepForm.vue
  src/components/stepforms/ToLowerStepForm.vue
  src/components/stepforms/ToUpperStepForm.vue
  src/components/stepforms/TopStepForm.vue
  src/components/stepforms/UnpivotStepForm.vue
Labels: documentation, to merge, ui

#395 Add 'isnull' and 'not null' operators to filter step
  CHANGELOG.md
  docs/_docs/tech/steps.md
  docs/_docs/user-interface/filter.md
  src/components/stepforms/schemas/filter.ts
  src/components/stepforms/widgets/FilterSimpleCondition.vue
  src/lib/labeller.ts
  src/lib/steps.ts
  src/lib/templating.ts
  src/lib/translators/mongo.ts
  tests/unit/filter-simple-condition-widget.spec.ts
  tests/unit/labeller.spec.ts
  tests/unit/mongo.spec.ts
  tests/unit/templating.spec.ts
Labels: enhancement, to merge

#396 Enhancement :: Playground Scrolling Hell
  playground/app.js
  playground/dist/index.html
  src/styles/ResizablePanels.scss
Labels: enhancement, need review

#398 v0.7.0
  CHANGELOG.md
  package.json
Labels: release, to merge

#400 Fix :: serialize-javascript dependencies issue
  yarn.lock
Labels: need review, tech
