Repository ToucanToco/weaverbird, pull requests merged in 2019-07, with the labels that each got.

#224 [tests] uses localVue.nextTick() instead of Vue.nextTick()
  tests/unit/action-toolbar.spec.ts
  tests/unit/argmax-step-form.spec.ts
  tests/unit/argmin-step-form.spec.ts
  tests/unit/data-viewer.spec.ts
  tests/unit/percentage-step-form.spec.ts
  tests/unit/rename-step-form.spec.ts
  tests/unit/step.spec.ts
  tests/unit/vqb.spec.ts
Labels: need review, tech

#215 Fix :: Remove stepSelectedColumn getter and setter in AggregateStepForm
  src/components/stepforms/AggregateStepForm.vue
Labels: bug, need review

#226 [eslint] no space between function parenthesis!
  package.json
Labels: need review, tech

#227 Feature :: Pivot Step Form
  src/components/stepforms/PivotStepForm.vue
  src/components/stepforms/index.ts
  src/components/stepforms/schemas/index.ts
  src/components/stepforms/schemas/pivot.ts
  tests/unit/karma-test-suite.ts
  tests/unit/pivot-step-form.spec.ts
Labels: enhancement, need review, ui

#229 Fix :: Ignore current selectedColumns when editing a step
  src/components/stepforms/StepForm.vue
Labels: bug, need review, ui

#230 Feature :: Improve WidgetList
  src/components/stepforms/AggregateStepForm.vue
  src/components/stepforms/WidgetList.vue
  tests/unit/widget-list.spec.ts
Labels: enhancement, need review

#231 [tests] exclude test files from coverage
  tests/rollup.config.test.js
Labels: tech, to merge

#233 Introduce a Top step
  src/components/stepforms/TopStepForm.vue
  src/components/stepforms/index.ts
  src/components/stepforms/schemas/index.ts
  src/components/stepforms/schemas/top.ts
  tests/unit/karma-test-suite.ts
  tests/unit/top-step-form.spec.ts
Labels: need review, ui

#236 Feature :: UI Keep Columns
  src/components/constants.ts
  src/components/stepforms/SelectColumnStepForm.vue
  src/components/stepforms/index.ts
  src/components/stepforms/schemas/index.ts
  src/components/stepforms/schemas/select.ts
  tests/unit/select-column-step-form.spec.ts
Labels: need review, ui

#239 [column-picker] fix default export name
  src/components/stepforms/ColumnPicker.vue
Labels: convention, need review

#247 Fix :: rename step submit function
  src/components/stepforms/RenameStepForm.vue
  tests/unit/rename-step-form.spec.ts
Labels: bug

#228 Feature :: Sort step form
  doc/steps.md
  src/components/ActionMenu.vue
  src/components/stepforms/SortStepForm.vue
  src/components/stepforms/WidgetAggregation.vue
  src/components/stepforms/WidgetList.vue
  src/components/stepforms/WidgetSortColumn.vue
  src/components/stepforms/index.ts
  src/components/stepforms/schemas/index.ts
  src/components/stepforms/schemas/sort.ts
  src/lib/steps.ts
  src/lib/translators/mongo.ts
  tests/unit/karma-test-suite.ts
  tests/unit/mongo.spec.ts
  tests/unit/sort-step-form.spec.ts
  tests/unit/widget-sort-column.spec.ts
Labels: need review, ui

#251 [playground] rename mongodb local module
  playground/mongo-server.js
  playground/server.js
Labels: need review, playground

#249 Feature: UI Formula
  src/components/ActionToolbar.vue
  src/components/stepforms/FormulaStepForm.vue
  src/components/stepforms/index.ts
  src/components/stepforms/schemas/formula.ts
  src/components/stepforms/schemas/index.ts
  tests/unit/formula-step-form.spec.ts
  tests/unit/karma-test-suite.ts
Labels: need review, ui

#255 Introduce a Known Limitations section in the documentation
  doc/known_limitations.md
Labels: documentation, need review

#254 Infer types :: Infer float type when a column has a mix of integers and floats
  src/lib/dataset/mongo.ts
  tests/unit/dataset.spec.ts
Labels: data, enhancement, need review

#257 Fix WidgetAggregation :: Watch 'aggregation' data rather than 'value' prop
  src/components/stepforms/WidgetAggregation.vue
  tests/unit/widget-aggregation.spec.ts
Labels: enhancement, need review

#256 Fillna step :: Cast user input depending on column data type
  src/components/stepforms/FillnaStepForm.vue
  src/components/stepforms/WidgetInputText.vue
  src/components/stepforms/schemas/fillna.ts
  tests/unit/fillna-step-form.spec.ts
Labels: enhancement, need review

#259 Fix :: stub transition component with correct parameter
  tests/unit/vqb.spec.ts
Labels: bug, need review

#250 Feature :: search bar new branch and finalization
  src/components/ActionToolbar.vue
  src/components/SearchBar.vue
  src/components/constants.ts
  src/components/stepforms/WidgetAutocomplete.vue
  tests/unit/action-toolbar.spec.ts
  tests/unit/karma-test-suite.ts
  tests/unit/search-bar.spec.ts
Labels: need review, ui

#264 [popover] suffix style units with px expclitly
  src/components/Popover.vue
  tests/unit/popover.spec.ts
Labels: bug, need review

#268 [tests] fix hardcoded filter-step-form jsonschema test
  tests/unit/filter-step-form.spec.ts
Labels: bug, need review

#265 [helpers] better helper function name for isBooleanString
  src/lib/helpers.ts
Labels: need review

#269 fix widget modules naming
  src/components/stepforms/AggregateStepForm.vue
  src/components/stepforms/ArgmaxStepForm.vue
  src/components/stepforms/ArgminStepForm.vue
  src/components/stepforms/ColumnPicker.vue
  src/components/stepforms/DeleteColumnStepForm.vue
  src/components/stepforms/DomainStepForm.vue
  src/components/stepforms/DuplicateColumnStepForm.vue
  src/components/stepforms/FillnaStepForm.vue
  src/components/stepforms/FilterStepForm.vue
  src/components/stepforms/FormulaStepForm.vue
  src/components/stepforms/PercentageStepForm.vue
  src/components/stepforms/PivotStepForm.vue
  src/components/stepforms/RenameStepForm.vue
  src/components/stepforms/ReplaceStepForm.vue
  src/components/stepforms/SelectColumnStepForm.vue
  src/components/stepforms/SortStepForm.vue
  src/components/stepforms/TopStepForm.vue
  src/components/stepforms/UnpivotStepForm.vue
  src/components/stepforms/widgets/Aggregation.vue
  src/components/stepforms/widgets/Autocomplete.vue
  src/components/stepforms/widgets/Checkbox.vue
  src/components/stepforms/widgets/FilterSimpleCondition.vue
  src/components/stepforms/widgets/InputText.vue
  src/components/stepforms/widgets/List.vue
  src/components/stepforms/widgets/MultiInputText.vue
  src/components/stepforms/widgets/Multiselect.vue
  src/components/stepforms/widgets/Replace.vue
  src/components/stepforms/widgets/SortColumn.vue
  tests/unit/aggregate-step-form.spec.ts
  tests/unit/aggregation-widget.spec.ts
  tests/unit/argmax-step-form.spec.ts
  tests/unit/argmin-step-form.spec.ts
  tests/unit/autocomplete-widget.spec.ts
  tests/unit/checkbox-widget.spec.ts
  tests/unit/column-picker.spec.ts
  tests/unit/delete-column-step-form.spec.ts
  tests/unit/domain-step-form.spec.ts
  tests/unit/duplicate-column-step-form.spec.ts
  tests/unit/fillna-step-form.spec.ts
  tests/unit/filter-simple-condition-widget.spec.ts
  tests/unit/filter-step-form.spec.ts
  tests/unit/formula-step-form.spec.ts
  tests/unit/input-text-widget.spec.ts
  tests/unit/list-widget.spec.ts
  tests/unit/multi-input-text-widget.spec.ts
  tests/unit/multiselect-widget.spec.ts
  tests/unit/percentage-step-form.spec.ts
  tests/unit/pivot-step-form.spec.ts
  tests/unit/rename-step-form.spec.ts
  tests/unit/replace-step-form.spec.ts
  tests/unit/replace-widget.spec.ts
  tests/unit/select-column-step-form.spec.ts
  tests/unit/sort-column-widget.spec.ts
  tests/unit/sort-step-form.spec.ts
  tests/unit/unpivot-step-form.spec.ts
Labels: need review, tech

#263 [store] introduce a `pagesize` state property
  playground/app.js
  src/store/backend-plugin.ts
  src/store/state.ts
  tests/unit/plugins.spec.ts
Labels: enhancement, need review

#271 Fix Pivot Step :: Add a custom stepSelectedColumn getter and setter
  src/components/stepforms/PivotStepForm.vue
  tests/unit/pivot-step-form.spec.ts
Labels: bug, to merge

#270 Fix Percentage Step :: Add a custom stepSelectedColumn getter and setter
  src/components/stepforms/PercentageStepForm.vue
  tests/unit/percentage-step-form.spec.ts
Labels: bug, to merge

#272 Fix Filter Step :: Cast the value key of the filter conditions depending on column type
  src/components/stepforms/FilterStepForm.vue
  src/components/stepforms/schemas/filter.ts
  tests/unit/filter-step-form.spec.ts
Labels: bug, need review
