Repository ToucanToco/weaverbird, pull requests merged in 2019-10, with the labels that each got.

#322 Fix :: Firefox hack for dataviewer border display
  src/styles/DataViewer.scss
Labels: bug, ui

#321 Simplify unpivot step
  CHANGELOG.md
  src/components/stepforms/UnpivotStepForm.vue
  src/lib/helpers.ts
  tests/unit/helpers.spec.ts
  tests/unit/unpivot-step-form.spec.ts
Labels: enhancement, need review

#323 Simplify percentage step
  CHANGELOG.md
  doc/steps.md
  src/components/stepforms/PercentageStepForm.vue
  src/components/stepforms/schemas/percentage.ts
  src/lib/labeller.ts
  src/lib/steps.ts
  src/lib/translators/mongo.ts
  tests/unit/labeller.spec.ts
  tests/unit/mongo.spec.ts
  tests/unit/percentage-step-form.spec.ts
  tests/unit/templating.spec.ts
Labels: enhancement, need review

#325 Fix :: Top step initialization
  CHANGELOG.md
  src/components/stepforms/TopStepForm.vue
Labels: bug, need review

#327 Fix labelling and bad interaction
  CHANGELOG.md
  src/components/stepforms/ArgmaxStepForm.vue
  src/components/stepforms/ArgminStepForm.vue
Labels: bug, need review

#328 [rollup] only use terser() in production mode
  rollup.config.js
Labels: build, need review

#330 [filter] fix shared references between conditions
  CHANGELOG.md
  src/components/stepforms/widgets/List.vue
  tests/unit/list-widget.spec.ts
Labels: bug, need review

#331 Fix :: add a minimum of margin on data-viewer
  src/styles/DataViewer.scss
Labels: bug, need review

#344 [templating] autocast output values
  CHANGELOG.md
  src/lib/templating.ts
  src/store/backend-plugin.ts
  tests/unit/templating.spec.ts
Labels: data, need review

#347 Release :: v0.3.0
  CHANGELOG.md
  package.json
Labels: tech, to merge

#349 Fix changelog
  CHANGELOG.md
Labels: bug, need review

#354 [eslint] enforce autoclosing tags
  package.json
  src/components/ActionToolbar.vue
  src/components/ActionToolbarButton.vue
  src/components/DataViewer.vue
  src/components/DeleteConfirmationModal.vue
  src/components/Pipeline.vue
  src/components/Popover.vue
  src/components/QueryBuilder.vue
  src/components/ResizablePanels.vue
  src/components/SearchBar.vue
  src/components/Step.vue
  src/components/stepforms/AggregateStepForm.vue
  src/components/stepforms/ArgmaxStepForm.vue
  src/components/stepforms/ArgminStepForm.vue
  src/components/stepforms/ColumnPicker.vue
  src/components/stepforms/DeleteColumnStepForm.vue
  src/components/stepforms/DomainStepForm.vue
  src/components/stepforms/DuplicateColumnStepForm.vue
  src/components/stepforms/FillnaStepForm.vue
  src/components/stepforms/FilterStepForm.vue
  src/components/stepforms/FormulaStepForm.vue
  src/components/stepforms/PercentageStepForm.vue
  src/components/stepforms/PivotStepForm.vue
  src/components/stepforms/RenameStepForm.vue
  src/components/stepforms/ReplaceStepForm.vue
  src/components/stepforms/SelectColumnStepForm.vue
  src/components/stepforms/SortStepForm.vue
  src/components/stepforms/ToLowerStepForm.vue
  src/components/stepforms/ToUpperStepForm.vue
  src/components/stepforms/TopStepForm.vue
  src/components/stepforms/UnpivotStepForm.vue
  src/components/stepforms/widgets/Aggregation.vue
  src/components/stepforms/widgets/Autocomplete.vue
  src/components/stepforms/widgets/FilterSimpleCondition.vue
  src/components/stepforms/widgets/InputText.vue
  src/components/stepforms/widgets/List.vue
  src/components/stepforms/widgets/Multiselect.vue
  src/components/stepforms/widgets/Replace.vue
  src/components/stepforms/widgets/SortColumn.vue
Labels: convention, need review

#342 Make lowercase and uppercase steps more straightforward
  CHANGELOG.md
  src/components/ActionToolbarButton.vue
  tests/unit/action-toolbar-button.spec.ts
Labels: enhancement, need review

#355 [tests] narrow return signature of setupMockStore
  tests/unit/action-menu.spec.ts
  tests/unit/action-toolbar-button.spec.ts
  tests/unit/aggregate-step-form.spec.ts
  tests/unit/aggregation-widget.spec.ts
  tests/unit/argmax-step-form.spec.ts
  tests/unit/argmin-step-form.spec.ts
  tests/unit/column-picker.spec.ts
  tests/unit/concatenate-step-form.spec.ts
  tests/unit/delete-column-step-form.spec.ts
  tests/unit/domain-step-form.spec.ts
  tests/unit/duplicate-column-step-form.spec.ts
  tests/unit/fillna-step-form.spec.ts
  tests/unit/filter-simple-condition-widget.spec.ts
  tests/unit/filter-step-form.spec.ts
  tests/unit/formula-step-form.spec.ts
  tests/unit/percentage-step-form.spec.ts
  tests/unit/pivot-step-form.spec.ts
  tests/unit/plugins.spec.ts
  tests/unit/rename-step-form.spec.ts
  tests/unit/replace-step-form.spec.ts
  tests/unit/replace-widget.spec.ts
  tests/unit/select-column-step-form.spec.ts
  tests/unit/sort-column-widget.spec.ts
  tests/unit/sort-step-form.spec.ts
  tests/unit/split-step-form.spec.ts
  tests/unit/step.spec.ts
  tests/unit/tolower-step-form.spec.ts
  tests/unit/top-step-form.spec.ts
  tests/unit/toupper-step-form.spec.ts
  tests/unit/unpivot-step-form.spec.ts
  tests/unit/utils.ts
Labels: need review, tech

#358 Weaverbird has spoken, let it leave the nest
  CHANGELOG.md
  README.md
  docs/_config.yml
  docs/about.html
  package.json
  playground/dist/index.html
  playground/dist/playground.css
  playground/dist/vue-query-builder.browser.js
  playground/dist/weaverbird.browser.js
  public/index.html
  rollup.config.js
  src/components/Vqb.vue
  stories/index.js
Labels: need review, tech

#360 [doc] remove old doc directory.
  doc/img/aggregate_example_conf.jpg
  doc/img/aggregate_example_result.jpg
  doc/img/aggregate_step_form.jpg
  doc/img/argmax_example_conf.jpg
  doc/img/argmax_example_result.jpg
  doc/img/argmax_step_form.jpg
  doc/img/argmin_example_conf.jpg
  doc/img/argmin_example_result.jpg
  doc/img/argmin_step_form.jpg
  doc/img/column_header_menu.jpg
  doc/img/delete_step_form.jpg
  doc/img/duplicate_example_conf.jpg
  doc/img/duplicate_example_result.jpg
  doc/img/duplicate_step_form.jpg
  doc/img/fillna_example_conf.jpg
  doc/img/fillna_example_result.jpg
  doc/img/fillna_step_form.jpg
  doc/img/filter_example_conf.jpg
  doc/img/filter_example_result.jpg
  doc/img/filter_step_form.jpg
  doc/img/formula_example_conf_1.jpg
  doc/img/formula_example_conf_2.jpg
  doc/img/formula_example_result_1.jpg
  doc/img/formula_example_result_2.jpg
  doc/img/formula_step_form.jpg
  doc/img/general_interface.jpg
  doc/img/lowercase_example_conf.jpg
  doc/img/lowercase_example_result.jpg
  doc/img/lowercase_step_form.jpg
  doc/img/middle_step_selected.jpg
  doc/img/percentage_example_conf.jpg
  doc/img/percentage_example_result.jpg
  doc/img/percentage_step_form.jpg
  doc/img/pivot_example_conf.jpg
  doc/img/pivot_example_result.jpg
  doc/img/pivot_step_form.jpg
  doc/img/rename_example_conf.jpg
  doc/img/rename_example_result.jpg
  doc/img/rename_step_form.jpg
  doc/img/replace_example_conf.jpg
  doc/img/replace_example_result.jpg
  doc/img/replace_step_form.jpg
  doc/img/search_bar_menu.jpg
  doc/img/select_step_form.jpg
  doc/img/sort_example_conf.jpg
  doc/img/sort_example_result.jpg
  doc/img/sort_step_form.jpg
  doc/img/step_edition_mode.jpg
  doc/img/top_example_conf.jpg
  doc/img/top_example_result.jpg
  doc/img/top_step_form.jpg
  doc/img/unpivot_example_conf.jpg
  doc/img/unpivot_example_result.jpg
  doc/img/unpivot_step_form.jpg
  doc/img/uppercase_example_conf.jpg
  doc/img/uppercase_example_result.jpg
  doc/img/uppercase_step_form.jpg
  doc/img/widget_menu.jpg
  doc/steps.md
  doc/user_interface.md
Labels: documentation, need review

#359 Move filter action higher in the columns header actions menu
  src/components/ActionMenu.vue
  tests/unit/action-menu.spec.ts
Labels: enhancement, ui

#361 [doc] fix title level for "Example"
  docs/_docs/tech/steps.md
Labels: documentation, need review

#363 Doc :: Add UI doc for concatenate, split and substring steps
  docs/_docs/user-interface/aggregate.md
  docs/_docs/user-interface/argmax.md
  docs/_docs/user-interface/argmin.md
  docs/_docs/user-interface/concatenate.md
  docs/_docs/user-interface/delete.md
  docs/_docs/user-interface/duplicate.md
  docs/_docs/user-interface/fillnull.md
  docs/_docs/user-interface/filter.md
  docs/_docs/user-interface/formula.md
  docs/_docs/user-interface/general-principles.md
  docs/_docs/user-interface/keep.md
  docs/_docs/user-interface/lowercase.md
  docs/_docs/user-interface/percentage.md
  docs/_docs/user-interface/pivot.md
  docs/_docs/user-interface/rename.md
  docs/_docs/user-interface/replace.md
  docs/_docs/user-interface/sort.md
  docs/_docs/user-interface/split.md
  docs/_docs/user-interface/substring.md
  docs/_docs/user-interface/topnrows.md
  docs/_docs/user-interface/unpivot.md
  docs/_docs/user-interface/uppercase.md
  docs/img/docs/user-interface/concatenate_example_conf.jpg
  docs/img/docs/user-interface/concatenate_example_result.jpg
  docs/img/docs/user-interface/concatenate_step_form.jpg
  docs/img/docs/user-interface/split_example_conf.jpg
  docs/img/docs/user-interface/split_example_result.jpg
  docs/img/docs/user-interface/split_step_form.jpg
  docs/img/docs/user-interface/substring_example_conf_1.jpg
  docs/img/docs/user-interface/substring_example_conf_2.jpg
  docs/img/docs/user-interface/substring_example_result.jpg
  docs/img/docs/user-interface/substring_step_form.jpg
Labels: documentation, need review
