Repository ToucanToco/weaverbird, pull requests merged in 2019-06, with the labels that each got.

#148 [playground] add `--automongo` flag
  README.md
  package.json
  playground/mongodb.js
  playground/playground.config.json
  playground/server.js
  yarn.lock
Labels: need review, playground, tech

#159 Delete dbservice.ts in playground
  playground/dbservice.ts
Labels: tech, to merge

#158 [playground] :: UI Enhancement
  playground/app.js
  playground/dist/index.html
  playground/dist/pattern-blueprints.png
  src/components/Vqb.vue
  src/styles/ResizablePanels.scss
Labels: enhancement, need review, ui

#160 [step] :: enhance active step UI
  src/components/Pipeline.vue
  src/components/Step.vue
  src/styles/DataViewer.scss
  src/styles/Steps.scss
  src/styles/_variables.scss
  tests/unit/pipeline.spec.ts
Labels: need review, ui

#161 Fix :: add back editStep event handler in Vqb
  src/components/Vqb.vue
Labels: need review

#164 Fix :: pipeline and dataviewer update
  src/components/Vqb.vue
  src/store/backend-plugin.ts
  tests/unit/plugins.spec.ts
Labels: need review

#167 [circleci] run jest in a single thread
  .circleci/config.yml
Labels: tech, to merge

#166 [Rename step] :: error if newname corresponds to an existing column name
  src/components/FormRenameStep.vue
  src/mixins/FormMixin.vue
  tests/unit/form-rename-step.spec.ts
Labels: need review

#168 [circleci] jest is not used anymore
  .circleci/config.yml
Labels: tech, to merge

#169 [eslint] use tslint parser
  package.json
  src/components/ActionMenu.vue
  src/components/formlib.ts
  tests/unit/widget-input-text.spec.ts
  yarn.lock
Labels: need review, tech

#170 [storybook] fix rollup config
  rollup.config.js
Labels: tech, to merge

#172 [form] only export a single symbol from Vue files
  src/components/RenameStepForm.vue
Labels: need review, tech

#175 [karma] fix injection slots in context.html
  tests/context.html
Labels: tech, to merge

#174 [forms] move step forms in a specific directory
  src/components/Vqb.vue
  src/components/formlib.ts
  src/components/stepforms/DeleteColumnStepForm.vue
  src/components/stepforms/FillnaStepForm.vue
  src/components/stepforms/RenameStepForm.vue
  src/components/stepforms/WidgetAutocomplete.vue
  src/components/stepforms/WidgetInputText.vue
  src/components/stepforms/index.ts
  tests/unit/delete-column-step-form.spec.ts
  tests/unit/fillna-step-form.spec.ts
  tests/unit/rename-step-form.spec.ts
  tests/unit/vqb.spec.ts
  tests/unit/widget-autocomplete.spec.ts
  tests/unit/widget-input-text.spec.ts
Labels: need review, tech

#177 Fix :: Codecov report generation
  package.json
Labels: bug, need review

#178 Feature :: Nice Slide Transition between Pipeline and StepForms component
  src/components/Vqb.vue
  src/styles/ResizablePanels.scss
  tests/unit/vqb.spec.ts
Labels: enhancement, need review, ui

#179 Feature :: Avoid bad toggling of step edition mode
  src/components/ActionMenu.vue
  src/components/Vqb.vue
  tests/unit/action-menu.spec.ts
  tests/unit/vqb.spec.ts
Labels: need review, ui

#183 [translator] fix handling of empty mongo pipelines
  src/lib/translators/mongo.ts
  tests/unit/mongo.spec.ts
Labels: bug, need review, querytranslate, tech

#182 [steps] make step type definitons writable
  src/lib/matcher.ts
  src/lib/steps.ts
  src/lib/translators/base.ts
  src/lib/translators/mongo.ts
Labels: need review, tech

#184 [stepforms] implement FilterStep form
  src/assets/schemas/filter-step__schema.json
  src/components/ActionMenu.vue
  src/components/stepforms/FilterStepForm.vue
  src/components/stepforms/index.ts
  tests/unit/filter-step-form.spec.ts
  tests/unit/karma-test-suite.ts
Labels: need review, ui

#197 fix :: remove forgotten .only in domain step form tests
  tests/unit/domain-step-form.spec.ts
Labels: bug, need review

#196 fix :: aggregate step title
  src/components/stepforms/AggregateStepForm.vue
Labels: bug, need review

#198 UI :: Form Buttons Improvements
  src/components/stepforms/StepFormButtonbar.vue
  src/styles/_variables.scss
Labels: need review, ui

#173 Feature :: Action toolbar popover
  src/components/ActionToolbar.vue
  src/components/ActionToolbarButton.vue
  src/components/constants.ts
  tests/unit/action-toolbar.spec.ts
Labels: need review, ui

#199 remove :: component DomainSelector is no longer used
  .storybook/bundle.ts
  src/components/DomainSelector.vue
  src/components/Pipeline.vue
  src/styles/DomainSelector.scss
  src/styles/main.scss
Labels: need review, tech

#200 Feature :: Playground :: Drop CSV File
  package.json
  playground/app.js
  playground/dist/index.html
  playground/server.js
  src/components/DataViewer.vue
  yarn.lock
Labels: enhancement, need review

#202 improve :: active header caret icon
  src/styles/DataViewer.scss
Labels: need review, ui

#201 Feature :: Empty Pipeline
  src/components/Pipeline.vue
  src/styles/Pipeline.scss
  tests/unit/pipeline.spec.ts
Labels: enhancement, ui

#203 Polishing :: input form contrast improvement
  src/components/stepforms/WidgetAutocomplete.vue
  src/components/stepforms/WidgetMultiselect.vue
  src/styles/_variables.scss
Labels: need review, ui

#206 Fix :: empty cells in csv
  playground/server.js
Labels: bug, need review

#208 [karma] use mocha-reporter with showDiff
  karma.conf.js
  package.json
  yarn.lock
Labels: need review, tech

#209 FillnaStepForm :: clean unnecessary import
  src/components/stepforms/FillnaStepForm.vue
Labels: :recycle: cleaning :recycle:, need review

#211 Refacto :: ActionToolButton use SASS $active-color variable
  src/components/ActionToolbarButton.vue
Labels: enhancement, need review

#210 AggregateStepForm :: Use the new way to update property when selectedColumns change
  src/components/stepforms/AggregateStepForm.vue
Labels: enhancement, need review

#217 Introduce Percentage Step
  src/assets/schemas/percentage-step__schema.json
  src/components/stepforms/PercentageStepForm.vue
  src/components/stepforms/index.ts
  tests/unit/karma-test-suite.ts
  tests/unit/percentage-step-form.spec.ts
Labels: need review, ui
