Repository ToucanToco/weaverbird, pull requests merged in 2019-08, with the labels that each got.

#274 [getters] introduce the columnTypes getter
  src/components/stepforms/FillnaStepForm.vue
  src/components/stepforms/FilterStepForm.vue
  src/components/stepforms/ReplaceStepForm.vue
  src/lib/dataset/index.ts
  src/store/getters.ts
  tests/unit/store.spec.ts
Labels: need review, tech

#275 [playground] fix typo on `mongotranslator`
  playground/app.js
Labels: bug, need review

#279 Make formula step accessible from compute widget
  src/components/ActionToolbar.vue
  src/components/SearchBar.vue
  src/components/constants.ts
  tests/unit/search-bar.spec.ts
Labels: enhancement, need review

#278 Feature :: pagination counter (clean branch)
  playground/app.js
  src/components/Pagination.vue
  src/lib/dataset/pagination.ts
  tests/unit/pagination-component.spec.ts
  tests/unit/pagination.spec.ts
Labels: need review, ui

#280 Fix : Filter step US
  src/components/stepforms/widgets/Autocomplete.vue
  src/components/stepforms/widgets/FilterSimpleCondition.vue
  src/components/stepforms/widgets/InputText.vue
  tests/unit/autocomplete-widget.spec.ts
  tests/unit/filter-simple-condition-widget.spec.ts
  tests/unit/input-text-widget.spec.ts
Labels: bug, enhancement, need review

#282 Tech :: update readme
  README.md
Labels: tech, to merge
