Repository ToucanToco/weaverbird, pull requests merged in 2019-05, with the labels that each got.

#117 Feature:: 'pivot' step translation to mongo
  doc/steps.md
  src/lib/steps.ts
  src/lib/translators/base.ts
  src/lib/translators/mongo.ts
  tests/unit/mongo.spec.ts
Labels: mongo, need review, querytranslate

#118 Feature :: unpivot step translation to mongo
  doc/steps.md
  src/lib/steps.ts
  src/lib/translators/base.ts
  src/lib/translators/mongo.ts
  tests/unit/mongo.spec.ts
Labels: mongo, need review, querytranslate

#121 feature :: lodash mongo utils
  src/lib/translators/mongo.ts
Labels: enhancement, need review

#123 [jest] make sure `.d.ts` are matched by jest
  jest.config.js
Labels: need review, tech

#120 feature :: define a basic dataset type
  src/components/DataViewer.vue
  src/lib/dataset/index.ts
  src/lib/dataset/mongo.ts
  stories/data-viewer.js
  tests/unit/data-viewer.spec.ts
  tests/unit/dataset.spec.ts
Labels: data, need review, tech

#124 Doc/examples steps
  doc/steps.md
Labels: documentation, querytranslate

#119 Improve :: replace step translation to mongo
  doc/steps.md
  src/lib/steps.ts
  src/lib/translators/mongo.ts
  tests/unit/mongo.spec.ts
Labels: mongo, need review, querytranslate

#127 [rollup] make sure `mathjs.parse` is exported
  rollup.config.js
Labels: build, need review, tech

#126 [steps] fix pivot step type definition
  src/lib/steps.ts
Labels: bug, need review

#129 [eslint] set prefer-const and no-console rules
  package.json
  src/lib/translators/mongo.ts
Labels: need review, tech

#132 Clean :: remove unused files
  src/App.vue
  src/example.ts
  src/fake_dataset.json
Labels: need review

#133 [pkg] remove deprecated `serve` target
  package.json
Labels: tech, to merge

#134 [eslint] better configuration and use typescript-eslint
  .prettierrc.js
  package.json
  src/components/DataViewer.vue
  src/components/DataViewerCell.vue
  src/components/DomainSelector.vue
  src/components/Pipeline.vue
  src/components/Step.vue
  src/lib/dataset/index.ts
  src/lib/dataset/mongo.ts
  src/lib/matcher.ts
  src/lib/pipeline.ts
  src/lib/steps.ts
  src/lib/translators/base.ts
  src/lib/translators/mongo.ts
  src/store/backend-plugin.ts
  src/store/index.ts
  src/store/state.ts
  src/typings/mathjs/index.d.ts
  tests/unit/mongo.spec.ts
  tests/unit/pipebuild.spec.ts
  tests/unit/plugins.spec.ts
  tests/unit/translator.spec.ts
  yarn.lock
Labels: need review, tech

#138 Feature :: Delete step
  src/components/DataViewer.vue
  src/components/Pipeline.vue
  src/components/Step.vue
  src/store/backend-plugin.ts
  src/store/mutations.ts
  tests/unit/pipeline.spec.ts
  tests/unit/step.spec.ts
Labels: need review, ui

#136 Feature :: Popover Component
  src/components/Popover.vue
  src/components/constants.ts
  tests/unit/popover.spec.ts
Labels: need review, ui

#143 Feature :: UI rename step
  .storybook/bundle.ts
  .storybook/rollup.config.js
  jest.config.js
  package.json
  playground/App.vue
  rollup.config.js
  src/assets/logo.png
  src/assets/schemas/index.ts
  src/assets/schemas/rename-step__schema.json
  src/components/DataViewer.vue
  src/components/FormRenameStep.vue
  src/components/Pipeline.vue
  src/components/Step.vue
  src/components/StepEditor.vue
  src/components/WidgetAutocomplete.vue
  src/components/WidgetInputText.vue
  src/main.ts
  src/mixins/FormMixin.vue
  src/store/getters.ts
  src/store/mutations.ts
  src/store/state.ts
  src/styles/DataViewer.scss
  src/styles/DomainSelector.scss
  src/styles/ResizablePanels.scss
  src/styles/Steps.scss
  src/styles/_variables.scss
  src/styles/main.scss
  stories/form-rename-step.js
  stories/index.js
  tests/unit/data-viewer.spec.ts
  tests/unit/form-rename-step.spec.ts
  tests/unit/pipeline.spec.ts
  tests/unit/step-editor.spec.ts
  tests/unit/widget-autocomplete.spec.ts
  tests/unit/widget-input-text.spec.ts
  yarn.lock
Labels: ui

#145 Feature :: edit rename step
  playground/App.vue
  src/components/FormRenameStep.vue
  src/components/Pipeline.vue
  src/components/Step.vue
  src/store/getters.ts
  src/store/mutations.ts
  src/store/state.ts
Labels: need review, ui

#141 [store] introduce MutationCallbacks type
  playground/App.vue
  src/components/DomainSelector.vue
  src/components/Pipeline.vue
  src/components/Step.vue
  src/store/mutations.ts
Labels: tech, to merge

#149 [playground] narrow transpilation to the bare minimum
  playground/tsconfig.json
Labels: playground, tech, to merge
