Repository ToucanToco/weaverbird, pull requests merged in 2020-05, with the labels that each got.

#524 Isolate multiselect in z-index rendering
  src/components/stepforms/widgets/MultiInputText.vue
Labels: bug

#528 Fix popover parents registration
  src/components/Popover.vue
Labels: bug, need review

#533 Fix back button style
  src/components/stepforms/StepFormHeader.vue
Labels: bug, need review, ui

#536 text/formula :: change parameters orders to make forms more intuitive
  CHANGELOG.md
  docs/_docs/user-interface/formula.md
  docs/_docs/user-interface/text.md
  docs/img/docs/user-interface/formula_example_conf_1.jpg
  docs/img/docs/user-interface/formula_example_conf_2.jpg
  docs/img/docs/user-interface/formula_example_result_1.jpg
  docs/img/docs/user-interface/formula_example_result_2.jpg
  docs/img/docs/user-interface/formula_step_form.jpg
  docs/img/docs/user-interface/text_example_conf.jpg
  docs/img/docs/user-interface/text_example_result.jpg
  docs/img/docs/user-interface/text_step_form.jpg
  src/components/stepforms/AddTextColumnStepForm.vue
  src/components/stepforms/FormulaStepForm.vue
  tests/unit/add-text-column.spec.ts
  tests/unit/formula-step-form.spec.ts
Labels: ui

#539 Add a trivial state getter to get backendMessage
  CHANGELOG.md
  src/store/getters.ts
  tests/unit/store.spec.ts
Labels: tech

#532 Sort unique values in alphanumeric order
  CHANGELOG.md
  src/lib/dataset/helpers.ts
  tests/unit/dataset.spec.ts
  tests/unit/store.spec.ts
Labels: enhancement, need review

#541 Fix popover opening to choose a variable
  src/components/stepforms/widgets/VariableInput/VariableInput.vue
Labels: bug

#545 v0.17.4
  CHANGELOG.md
  package.json
Labels: release

#546 Playground enhancements
  playground/app.js
  playground/dist/index.html
Labels: playground

#548 Popover click does not propagate to window
  src/components/Popover.vue
Labels: bug
