Repository ToucanToco/weaverbird, pull requests merged in 2020-02, with the labels that each got.

#410 Fix unpivot translation to manage dropna option properly
  CHANGELOG.md
  src/lib/translators/mongo.ts
Labels: bug

#417 Reorder aggregate widget
  src/components/constants.ts
  tests/unit/action-toolbar.spec.ts
Labels: enhancement, ui

#416 add basic support for regexp in filter steps
  CHANGELOG.md
  docs/_docs/tech/steps.md
  docs/_docs/user-interface/filter.md
  src/components/stepforms/schemas/filter.ts
  src/components/stepforms/widgets/FilterSimpleCondition.vue
  src/lib/labeller.ts
  src/lib/steps.ts
  src/lib/translators/mongo.ts
  tests/unit/filter-step-form.spec.ts
  tests/unit/labeller.spec.ts
  tests/unit/mongo.spec.ts
Labels: enhancement, need review, querytranslate, ui

#420 v0.10.0
  CHANGELOG.md
  package.json
Labels: need review, release

#421 standardize "add custom label" in menus
  src/components/constants.ts
Labels: documentation, need review

#422 Add UI for format parameter in todate step
  CHANGELOG.md
  src/components/stepforms/ToDateStepForm.vue
  src/components/stepforms/schemas/todate.ts
  src/lib/translators/mongo4.ts
  tests/unit/mongo.spec.ts
  tests/unit/mongo4.spec.ts
  tests/unit/todate-step-form.spec.ts
  tests/unit/utils.ts
Labels: ui

#419 Allow to set a code editor for the custom step
  CHANGELOG.md
  docs/_docs/tech/custom-code-editor.md
  playground/app.js
  src/components/code-editor.ts
  src/components/stepforms/CustomStepForm.vue
  src/components/stepforms/widgets/CodeEditorWidget.vue
  src/components/stepforms/widgets/DefaultCodeEditor.vue
  src/main.ts
  tests/unit/code-editor-widget.spec.ts
  tests/unit/custom-step-form.spec.ts
  tests/unit/set-code-editor.spec.ts
  tests/unit/textarea-widget.spec.ts
Labels: enhancement, need review

#423 small fixes in documentation
  docs/_data/docs.yml
  docs/img/docs/user-interface/dateextract_menu_example.jpg
Labels: documentation, need review

#427 widget-code-editor re-style
  src/components/stepforms/widgets/CodeEditorWidget.vue
  src/components/stepforms/widgets/DefaultCodeEditor.vue
Labels: need review

#431 v0.11.0
  CHANGELOG.md
  package.json
Labels: need review, release

#437 [doc] fix typo in date-extract page title
  docs/_docs/user-interface/dateextract.md
Labels: bug, documentation, to merge

#433 StepFormButtonbar and StepFormHeader cleaning
  docs/_docs/tech/stepforms.md
  docs/img/StepFormButtonbar.png
  docs/img/StepFormHeader.png
  src/components/QueryBuilder.vue
  src/components/stepforms/AddTextColumnStepForm.vue
  src/components/stepforms/AggregateStepForm.vue
  src/components/stepforms/AppendStepForm.vue
  src/components/stepforms/ArgmaxStepForm.vue
  src/components/stepforms/ArgminStepForm.vue
  src/components/stepforms/ConcatenateStepForm.vue
  src/components/stepforms/ConvertStepForm.vue
  src/components/stepforms/CustomStepForm.vue
  src/components/stepforms/DateExtractStepForm.vue
  src/components/stepforms/DeleteColumnStepForm.vue
  src/components/stepforms/DomainStepForm.vue
  src/components/stepforms/DuplicateColumnStepForm.vue
  src/components/stepforms/FillnaStepForm.vue
  src/components/stepforms/FilterStepForm.vue
  src/components/stepforms/FormulaStepForm.vue
  src/components/stepforms/FromDateStepForm.vue
  src/components/stepforms/JoinStepForm.vue
  src/components/stepforms/PercentageStepForm.vue
  src/components/stepforms/PivotStepForm.vue
  src/components/stepforms/RenameStepForm.vue
  src/components/stepforms/ReplaceStepForm.vue
  src/components/stepforms/SelectColumnStepForm.vue
  src/components/stepforms/SortStepForm.vue
  src/components/stepforms/SplitStepForm.vue
  src/components/stepforms/StepForm.vue
  src/components/stepforms/StepFormButtonbar.vue
  src/components/stepforms/StepFormHeader.vue
  src/components/stepforms/SubstringStepForm.vue
  src/components/stepforms/ToDateStepForm.vue
  src/components/stepforms/ToLowerStepForm.vue
  src/components/stepforms/ToUpperStepForm.vue
  src/components/stepforms/TopStepForm.vue
  src/components/stepforms/UniqueGroupsStepForm.vue
  src/components/stepforms/UnpivotStepForm.vue
  tests/unit/query-builder.spec.ts
  tests/unit/utils.ts
Labels: need review

#438 [pkg] remove rollup-plugin-istanbul
  package.json
  yarn.lock
Labels: tech

#443 Enhancement :: Beautiful New Logo
  README.md
  docs/favicon.ico
  docs/img/logonav.png
  public/favicon.ico
Labels: design, to merge

#440 Refactoring :: move scss files into vue files
  playground/dist/index.html
  src/components/DataViewer.vue
  src/components/DeleteConfirmationModal.vue
  src/components/Pipeline.vue
  src/components/QueryBuilder.vue
  src/components/ResizablePanels.vue
  src/components/Step.vue
  src/components/stepforms/widgets/List.vue
  src/styles/DataViewer.scss
  src/styles/DeleteConfirmationModal.scss
  src/styles/Pipeline.scss
  src/styles/ResizablePanels.scss
  src/styles/Steps.scss
  src/styles/_variables.scss
  src/styles/main.scss
Labels: enhancement, playground

#450 custom step :: add support for templating
  CHANGELOG.md
  src/lib/templating.ts
  tests/unit/templating.spec.ts
Labels: enhancement, need review

#448 Fix :: WidgetList item deletion
  src/components/stepforms/widgets/List.vue
  tests/unit/list-widget.spec.ts
Labels: bug, to merge

#451 v0.12.0
  CHANGELOG.md
  package.json
Labels: need review, release

#434 [mongo translator] :: allow to escape column name in FormulaStep with "[" and "]"
  CHANGELOG.md
  src/components/stepforms/FormulaStepForm.vue
  src/lib/translators/mongo.ts
  src/typings/mathjs/index.d.ts
  tests/unit/mongo.spec.ts
Labels: need review
