Repository ToucanToco/weaverbird, pull requests merged in 2020-07, with the labels that each got.

#566 fix(multiselect): force the multiselect to open bellow
  CHANGELOG.md
  package.json
  src/components/SearchBar.vue
  src/components/stepforms/widgets/Autocomplete.vue
  src/components/stepforms/widgets/MultiInputText.vue
  src/components/stepforms/widgets/Multiselect.vue
Labels: bug, need review

#568 fix: cast values on deeper conditionnal levels
  src/components/stepforms/IfThenElseStepForm.vue
  tests/unit/ifthenelse-step-form.spec.ts
Labels: bug

#570 fix: keep `null` value filter for numeric columns
  src/lib/helpers.ts
  tests/unit/filter-step-form.spec.ts
Labels: bug

#571 v0.19.3
  CHANGELOG.md
  package.json
Labels: release

#575 fix(mongo): join on column names with invalid characters
  src/lib/translators/mongo.ts
  tests/unit/mongo.spec.ts
Labels: bug

#577 fix(pagination): always display pagination for multiple pages dataset
  CHANGELOG.md
  src/components/Pagination.vue
  tests/unit/pagination-component.spec.ts
Labels: bug
