Repository ToucanToco/weaverbird, pull requests merged in 2020-06, with the labels that each got.

#550 Add the 'left outer' to the schema and type enum for JoinStep.
  src/components/stepforms/JoinStepForm.vue
  src/components/stepforms/schemas/join.ts
  src/lib/steps.ts
  tests/unit/join-step-form.spec.ts
Labels: bug, need review

#555 v0.19.0
  CHANGELOG.md
  package.json
Labels: release

#558 Doc :: Fix ifthenelse doc permalink
  CHANGELOG.md
  docs/_docs/user-interface/ifthenelse.md
Labels: documentation, need review

#556 Always show the result's row count.
  src/components/DataViewer.vue
  src/components/Pagination.vue
  src/store/getters.ts
  tests/unit/data-viewer.spec.ts
  tests/unit/pagination-component.spec.ts
  tests/unit/store.spec.ts
Labels: bug, need review

#559 v0.19.1
  CHANGELOG.md
  package.json
Labels: release
