Repository ToucanToco/weaverbird, pull requests merged in 2020-08, with the labels that each got.

#581 fix: remove grouping of addFields steps in mongo query
  CHANGELOG.md
  src/lib/translators/mongo.ts
  tests/unit/mongo.spec.ts
  tests/unit/mongo4.spec.ts
Labels: bug, need review

#584 v0.20.0
  CHANGELOG.md
  package.json
Labels: need review

#585 doc: add `Create a release` section in readme
  README.md
Labels: documentation, need review

#589 v0.21.0
  CHANGELOG.md
  package.json
Labels: release

#593 feat: prevent cyclic jointures between pipelines
  src/components/stepforms/AppendStepForm.vue
  src/components/stepforms/JoinStepForm.vue
  src/components/stepforms/widgets/Autocomplete.vue
  src/components/stepforms/widgets/Multiselect.vue
  src/main.ts
  src/store/getters.ts
  src/store/utils/dereference-pipeline.ts
  tests/unit/append-step-form.spec.ts
  tests/unit/autocomplete-widget.spec.ts
  tests/unit/dereference-pipeline.spec.ts
  tests/unit/input-text-widget.spec.ts
  tests/unit/join-step-form.spec.ts
  tests/unit/multiselect-widget.spec.ts
  tests/unit/store.spec.ts
Labels: enhancement, need review

#596 v0.22.0
  CHANGELOG.md
  package.json
Labels: need review, release

#599 fix: accessibility for delete icons in filter step form
  src/components/ConditionsEditor/ConditionsGroup.vue
Labels: bug

#600 fix(variables): allow to use unique variable in multiInputText of fil…
  src/components/FilterEditor.vue
  src/components/stepforms/widgets/FilterSimpleCondition.vue
Labels: bug

#601 fix: remove duplicate delete row icon
  src/components/ConditionsEditor/ConditionsGroup.vue
Labels: bug

#603 v0.23.0
  CHANGELOG.md
  package.json
Labels: need review, release

#606 v0.23.1
  CHANGELOG.md
  package.json
Labels: release

#609 v0.23.2
  CHANGELOG.md
  package.json
Labels: release

#610 cumsum step :: simplify mongo translation and keep track of all columns
  src/lib/translators/mongo.ts
  tests/unit/mongo.spec.ts
Labels: mongo, need review, querytranslate

#615 feat(variables): add advanced variable modal inputs
  src/components/stepforms/widgets/Autocomplete.vue
  src/components/stepforms/widgets/InputText.vue
  src/components/stepforms/widgets/MultiVariableInput.vue
  src/components/stepforms/widgets/VariableInput.vue
  src/components/stepforms/widgets/VariableInputs/AdvancedVariableModal.vue
  tests/unit/advanced-variable-modal.spec.ts
Labels: need review

#616 fix(muti-variable-input): fix button picker style and multiselect pick
  src/components/stepforms/widgets/MultiInputText.vue
  src/components/stepforms/widgets/Multiselect.vue
Labels: bug, need review

#612 fix(data-viewer): contextual menus now hide on dataset change
  src/components/DataViewer.vue
  tests/unit/data-viewer.spec.ts
Labels: bug

#624 v0.24.0
  CHANGELOG.md
  package.json
Labels: need review, release
