Repository ToucanToco/weaverbird, pull requests merged in 2020-10, with the labels that each got.

#655 fix: set the multivariableinput z-index
  src/components/stepforms/widgets/MultiVariableInput.vue
Labels: bug, need review

#656 v0.27.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#657 v0.27.1
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: need review, release

#659 fix(multiinput-text): display dropdown without be overlapped by next input
  src/components/stepforms/widgets/MultiInputText.vue
  src/components/stepforms/widgets/MultiVariableInput.vue
Labels: need review

#660 v0.27.2
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: need review, release

#661 v0.28.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: need review, release

#663 v0.28.1
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: need review, release

#664 pivot step: add variables support
  src/components/stepforms/PivotStepForm.vue
Labels: need review, ui

#668 pivot step: support variables interpolation
  CHANGELOG.md
  src/lib/templating.ts
  tests/unit/templating.spec.ts
Labels: need review

#669 Fix types in JoinStepForm.vue
  src/components/stepforms/JoinStepForm.vue
Labels: need review

#674 feat(server): support for logical and/or in filter
  server/weaverbird/steps/filter.py
Labels: py pandas

#676 tests(server): add tests for logical conditions
  server/tests/steps/test_filter.py
Labels: need review, tech

#681 feat(playground): load all csv files in playground/datastore
  server/playground.py
Labels: playground
