Repository ToucanToco/weaverbird, pull requests merged in 2020-12, with the labels that each got.

#772 v0.32.1
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: need review, release

#776 v0.31.1
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: need review, release

#777 fix(filter-condition): dont cast undefined value when add group or condition
  src/components/ConditionsEditor/ConditionsEditor.vue
  src/components/ConditionsEditor/ConditionsGroup.vue
  src/components/FilterEditor.vue
  src/components/stepforms/widgets/FilterSimpleCondition.vue
Labels: bug, need review

#778 v0.33.2
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: need review, release

#779 chore: remove sonar warnings
  src/components/ActionMenu.vue
  src/components/ActionToolbarButton.vue
  src/components/DataTypesMenu.vue
  src/components/DataViewer.vue
  src/components/DeleteConfirmationModal.vue
  src/components/Pagination.vue
  src/components/Pipeline.vue
  src/components/QueryBuilder.vue
  src/components/SearchBar.vue
  src/components/Step.vue
  src/components/stepforms/StatisticsStepForm.vue
  src/components/stepforms/StepFormHeader.vue
  src/components/stepforms/widgets/Aggregation.vue
  src/components/stepforms/widgets/Autocomplete.vue
  src/components/stepforms/widgets/IfThenElseWidget.vue
  src/components/stepforms/widgets/InputNumber.vue
  src/components/stepforms/widgets/InputText.vue
  src/components/stepforms/widgets/JoinColumns.vue
  src/components/stepforms/widgets/List.vue
  src/components/stepforms/widgets/MultiInputText.vue
  src/components/stepforms/widgets/SortColumn.vue
  src/styles/utils/v-tooltip.scss
Labels: need review, tech

#781 chore: remove sonar warnings
  src/components/stepforms/widgets/MultiInputText.vue
  src/components/stepforms/widgets/Multiselect.vue
  src/components/stepforms/widgets/VariableInputs/VariableTag.vue
  src/styles/_variables.scss
Labels: need review, tech

#783 v0.33.3
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#784 feat(server): raise more helpful error on pipeline failure
  server/tests/test_pipeline_executor.py
  server/weaverbird/pipeline_executor.py
Labels: enhancement, need review, py pandas

#760 fix(waterfall): we aggregate values for a given label/ group
  server/tests/steps/test_waterfall.py
  server/weaverbird/steps/waterfall.py
Labels: bug, need review, py pandas

#786 fix(conditions-editor): pass the default value to ConditionsGroup
  CHANGELOG.md
  package.json
  sonar-project.properties
  src/components/ConditionsEditor/ConditionsEditor.vue
Labels: bug

#787 fix: pass default value everywhere
  CHANGELOG.md
  package.json
  sonar-project.properties
  src/components/ConditionsEditor/ConditionsEditor.vue
  src/components/ConditionsEditor/ConditionsGroup.vue
  stories/filter-editor.js
  tests/unit/conditions-editor.spec.ts
  tests/unit/conditions-group.spec.ts
Labels: bug

#785 feat(pandas log memory usage): each step of the pipeline logs memory usage
  server/weaverbird/pipeline_executor.py
  server/weaverbird/utils/__init__.py
  server/weaverbird/utils/size.py
  server/weaverbird/utils/stopwatch.py
Labels: py pandas

#765 test(front): fix coverage of an excluded catch block
  src/store/actions.ts
Labels: tech

#793 feat(front): add a tooltip for each column name
  CHANGELOG.md
  src/components/DataViewer.vue
  src/styles/utils/v-tooltip.scss
  tests/unit/data-viewer.spec.ts
Labels: enhancement, javascript

#797 v0.34.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#799 fix(front): preview request only once when changing domain
  src/components/QueryBuilder.vue
Labels: bug, javascript

#800 fix(mongo): fix usage of $regexMatch
  CHANGELOG.md
  src/lib/translators/mongo.ts
  tests/unit/mongo.spec.ts
Labels: bug, javascript, need review

#801 build(front): v0.34.1
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: javascript, release

#802 perf: optimize aggregate step
  server/weaverbird/steps/aggregate.py
Labels: py pandas

#803 Feat/pandas duration step
  docs/_docs/tech/steps.md
  server/pyproject.toml
  server/tests/steps/test_duration.py
  server/weaverbird/pipeline.py
  server/weaverbird/steps/__init__.py
  server/weaverbird/steps/duration.py
  src/lib/translators/pandas.ts
Labels: py pandas

#806 Feat/pandas add missing dates
  docs/_docs/user-interface/addmissingdates.md
  server/tests/steps/test_addmissingdates.py
  server/weaverbird/pipeline.py
  server/weaverbird/steps/__init__.py
  server/weaverbird/steps/addmissingdates.py
  src/lib/translators/pandas.ts
Labels: py pandas
