Repository ToucanToco/weaverbird, pull requests merged in 2020-04, with the labels that each got.

#490 Prevent column override when aggregating on an exiting column
  CHANGELOG.md
  src/components/stepforms/AggregateStepForm.vue
  tests/unit/aggregate-step-form.spec.ts
Labels: bug, need review

#496 v0.15.1
  CHANGELOG.md
  package.json
Labels: release

#492 Improve Popover interface
  CHANGELOG.md
  src/components/ActionMenu.vue
  src/components/ActionToolbarButton.vue
  src/components/DataTypesMenu.vue
  src/components/DataViewer.vue
  src/components/Popover.vue
  tests/unit/action-menu.spec.ts
  tests/unit/action-toolbar-button.spec.ts
  tests/unit/data-types-menu.spec.ts
  tests/unit/data-viewer.spec.ts
  tests/unit/popover.spec.ts
Labels: tech

#506 addLocalUnique to dataset handles the pagination
  src/components/DataViewer.vue
  src/lib/dataset/helpers.ts
  src/store/getters.ts
  tests/unit/dataset.spec.ts
  tests/unit/plugins.spec.ts
  tests/unit/store.spec.ts
Labels: need review
