Repository ToucanToco/weaverbird, pull requests merged in 2020-09, with the labels that each got.

#626 feat(codeEditor): use a specific config in a codeEditorWidget
  CHANGELOG.md
  docs/_docs/tech/custom-code-editor.md
  playground/app.js
  src/components/code-editor.ts
  src/components/stepforms/widgets/CodeEditorWidget.vue
  src/main.ts
  tests/unit/code-editor-widget.spec.ts
  tests/unit/set-code-editor.spec.ts
Labels: need review

#631 feat(advanced-variable): update an advanced variable
  src/components/stepforms/widgets/MultiInputText.vue
  src/components/stepforms/widgets/MultiVariableInput.vue
  src/components/stepforms/widgets/Multiselect.vue
  src/components/stepforms/widgets/VariableInput.vue
  src/components/stepforms/widgets/VariableInputs/AdvancedVariableModal.vue
  src/components/stepforms/widgets/VariableInputs/VariableInputBase.vue
  src/components/stepforms/widgets/VariableInputs/VariableTag.vue
  stories/variable.js
  tests/unit/advanced-variable-modal.spec.ts
  tests/unit/multi-input-text-widget.spec.ts
  tests/unit/multi-variable-input.spec.ts
  tests/unit/multiselect-widget.spec.ts
  tests/unit/variable-input-base.spec.ts
  tests/unit/variable-input.spec.ts
  tests/unit/variable-tag.spec.ts
Labels: need review

#632 chore(playground): add variables to playground
  playground/app.js
Labels: need review

#633 feat(package-version): display package version in documentation link
  docs/_docs/contributing/new-step.md
  src/components/QueryBuilder.vue
  src/components/stepforms/AddTextColumnStepForm.vue
  src/components/stepforms/AggregateStepForm.vue
  src/components/stepforms/AppendStepForm.vue
  src/components/stepforms/ArgmaxStepForm.vue
  src/components/stepforms/ArgminStepForm.vue
  src/components/stepforms/ConcatenateStepForm.vue
  src/components/stepforms/ConvertStepForm.vue
  src/components/stepforms/CumSumStepForm.vue
  src/components/stepforms/CustomStepForm.vue
  src/components/stepforms/DateExtractStepForm.vue
  src/components/stepforms/DeleteColumnStepForm.vue
  src/components/stepforms/DomainStepForm.vue
  src/components/stepforms/DuplicateColumnStepForm.vue
  src/components/stepforms/EvolutionStepForm.vue
  src/components/stepforms/FillnaStepForm.vue
  src/components/stepforms/FilterStepForm.vue
  src/components/stepforms/FormulaStepForm.vue
  src/components/stepforms/FromDateStepForm.vue
  src/components/stepforms/IfThenElseStepForm.vue
  src/components/stepforms/JoinStepForm.vue
  src/components/stepforms/PercentageStepForm.vue
  src/components/stepforms/PivotStepForm.vue
  src/components/stepforms/RankStepForm.vue
  src/components/stepforms/RenameStepForm.vue
  src/components/stepforms/ReplaceStepForm.vue
  src/components/stepforms/RollupStepForm.vue
  src/components/stepforms/SelectColumnStepForm.vue
  src/components/stepforms/SortStepForm.vue
  src/components/stepforms/SplitStepForm.vue
  src/components/stepforms/StepForm.vue
  src/components/stepforms/StepFormHeader.vue
  src/components/stepforms/SubstringStepForm.vue
  src/components/stepforms/ToDateStepForm.vue
  src/components/stepforms/ToLowerStepForm.vue
  src/components/stepforms/ToUpperStepForm.vue
  src/components/stepforms/TopStepForm.vue
  src/components/stepforms/UniqueGroupsStepForm.vue
  src/components/stepforms/UnpivotStepForm.vue
  src/components/stepforms/WaterfallStepForm.vue
  tests/unit/query-builder.spec.ts
Labels: need review

#621 aggregate step :: option to keep original granularity and add aggregations in new columns
  CHANGELOG.md
  docs/_docs/tech/steps.md
  docs/_docs/user-interface/aggregate.md
  docs/img/docs/user-interface/aggregate_example_conf.jpg
  docs/img/docs/user-interface/aggregate_example_conf_1.jpg
  docs/img/docs/user-interface/aggregate_example_conf_2.jpg
  docs/img/docs/user-interface/aggregate_example_result.jpg
  docs/img/docs/user-interface/aggregate_example_result_1.jpg
  docs/img/docs/user-interface/aggregate_example_result_2.jpg
  docs/img/docs/user-interface/aggregate_step_form.jpg
  src/components/stepforms/AggregateStepForm.vue
  src/components/stepforms/schemas/aggregate.ts
  src/lib/steps.ts
  src/lib/templating.ts
  src/lib/translators/mongo.ts
  tests/unit/aggregate-step-form.spec.ts
  tests/unit/labeller.spec.ts
  tests/unit/mongo.spec.ts
  tests/unit/templating.spec.ts
Labels: need review, querytranslate, ui

#639 chore(sonar): fix missing cover condition
  tests/unit/multiselect-widget.spec.ts
Labels: need review

#640 fix(advanced-variable-modal): remove style of code editor
  src/components/stepforms/widgets/VariableInputs/AdvancedVariableModal.vue
Labels: need review

#642 fix(load-all-values): keep action menu open
  src/components/DataViewer.vue
  tests/unit/data-viewer.spec.ts
Labels: need review

#641 fix(variables): fix types
  src/components/FilterEditor.vue
  src/components/stepforms/AddTextColumnStepForm.vue
  src/components/stepforms/AggregateStepForm.vue
  src/components/stepforms/ArgmaxStepForm.vue
  src/components/stepforms/ArgminStepForm.vue
  src/components/stepforms/ColumnPicker.vue
  src/components/stepforms/ConcatenateStepForm.vue
  src/components/stepforms/CumSumStepForm.vue
  src/components/stepforms/EvolutionStepForm.vue
  src/components/stepforms/FilterStepForm.vue
  src/components/stepforms/FormulaStepForm.vue
  src/components/stepforms/IfThenElseStepForm.vue
  src/components/stepforms/RankStepForm.vue
  src/components/stepforms/SplitStepForm.vue
  src/components/stepforms/TopStepForm.vue
  src/components/stepforms/WaterfallStepForm.vue
  src/components/stepforms/widgets/Aggregation.vue
  src/components/stepforms/widgets/Autocomplete.vue
  src/components/stepforms/widgets/FilterSimpleCondition.vue
  src/components/stepforms/widgets/IfThenElseWidget.vue
  src/components/stepforms/widgets/InputNumber.vue
  src/components/stepforms/widgets/InputText.vue
  src/components/stepforms/widgets/JoinColumns.vue
  src/components/stepforms/widgets/List.vue
  src/components/stepforms/widgets/MultiInputText.vue
  src/components/stepforms/widgets/MultiVariableInput.vue
  src/components/stepforms/widgets/Multiselect.vue
  src/components/stepforms/widgets/VariableInput.vue
  src/components/stepforms/widgets/VariableInputs/VariableInputBase.vue
  src/components/stepforms/widgets/VariableInputs/VariableTag.vue
Labels: need review

#643 v0.25.0
  CHANGELOG.md
  package.json
Labels: need review, release

#647 v0.25.2
  CHANGELOG.md
  package.json
Labels: release

#648 fillna step: support multiple columns
  CHANGELOG.md
  docs/_docs/tech/steps.md
  docs/_docs/user-interface/fillna.md
  docs/img/docs/user-interface/fillna_example_conf.jpg
  docs/img/docs/user-interface/fillna_example_result.jpg
  docs/img/docs/user-interface/fillna_step_form.jpg
  src/components/stepforms/FillnaStepForm.vue
  src/components/stepforms/schemas/fillna.ts
  src/lib/steps.ts
  src/lib/translators/mongo.ts
  tests/unit/fillna-step-form.spec.ts
  tests/unit/mongo.spec.ts
Labels: need review, querytranslate, ui

#651 v0.26.0
  CHANGELOG.md
  package.json
Labels: release
