Repository ToucanToco/weaverbird, pull requests merged in 2020-03, with the labels that each got.

#454 Map domains to collection with a translator method
  src/lib/translators/mongo.ts
  tests/unit/mongo.spec.ts
Labels: enhancement

#463 formula step :: update doc (escaping column names with whitespaces)
  docs/_docs/tech/steps.md
  docs/_docs/user-interface/formula.md
  docs/img/docs/user-interface/formula_example_conf_1.jpg
  docs/img/docs/user-interface/formula_example_conf_2.jpg
  docs/img/docs/user-interface/formula_example_result_1.jpg
  docs/img/docs/user-interface/formula_example_result_2.jpg
Labels: documentation

#466 fix default dataset in playground
  playground/server.js
Labels: playground, to merge

#467 Fix :: Top groups
  src/components/stepforms/TopStepForm.vue
Labels: bug, need review

#470 0.13.0
  CHANGELOG.md
  package.json
Labels: need review, release

#471 0.13.1
  CHANGELOG.md
  package.json
Labels: release

#468 reset pagination after some mutations
  src/store/mutations.ts
  tests/unit/store.spec.ts
Labels: bug, to merge

#475 v0.14.0
  CHANGELOG.md
  package.json
Labels: release

#472 fix :: replaceWidget change props behavior
  src/components/stepforms/ReplaceStepForm.vue
  src/components/stepforms/widgets/Replace.vue
  tests/unit/replace-widget.spec.ts
Labels: bug, need review

#479 Update FilterStep technical doc
  docs/_docs/tech/steps.md
Labels: documentation

#480 hyperlinks :: add 'nooponer' protection to _blank targets
  src/components/QueryBuilder.vue
  src/components/stepforms/StepFormHeader.vue
Labels: need review

#481 Aggregation Step (a.k.a "groupby"): add "first" and "last" aggFunction
  src/components/stepforms/schemas/aggregate.ts
  src/components/stepforms/widgets/Aggregation.vue
  src/lib/labeller.ts
  src/lib/steps.ts
Labels: need review

#476 Fix :: sort step change props propagation
  src/components/stepforms/SortStepForm.vue
  src/components/stepforms/widgets/SortColumn.vue
  tests/unit/sort-column-widget.spec.ts
  tests/unit/sort-step-form.spec.ts
Labels: bug, need review

#473 Revamp FilterStep to allow nested conditions trees
  .storybook/bundle.ts
  docs/_docs/user-interface/filter.md
  docs/img/docs/user-interface/filter_example_conf.jpg
  docs/img/docs/user-interface/filter_example_result.jpg
  docs/img/docs/user-interface/filter_step_form.jpg
  src/components/ConditionsEditor/ConditionsEditor.vue
  src/components/ConditionsEditor/ConditionsGroup.vue
  src/components/ConditionsEditor/tree-types.ts
  src/components/stepforms/ConditionsEditor/ConditionForm.vue
  src/components/stepforms/FilterStepForm.vue
  src/components/stepforms/StepFormHeader.vue
  src/components/stepforms/convert-filter-step-tree.ts
  src/components/stepforms/schemas/filter.ts
  src/components/stepforms/widgets/FilterSimpleCondition.vue
  stories/conditions-editor.js
  tests/unit/condition-form.spec.ts
  tests/unit/conditions-group.spec.ts
  tests/unit/convert-filter-step-tree.spec.ts
  tests/unit/filter-simple-condition-widget.spec.ts
  tests/unit/filter-step-form.spec.ts
Labels: enhancement, need review

#484 Change how updates are propagated from Autocomplete widget
  src/components/stepforms/widgets/Autocomplete.vue
  tests/unit/autocomplete-widget.spec.ts
Labels: :recycle: cleaning :recycle:, tech

#482 [pkg] v0.15.0
  CHANGELOG.md
  package.json
Labels: release

#485 Authorize small drops of total coverage
  codecov.yml
Labels: tech

#489 Replace id of widgets by class
  CHANGELOG.md
  docs/_docs/contributing/new-step.md
  src/components/stepforms/AddTextColumnStepForm.vue
  src/components/stepforms/AggregateStepForm.vue
  src/components/stepforms/AppendStepForm.vue
  src/components/stepforms/ArgmaxStepForm.vue
  src/components/stepforms/ArgminStepForm.vue
  src/components/stepforms/ColumnPicker.vue
  src/components/stepforms/ConcatenateStepForm.vue
  src/components/stepforms/ConvertStepForm.vue
  src/components/stepforms/CumSumStepForm.vue
  src/components/stepforms/DateExtractStepForm.vue
  src/components/stepforms/DeleteColumnStepForm.vue
  src/components/stepforms/DomainStepForm.vue
  src/components/stepforms/DuplicateColumnStepForm.vue
  src/components/stepforms/EvolutionStepForm.vue
  src/components/stepforms/FillnaStepForm.vue
  src/components/stepforms/FormulaStepForm.vue
  src/components/stepforms/FromDateStepForm.vue
  src/components/stepforms/JoinStepForm.vue
  src/components/stepforms/PercentageStepForm.vue
  src/components/stepforms/PivotStepForm.vue
  src/components/stepforms/RenameStepForm.vue
  src/components/stepforms/ReplaceStepForm.vue
  src/components/stepforms/RollupStepForm.vue
  src/components/stepforms/SelectColumnStepForm.vue
  src/components/stepforms/SortStepForm.vue
  src/components/stepforms/SplitStepForm.vue
  src/components/stepforms/SubstringStepForm.vue
  src/components/stepforms/ToDateStepForm.vue
  src/components/stepforms/ToLowerStepForm.vue
  src/components/stepforms/ToUpperStepForm.vue
  src/components/stepforms/TopStepForm.vue
  src/components/stepforms/UniqueGroupsStepForm.vue
  src/components/stepforms/UnpivotStepForm.vue
  src/components/stepforms/widgets/Aggregation.vue
  src/components/stepforms/widgets/Autocomplete.vue
  src/components/stepforms/widgets/CodeEditorWidget.vue
  src/components/stepforms/widgets/FilterSimpleCondition.vue
  src/components/stepforms/widgets/InputText.vue
  src/components/stepforms/widgets/JoinColumns.vue
  src/components/stepforms/widgets/List.vue
  src/components/stepforms/widgets/MultiInputText.vue
  src/components/stepforms/widgets/Multiselect.vue
  src/components/stepforms/widgets/Replace.vue
  src/components/stepforms/widgets/SortColumn.vue
  tests/unit/aggregation-widget.spec.ts
  tests/unit/evolution-step-form.spec.ts
  tests/unit/filter-simple-condition-widget.spec.ts
  tests/unit/pivot-step-form.spec.ts
  tests/unit/split-step-form.spec.ts
  tests/unit/substring-step-form.spec.ts
  tests/unit/top-step-form.spec.ts
  tests/unit/unpivot-step-form.spec.ts
Labels: bug, need review

#491 Fix checkbox props propagation
  CHANGELOG.md
  src/components/stepforms/widgets/Checkbox.vue
  tests/unit/checkbox-widget.spec.ts
Labels: bug, need review
