Repository ToucanToco/weaverbird, pull requests merged in 2021-11, with the labels that each got.

#1165 chore(build): storybook reload css
  .storybook/rollup.config.js
Labels: bug, need review

#1164 feat(ui): reset button for DateRangeInput TCTC-1097
  src/components/stepforms/widgets/DateComponents/DateRangeInput.vue
  src/lib/dates.ts
  tests/unit/date-range-input.spec.ts
Labels: need review, ui

#1166 fix(range calendar): clamp selection to bounds when switching granularity TCTC-1031
  src/components/DatePicker/Calendar.vue
  src/components/DatePicker/CustomGranularityCalendar.vue
  src/components/stepforms/widgets/DateComponents/TabbedRangeCalendars.vue
  src/lib/dates.ts
  stories/dates/date-range-input.js
  tests/unit/calendar.spec.ts
  tests/unit/custom-granularity-calendar.spec.ts
  tests/unit/lib/dates.spec.ts
  tests/unit/tabbed-range-calendars.spec.ts
Labels: need review, ui, fix

#1163 feat(relative date range): add before/after field in form
  rollup.config.js
  src/components/stepforms/widgets/DateComponents/DateRangeInput.vue
  src/components/stepforms/widgets/DateComponents/RelativeDateForm.vue
  src/components/stepforms/widgets/DateComponents/RelativeDateRangeForm.vue
  src/lib/dates.ts
  tests/unit/lib/dates.spec.ts
  tests/unit/new-date-input.spec.ts
  tests/unit/relative-date-form-widget.spec.ts
  tests/unit/relative-date-range-form-widget.spec.ts
Labels: enhancement, ui

#1167 fix(custom-granularity-calendar): update navigation based on selected option when switching between tabs TCTC-1031
  src/components/DatePicker/CustomGranularityCalendar.vue
  tests/unit/custom-granularity-calendar.spec.ts
Labels: bug, need review, javascript

#1168 v0.73.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: ui, release

#1169 chore(lib): export pagination component TCTC-1076
  CHANGELOG.md
  src/components/DataViewer.vue
  src/components/Pagination.vue
  src/main.ts
  tests/unit/pagination-component.spec.ts
Labels: need review, tech, ui

#1170 v0.74.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#1172 style(ui): remove background on DateRangeInput reset btn TCTC-1097
  src/components/stepforms/widgets/DateComponents/DateRangeInput.vue
Labels: need review, ui

#1173 fix(relative date range form): use the right operator names TCTC-1182
  src/components/stepforms/widgets/DateComponents/RelativeDateRangeForm.vue
  src/lib/dates.ts
  tests/unit/lib/dates.spec.ts
  tests/unit/relative-date-range-form-widget.spec.ts
Labels: need review, ui, fix

#1174 build(ui): v0.75.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#1176 build(storybook): avoid babeling storybok bundle
  .storybook/.babelrc
Labels: need review, build, ui, fix

#1177 refactor(relative date range): use a proper "operator" property TCTC-1183
  CHANGELOG.md
  src/components/DatePicker/transform-value-to-date-or-range.ts
  src/components/stepforms/widgets/DateComponents/DateRangeInput.vue
  src/components/stepforms/widgets/DateComponents/RelativeDateRangeForm.vue
  src/lib/dates.ts
  stories/dates/date-range-input.js
  tests/unit/date-range-input.spec.ts
  tests/unit/lib/dates.spec.ts
  tests/unit/relative-date-range-form-widget.spec.ts
  tests/unit/transform-value-to-date-or-range.spec.ts
Labels: need review, tech, ui

#1178 feat(date-range-input): enable to use a compact mode for mobile purpose TCTC-755
  src/components/DatePicker/CustomGranularityCalendar.vue
  src/components/Tabs.vue
  src/components/stepforms/widgets/DateComponents/DateRangeInput.vue
  src/components/stepforms/widgets/DateComponents/TabbedRangeCalendars.vue
  stories/dates/date-range-input.js
  tests/unit/date-range-input.spec.ts
Labels: need review, design, javascript

#1179 v0.76.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#1181 fix(calendars): reset value when selected range is out of updated bounds TCTC-1248
  src/components/DatePicker/Calendar.vue
  src/components/DatePicker/CustomGranularityCalendar.vue
  src/components/stepforms/widgets/DateComponents/TabbedRangeCalendars.vue
  src/lib/dates.ts
  tests/unit/calendar.spec.ts
  tests/unit/custom-granularity-calendar.spec.ts
  tests/unit/lib/dates.spec.ts
  tests/unit/tabbed-range-calendars.spec.ts
Labels: bug, need review, javascript

#1182 v0.76.1
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#1183 fix(sql): replace step work w & w/ quotes [TCTC-1246]
  server/tests/backends/fixtures/replace/snowflake_simple.json
  server/tests/steps/sql_translator/test_replace.py
  server/weaverbird/backends/sql_translator/steps/replace.py
Labels: bug, need review

#1184 fix(sql): fix filter step on date [TCTC-1242]
  server/tests/backends/fixtures/HOWTO-create-fixtures.md
  server/tests/backends/fixtures/filter/dates.json
  server/tests/backends/pandas_executor/test_pandas_executor_steps.py
  server/tests/backends/sql_translator/test_snowflake_translator_steps.py
  server/tests/backends/sql_translator/test_sql_translator_steps.py
  server/tests/steps/sql_translator/test_filter.py
  server/tests/utils.py
  server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
Labels: bug, need review

#1187 fix(variable-input-base): avoid variable to replace single string when selecting a variable in multiple mode TCTC-1047
  src/components/stepforms/widgets/VariableInputs/VariableInputBase.vue
  tests/unit/variable-input-base.spec.ts
Labels: javascript, fix

#1188 v0.76.2
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#1186 chore(playground): add dates test case in playground TCTC-1192
  playground/app.js
  playground/datastore/sin-from-2019-to-2022.json
  playground/dist/index.html
  server/playground.py
  src/store/state.ts
Labels: need review, ui, playground

#1190 feat(new-date-input): enable to use advanced variable TCTC-1195
  src/assets/FA-ICONS.ts
  src/components/stepforms/widgets/DateComponents/CustomVariableList.vue
  src/components/stepforms/widgets/DateComponents/DateRangeInput.vue
  src/components/stepforms/widgets/DateComponents/NewDateInput.vue
  src/components/stepforms/widgets/VariableInputs/VariableChooser.vue
  src/components/stepforms/widgets/VariableInputs/VariableList.vue
  src/components/stepforms/widgets/VariableInputs/VariableTag.vue
  tests/unit/custom-variable-list.spec.ts
  tests/unit/new-date-input.spec.ts
  tests/unit/variable-chooser.spec.ts
  tests/unit/variable-list.spec.ts
  tests/unit/variable-tag.spec.ts
Labels: ui, javascript

#1192 feat(playground): provide a mongo 5 container with data from playground TCTC-1197
  playground/Dockerfile-mongo
  playground/init-mongo/01-import-files.sh
  playground/init-mongo/02-adjust-types.js
Labels: playground

#1191 feat(filter-step): use specific operator for date columns TCTC-1193
  src/components/stepforms/schemas/filter.ts
  src/components/stepforms/schemas/ifthenelse.ts
  src/components/stepforms/widgets/FilterSimpleCondition.vue
  src/lib/labeller.ts
  src/lib/steps.ts
  src/lib/translators/mongo.ts
  src/lib/translators/mongo42.ts
  tests/unit/filter-simple-condition-widget.spec.ts
  tests/unit/labeller.spec.ts
Labels: javascript

#1121 doc(dates): rework preparation of dates operations
  docs/_docs/tech/dates.md
  docs/_docs/tech/relative-dates.md
  server/src/weaverbird/pipeline/conditions.py
  server/src/weaverbird/pipeline/dates.py
  src/lib/steps.ts
Labels: documentation

#1193 feat(filter-step): replace date widget with new date input TCTC-1194
  src/components/stepforms/widgets/DateComponents/CustomVariableList.vue
  src/components/stepforms/widgets/DateComponents/NewDateInput.vue
  src/components/stepforms/widgets/FilterSimpleCondition.vue
  src/styles/_variables.scss
  tests/unit/filter-simple-condition-widget.spec.ts
  tests/unit/new-date-input.spec.ts
Labels: :eye: review ongoing :eye:, javascript

#1196 feat(playground): add dates variables to test in playground TCTC-1196
  playground/app.js
  src/lib/templating.ts
Labels: playground, javascript

#1103 feat(mongo): relative date support in filter step (mongo 5+) TCTC-1197
  .github/workflows/ci-ui.yml
  docs/_docs/tech/steps.md
  docs/_docs/user-interface/addmissingdates.md
  docs/_docs/user-interface/aggregate.md
  docs/_docs/user-interface/append.md
  docs/_docs/user-interface/argmax.md
  docs/_docs/user-interface/argmin.md
  docs/_docs/user-interface/comparetext.md
  docs/_docs/user-interface/concatenate.md
  docs/_docs/user-interface/convert.md
  docs/_docs/user-interface/cumsum.md
  docs/_docs/user-interface/custom.md
  docs/_docs/user-interface/dateextract.md
  docs/_docs/user-interface/delete.md
  docs/_docs/user-interface/duplicate.md
  docs/_docs/user-interface/duration.md
  docs/_docs/user-interface/evolution.md
  docs/_docs/user-interface/fillna.md
  docs/_docs/user-interface/filter.md
  docs/_docs/user-interface/formula.md
  docs/_docs/user-interface/fromdate.md
  docs/_docs/user-interface/ifthenelse.md
  docs/_docs/user-interface/join.md
  docs/_docs/user-interface/keep.md
  docs/_docs/user-interface/lowercase.md
  docs/_docs/user-interface/movingaverage.md
  docs/_docs/user-interface/percentage.md
  docs/_docs/user-interface/pivot.md
  docs/_docs/user-interface/rank.md
  docs/_docs/user-interface/rename.md
  docs/_docs/user-interface/replace.md
  docs/_docs/user-interface/rollup.md
  docs/_docs/user-interface/sort.md
  docs/_docs/user-interface/split.md
  docs/_docs/user-interface/statistics.md
  docs/_docs/user-interface/substring.md
  docs/_docs/user-interface/text.md
  docs/_docs/user-interface/todate.md
  docs/_docs/user-interface/top.md
  docs/_docs/user-interface/totals.md
  docs/_docs/user-interface/trim.md
  docs/_docs/user-interface/uniquegroups.md
  docs/_docs/user-interface/unpivot.md
  docs/_docs/user-interface/uppercase.md
  docs/_docs/user-interface/waterfall.md
  playground/app.js
  src/lib/dates.ts
  src/lib/translators/index.ts
  src/lib/translators/mongo.ts
  src/lib/translators/mongo5.ts
  tests/unit/lib/dataset/pandas.spec.ts
  tests/unit/mongo.spec.ts
  tests/unit/translator.spec.ts
Labels: :hammer: wip :hammer:, mongo, javascript

#1197 fix(playground): add symlink with static files
  server/static
Labels: playground

#1198 fix(filter-step): update invalid operator when switching relative date feature flag TCTC-1193
  src/components/stepforms/FilterStepForm.vue
  src/components/stepforms/widgets/FilterSimpleCondition.vue
  tests/unit/filter-simple-condition-widget.spec.ts
Labels: bug, need review, javascript

#1195 fix(filter-step): keep relative date selected when switching from/until operators TCTC-1193
  src/components/stepforms/widgets/FilterSimpleCondition.vue
  src/lib/dates.ts
  src/lib/helpers.ts
  tests/unit/filter-simple-condition-widget.spec.ts
  tests/unit/helpers.spec.ts
  tests/unit/lib/dates.spec.ts
Labels: bug, javascript

#1199 doc(playground): update playground url
  README.md
Labels: playground

#1200 fix(playground): mongo empty results were not formed correctly TCTC-905
  server/playground.py
Labels: mongo, playground

#1203 feat(playground): improve the debug panel display
  playground/dist/index.html
Labels: playground

#1201 feat(dates): use relative date with variables in new date input and clean relative date interfaces TCTC-1321
  .storybook/bundle.ts
  src/components/DatePicker/transform-value-to-date-or-range.ts
  src/components/Step.vue
  src/components/stepforms/widgets/DateComponents/DateRangeInput.vue
  src/components/stepforms/widgets/DateComponents/NewDateInput.vue
  src/components/stepforms/widgets/DateComponents/RelativeDateForm.vue
  src/components/stepforms/widgets/DateComponents/RelativeDateRangeForm.vue
  src/lib/dates.ts
  src/lib/translators/mongo5.ts
  stories/dates/date-range-input.js
  stories/dates/new-date-input.js
  stories/dates/relative-date-form.js
  stories/dates/relative-date-range-form.js
  tests/unit/date-range-input.spec.ts
  tests/unit/helpers.spec.ts
  tests/unit/labeller.spec.ts
  tests/unit/lib/dates.spec.ts
  tests/unit/mongo.spec.ts
  tests/unit/new-date-input.spec.ts
  tests/unit/relative-date-form-widget.spec.ts
  tests/unit/relative-date-range-form-widget.spec.ts
  tests/unit/transform-value-to-date-or-range.spec.ts
Labels: need review, :recycle: cleaning :recycle:, :eye: review ongoing :eye:, javascript

#1202 feat(mongo): truncate dates to compare only days for from/until operators TCTC-1322
  .eslintrc.js
  playground/datastore/november-2021-hours.json
  playground/init-mongo/01-import-files.sh
  playground/init-mongo/02-adjust-types.js
  server/playground.py
  src/components/DatePicker/Calendar.vue
  src/lib/translators/mongo.ts
  src/lib/translators/mongo5.ts
  tests/unit/calendar.spec.ts
  tests/unit/mongo.spec.ts
Labels: mongo

#1206 fix(relative-date): simplify label for relative date removing suffix and separator
  src/lib/dates.ts
  tests/unit/date-range-input.spec.ts
  tests/unit/labeller.spec.ts
  tests/unit/lib/dates.spec.ts
  tests/unit/new-date-input.spec.ts
Labels: javascript

#1207 feat(mongo): enable to use variable as base date for relative date filtering TCTC-1321
  src/components/stepforms/widgets/DateComponents/NewDateInput.vue
  src/lib/dates.ts
  src/lib/translators/mongo5.ts
  stories/dates/new-date-input.js
  tests/unit/mongo.spec.ts
  tests/unit/new-date-input.spec.ts
Labels: mongo, javascript

#1208 fix(new-date-input): add relative date secruity where missing TCTC-1321
  src/components/stepforms/widgets/DateComponents/NewDateInput.vue
Labels: need review, javascript
