Repository ToucanToco/weaverbird, pull requests merged in 2021-07, with the labels that each got.

#935 fix(formula): avoid Infinity in resulting dataframe
  server/tests/steps/test_formula.py
  server/weaverbird/formula.py
Labels: bug

#937 feat(aggregate steps): add unique column names validation
  server/tests/steps/test_aggregate.py
  server/weaverbird/steps/aggregate.py
Labels: bug

#938 release/0.53.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: need review

#941 doc: add backend release how to
  README.md
Labels: documentation

#944 fix(server): pandas step names case
  server/pyproject.toml
  server/weaverbird/backends/pandas_executor/steps/__init__.py
Labels: bug, need review, py pandas, release

#943 Doc add a section "howto add a new translator"
  docs/_docs/tech/python-package.md
Labels: documentation

#946 feat(to-date-step): implement "try to guess" with "%Y"
  CHANGELOG.md
  src/lib/translators/mongo4.ts
  tests/unit/mongo.spec.ts
Labels: mongo, need review

#947 v0.53.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#949 build: deactivate featurepeek
  .github/workflows/docker-playground.yml
  .github/workflows/storybook.yml
  peek.yml
Labels: build

#951 fix(pandas): evolution step now handles mixed indexes
  server/tests/steps/test_evolution.py
  server/weaverbird/backends/pandas_executor/steps/evolution.py
Labels: bug

#954 fix(pipeline): enable delete shortcut only when no other input is focused
  CHANGELOG.md
  src/components/Pipeline.vue
Labels: bug

#953 fix(search): display search correctly
  CHANGELOG.md
  src/components/ActionMenu.vue
  src/components/ActionToolbarSearch.vue
Labels: ui

#956 v0.53.1
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: need review

#957 doc(readme): better introduction
  README.md
  docs/img/readme_screenshot.png
Labels: documentation, need review

#959 chore(bump): upgrade to version 0.5.3
  server/pyproject.toml
Labels: need review

#961 doc: doc for sql translation
  docs/_data/docs.yml
  docs/_docs/tech/sql-pipeline.md
  docs/_docs/tech/sql-steps/aggregate.md
  docs/_docs/tech/sql-steps/filter.md
Labels: Tortank, documentation
