Repository ToucanToco/weaverbird, pull requests merged in 2021-04, with the labels that each got.

#864 feat(pipeline): update design to fit guidelines
  src/components/Step.vue
Labels: ui

#863 fix(conditions): display row corectly with long labels
  src/components/ConditionsEditor/ConditionsGroup.vue
Labels: bug, ui

#865 feat(back): no more None values in step.dict()
  server/tests/test_pipeline.py
  server/weaverbird/pipeline.py
  server/weaverbird/steps/base.py
Labels: py pandas

#866 feat(pipeline): display more readable errors
  src/components/Pipeline.vue
  src/components/Step.vue
  src/lib/backend.ts
  src/store/actions.ts
  src/store/getters.ts
  src/styles/_variables.scss
  tests/unit/step.spec.ts
  tests/unit/store.spec.ts
Labels: javascript

#867 v0.45.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#873 feat(back): no more None values in step.dict()
  server/tests/test_pipeline.py
  server/tests/test_pipeline_executor.py
  server/weaverbird/pipeline.py
  server/weaverbird/pipeline_executor.py
  server/weaverbird/steps/base.py
Labels: py pandas

#872 fix(variables): retrieve variable identifier from malformatted variables
  src/lib/variables.ts
  tests/unit/variables.spec.ts
Labels: bug, need review

#874 feat(pipeline executor): pilepineExecutor#execute now returns a detailed report
  server/pyproject.toml
  server/tests/test_pipeline_executor.py
  server/weaverbird/pipeline_executor.py
Labels: py pandas

#875 fix(filter-condition): update value when changing widget
  src/components/stepforms/widgets/FilterSimpleCondition.vue
  src/components/stepforms/widgets/InputDate.vue
  src/lib/helpers.ts
  tests/unit/filter-simple-condition-widget.spec.ts
  tests/unit/helpers.spec.ts
Labels: bug

#876 fix(input-date): enable to use variables
  src/components/stepforms/widgets/InputDate.vue
  src/lib/helpers.ts
  tests/unit/filter-simple-condition-widget.spec.ts
  tests/unit/helpers.spec.ts
  tests/unit/input-date-widget.spec.ts
Labels: bug

#877 v0.46.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#879 fix(date-step-form): always display custom input format when custom format is selected
  src/components/stepforms/FromDateStepForm.vue
  src/components/stepforms/ToDateStepForm.vue
  tests/unit/fromdate-step-form.spec.ts
  tests/unit/todate-step-form.spec.ts
Labels: bug, need review

#881 v0.46.1
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#878 pandas/waterfall: the column 'TYPE_waterfall' was wrong, leading to bad drilling
  server/tests/steps/test_waterfall.py
  server/weaverbird/steps/waterfall.py
Labels: py pandas

#883 fix(date-step-form): display custom format input with empty field
  src/components/stepforms/FromDateStepForm.vue
  src/components/stepforms/ToDateStepForm.vue
  tests/unit/fromdate-step-form.spec.ts
  tests/unit/todate-step-form.spec.ts
Labels: bug

#884 v0.46.2
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#885 feat(pipeline): delete multiple steps at once
  src/components/Pipeline.vue
  src/components/Step.vue
  src/store/actions.ts
  src/store/mutations.ts
  src/styles/_variables.scss
  tests/unit/pipeline.spec.ts
  tests/unit/step.spec.ts
  tests/unit/store.spec.ts
Labels: :eye: review ongoing :eye:, javascript

#886 feat(pipeline): enable to reorder steps using drag and drop
  .storybook/bundle.ts
  package.json
  src/components/Pipeline.vue
  src/components/Step.vue
  src/store/actions.ts
  src/styles/_variables.scss
  stories/filter-editor.js
  stories/step.js
  tests/unit/pipeline.spec.ts
  tests/unit/step.spec.ts
  tests/unit/store.spec.ts
  yarn.lock
Labels: javascript, need review

#890 fix(popover): put z-index: 2 to popover
  src/components/Popover.vue
Labels: bug

#891 v0.46.4
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#893 v0.47.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release
