Repository ToucanToco/weaverbird, pull requests merged in 2021-06, with the labels that each got.

#915 v0.49.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#917 test: add data-cy for filter value
  src/components/stepforms/widgets/FilterSimpleCondition.vue
Labels: tech

#918 chore(front): v0.49.1
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release, ui

#919 fix(variable chooser): always display date in UTC
  CHANGELOG.md
  src/components/stepforms/widgets/VariableInputs/VariableChooser.vue
  tests/unit/variable-chooser.spec.ts
Labels: bug

#920 fix(code-editor): move fixed height to container
  CHANGELOG.md
  src/components/stepforms/widgets/CodeEditorWidget.vue
Labels: bug, need review

#924 v0.49.2
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#922 feat(translators): add new empty translator
  CHANGELOG.md
  src/lib/translators/empty.ts
  src/lib/translators/index.ts
  tests/unit/translator.spec.ts
Labels: need review

#923 feat(translators): hide actions from interface if no steps are supported
  CHANGELOG.md
  src/components/ActionToolbar.vue
  src/components/DataViewer.vue
  src/components/Pipeline.vue
  src/store/getters.ts
  tests/unit/action-toolbar.spec.ts
  tests/unit/data-viewer.spec.ts
  tests/unit/pipeline.spec.ts
  tests/unit/store.spec.ts
Labels: javascript, need review

#925 v0.50.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#929 fix: prevent uint32 in date extract results
  server/tests/steps/test_date_extract.py
  server/weaverbird/steps/date_extract.py
Labels: bug

#930 fix(step): change drag & drop grip icon
  src/components/Step.vue
Labels: design

#928 feat(pipeline): handle cmd for copy/pasting + backspace key to delete
  src/components/Pipeline.vue
  tests/unit/pipeline.spec.ts
Labels: javascript, need review

#931 feat(action toolbar): new search integration
  src/components/ActionToolbar.vue
  src/components/ActionToolbarSearch.vue
  src/components/SearchBar.vue
  tests/unit/action-toolbar-search.spec.ts
  tests/unit/action-toolbar.spec.ts
  tests/unit/search-bar.spec.ts
Labels: design, ui

#932 docs(server): python package install and usage
  docs/_data/docs.yml
  docs/_docs/tech/index.md
  docs/_docs/tech/known_limitations.md
  docs/_docs/tech/packages.md
  docs/_docs/tech/python-package.md
  docs/about.html
  server/README.md
Labels: documentation, py pandas
