Repository ToucanToco/weaverbird, pull requests merged in 2021-05, with the labels that each got.

#895 feat(front): customize popover container
  .storybook/bundle.ts
  src/components/ActionMenu.vue
  src/components/DataViewer.vue
  src/components/Popover.vue
  stories/popover.js
Labels: javascript, tech

#904 v0.47.1
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: need review, release

#905 feat(FilterEditor): make variables hiddable for column
  src/components/FilterEditor.vue
  src/components/stepforms/widgets/FilterSimpleCondition.vue
  tests/unit/filter-simple-condition-widget.spec.ts
Labels: enhancement, need review

#906 feat(pipeline): copy/paste steps with clipboard
  src/components/Pipeline.vue
  src/lib/clipboard.ts
  src/lib/steps.ts
  src/store/actions.ts
  src/store/mutations.ts
  tests/unit/lib/clipboard.spec.ts
  tests/unit/pipeline.spec.ts
  tests/unit/store.spec.ts
Labels: javascript

#908 v0.48.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#909 fix(filter-condition): enable to have undefined value
  src/components/stepforms/schemas/filter.ts
  src/components/stepforms/schemas/ifthenelse.ts
Labels: bug, need review

#910 v0.48.1
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: need review, release

#896 chore: add data cy for story create e2e tests
  src/components/ActionToolbarButton.vue
  src/components/DataViewer.vue
  src/components/DataViewerCell.vue
  src/components/Popover.vue
  src/components/QueryBuilder.vue
  src/components/Step.vue
  src/components/stepforms/FilterStepForm.vue
  src/components/stepforms/StepFormButtonbar.vue
  src/components/stepforms/widgets/Autocomplete.vue
  src/components/stepforms/widgets/FilterSimpleCondition.vue
  src/components/stepforms/widgets/InputText.vue
  src/components/stepforms/widgets/JoinColumns.vue
Labels: need review, tech
