Repository ToucanToco/weaverbird, pull requests merged in 2021-10, with the labels that each got.

#1093 chore(dates): export date range and new input date components
  src/main.ts
Labels: tech

#1094 v0.61.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#1095 feat(front): make date-range input fixed/relative tabs hideable
  src/components/stepforms/widgets/DateComponents/CustomVariableList.vue
  src/components/stepforms/widgets/DateComponents/DateRangeInput.vue
  stories/dates/date-range-input.js
  tests/unit/custom-variable-list.spec.ts
  tests/unit/date-range-input.spec.ts
Labels: need review, javascript

#1096 v0.62.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#1098 feat(widgets): month picker
  .storybook/bundle.ts
  package.json
  src/assets/FA-ICONS.ts
  src/components/DatePicker/Calendar.vue
  src/components/DatePicker/MonthCalendar.vue
  src/components/DatePicker/RangeCalendar.vue
  src/components/stepforms/widgets/DateComponents/DateRangeInput.vue
  src/components/stepforms/widgets/DateComponents/NewDateInput.vue
  src/lib/dates.ts
  stories/dates/calendar.js
  stories/dates/month-calendar.js
  stories/dates/range-calendar.js
  tests/unit/calendar.spec.ts
  tests/unit/month-calendar.spec.ts
  tests/unit/range-calendar.spec.ts
  yarn.lock
Labels: enhancement, need review, ui

#1101 feat(date-range-input): replace range-calendar with unique calendar using a range
  src/components/stepforms/widgets/DateComponents/DateRangeInput.vue
  tests/unit/date-range-input.spec.ts
Labels: need review, javascript
