Repository ToucanToco/weaverbird, pull requests merged in 2021-03, with the labels that each got.

#836 filter on a date column now allows to use a date input.
  server/weaverbird/conditions.py
  src/components/ConditionsEditor/ConditionsGroup.vue
  src/components/FilterEditor.vue
  src/components/stepforms/convert-filter-step-tree.ts
  src/components/stepforms/schemas/filter.ts
  src/components/stepforms/widgets/FilterSimpleCondition.vue
  src/components/stepforms/widgets/InputDate.vue
  src/lib/helpers.ts
  src/store/state.ts
  tests/unit/filter-simple-condition-widget.spec.ts
  tests/unit/helpers.spec.ts
  tests/unit/input-date-widget.spec.ts
Labels: enhancement, need review

#847 v0.42.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#851 v0.42.2
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#855 chore(front): v0.43.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#856 feat(pandas): add no joins translator
  CHANGELOG.md
  src/components/stepforms/FromDateStepForm.vue
  src/components/stepforms/ToDateStepForm.vue
  src/lib/translators/index.ts
  src/lib/translators/pandas-no_joins.ts
  tests/unit/translator.spec.ts
Labels: need review

#852 feat(dateextract step): Add new date information to be extracted + extract several info in just one step
  CHANGELOG.md
  docs/_docs/tech/steps.md
  docs/_docs/user-interface/dateextract.md
  docs/img/docs/user-interface/dateextract_example_conf.jpg
  docs/img/docs/user-interface/dateextract_example_result.jpg
  docs/img/docs/user-interface/dateextract_menu_example.jpg
  docs/img/docs/user-interface/dateextract_step_form.jpg
  server/tests/steps/test_date_extract.py
  server/weaverbird/steps/date_extract.py
  src/components/ActionToolbarButton.vue
  src/components/constants.ts
  src/components/stepforms/DateExtractStepForm.vue
  src/components/stepforms/schemas/dateextract.ts
  src/lib/labeller.ts
  src/lib/steps.ts
  src/lib/templating.ts
  src/lib/translators/base.ts
  src/lib/translators/mongo.ts
  src/lib/translators/pandas-no_joins.ts
  src/lib/translators/pandas.ts
  tests/unit/action-toolbar-button.spec.ts
  tests/unit/dateextract-step-form.spec.ts
  tests/unit/labeller.spec.ts
  tests/unit/mongo.spec.ts
  tests/unit/templating.spec.ts
Labels: :eye: review ongoing :eye:, enhancement

#857 v0.44.0
  CHANGELOG.md
  package.json
  server/pyproject.toml
  sonar-project.properties
Labels: need review, release
