Repository ToucanToco/weaverbird, pull requests merged in 2021-02, with the labels that each got.

#827 Backport v0.36.1
  CHANGELOG.md
  src/components/stepforms/FromDateStepForm.vue
Labels: backport, bug

#828 feat(front): add text and center loading spinner
  src/components/DataViewer.vue
  stories/data-viewer.js
  tests/unit/data-viewer.spec.ts
Labels: enhancement, javascript, need review

#830 chore(front): v0.38.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#835 v0.39.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#839 feat(front): order of combinable tables in selector
  CHANGELOG.md
  src/store/getters.ts
  tests/unit/store.spec.ts
Labels: javascript

#841 chore(front): v0.40.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#842 fix(to date step): enable to transform a year string to a date
  src/components/stepforms/ToDateStepForm.vue
  src/lib/translators/mongo4.ts
  tests/unit/mongo.spec.ts
Labels: bug, need review

#844 v0.41.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#845 feat(domain step): change label
  CHANGELOG.md
  src/lib/labeller.ts
  tests/unit/labeller.spec.ts
  tests/unit/step.spec.ts
Labels: need review, ui
