Repository ToucanToco/weaverbird, pull requests merged in 2021-12, with the labels that each got.

#1211 feat(backend service): configurable "preview source" rows subset TCTC-1324
  CHANGELOG.md
  src/components/Pipeline.vue
  src/components/PreviewSourceSubset.vue
  src/lib/backend.ts
  src/lib/dataset/index.ts
  src/store/actions.ts
  src/store/getters.ts
  src/store/mutations.ts
Labels: need review, ui

#1205 feat(playground): add buttons to select a backend
  playground/app.js
  playground/dist/index.html
Labels: playground

#1210 fix(ui): component InputNumber return value as number
  src/components/stepforms/StatisticsStepForm.vue
  src/components/stepforms/widgets/InputNumber.vue
  tests/unit/input-number-widget.spec.ts
  tests/unit/statistics-step-form.spec.ts
Labels: bug, need review, javascript

#1212 feat(new-date-input): send analytics event when user select a (advanced or base) variable TCTC-899
  playground/app.js
  src/components/stepforms/widgets/DateComponents/NewDateInput.vue
  src/lib/send-analytics.ts
  src/main.ts
  tests/unit/lib/send-analytics.spec.ts
  tests/unit/new-date-input.spec.ts
Labels: javascript

#1209 fix(add-total-steps-rows): avoid to submit form before set aggregations new columns is over TCTC-1300
  src/components/stepforms/AddTotalRowsStepForm.vue
  tests/unit/utils.ts
Labels: bug, javascript

#1215 v0.77.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: ui, release

#1217 chore(server): v0.9.0
  server/setup.cfg
Labels: need review, py pandas, release, sql

#1219 feat(new-date-input): add analytics when saving a relative date TCTC-899
  src/components/stepforms/widgets/DateComponents/NewDateInput.vue
  tests/unit/new-date-input.spec.ts
Labels: need review, javascript

#1220 v0.78.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: need review, release

#1218 fix(mongo): always truncate time to day in date extract step TCTC-1283
  src/lib/steps.ts
  src/lib/translators/mongo-dates.ts
  src/lib/translators/mongo.ts
  src/lib/translators/mongo5.ts
  tests/unit/mongo.spec.ts
Labels: mongo, :eye: review ongoing :eye:, fix

#1222 fix(sql): align SnowFlake date extract results with other backends TCTC-1283
  server/src/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
  server/tests/backends/fixtures/dateextract/snowflake_all_cases.json
  server/tests/steps/sql_translator/test_dateextract.py
  server/tests/utils.py
Labels: need review, fix, sql

#1225 v0.78.1
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: mongo, release

#1227 fix(pandas): some dateextract were failing if some dates were duplicated TCTC-1379
  server/src/weaverbird/backends/pandas_executor/steps/addmissingdates.py
  server/src/weaverbird/backends/pandas_executor/steps/date_extract.py
  server/tests/steps/test_addmissingdates.py
Labels: bug, need review, py pandas

#1228 feat(configurable-subset-preview): use correct design TCTC-1339
  src/assets/FA-ICONS.ts
  src/components/Pipeline.vue
  src/components/PreviewSourceSubset.vue
  src/components/Step.vue
  stories/step.js
  tests/unit/step.spec.ts
Labels: need review, design, javascript

#1231 v0.79.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: need review, release

#1229 chore: export date range to string method TCTC-1398
  src/main.ts
Labels: need review, javascript

#1232 v0.79.1
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#1233 fix(preview source subset): stop click propagation TCTC-1419
  src/components/PreviewSourceSubset.vue
Labels: need review, ui, javascript

#1234 v0.79.2
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: ui, release

#1235 feat(filter-step): rename label for from/until date operators TCTC-1443
  src/components/stepforms/widgets/FilterSimpleCondition.vue
  src/lib/labeller.ts
  tests/unit/labeller.spec.ts
Labels: javascript

#1236 fix(preview-source-subset): use correct icon and label TCTC-1339
  src/assets/FA-ICONS.ts
  src/components/PreviewSourceSubset.vue
  src/components/Step.vue
Labels: bug, need review, javascript

#1237 v0.79.3
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#1238 fix(stepforms): change placeholders color [TCTC-1380]
  src/components/stepforms/widgets/InputText.vue
  src/components/stepforms/widgets/Multiselect.vue
  src/components/stepforms/widgets/TotalDimensions.vue
Labels: need review, ui

#1239 chore(version): 0.79.4
  CHANGELOG.md
  package.json
  sonar-project.properties
  src/components/stepforms/widgets/TotalDimensions.vue
Labels: need review

#1240 feat: enable postgres/redshift connector
  server/src/weaverbird/backends/sql_translator/sql_pipeline_translator.py
  server/src/weaverbird/backends/sql_translator/steps/aggregate.py
  server/src/weaverbird/backends/sql_translator/steps/append.py
  server/src/weaverbird/backends/sql_translator/steps/argmax.py
  server/src/weaverbird/backends/sql_translator/steps/argmin.py
  server/src/weaverbird/backends/sql_translator/steps/concatenate.py
  server/src/weaverbird/backends/sql_translator/steps/convert.py
  server/src/weaverbird/backends/sql_translator/steps/cumsum.py
  server/src/weaverbird/backends/sql_translator/steps/customsql.py
  server/src/weaverbird/backends/sql_translator/steps/dateextract.py
  server/src/weaverbird/backends/sql_translator/steps/delete.py
  server/src/weaverbird/backends/sql_translator/steps/duplicate.py
  server/src/weaverbird/backends/sql_translator/steps/duration.py
  server/src/weaverbird/backends/sql_translator/steps/evolution.py
  server/src/weaverbird/backends/sql_translator/steps/fillna.py
  server/src/weaverbird/backends/sql_translator/steps/filter.py
  server/src/weaverbird/backends/sql_translator/steps/formula.py
  server/src/weaverbird/backends/sql_translator/steps/fromdate.py
  server/src/weaverbird/backends/sql_translator/steps/ifthenelse.py
  server/src/weaverbird/backends/sql_translator/steps/join.py
  server/src/weaverbird/backends/sql_translator/steps/lowercase.py
  server/src/weaverbird/backends/sql_translator/steps/percentage.py
  server/src/weaverbird/backends/sql_translator/steps/pivot.py
  server/src/weaverbird/backends/sql_translator/steps/rank.py
  server/src/weaverbird/backends/sql_translator/steps/rename.py
  server/src/weaverbird/backends/sql_translator/steps/replace.py
  server/src/weaverbird/backends/sql_translator/steps/rollup.py
  server/src/weaverbird/backends/sql_translator/steps/select.py
  server/src/weaverbird/backends/sql_translator/steps/sort.py
  server/src/weaverbird/backends/sql_translator/steps/split.py
  server/src/weaverbird/backends/sql_translator/steps/substring.py
  server/src/weaverbird/backends/sql_translator/steps/table.py
  server/src/weaverbird/backends/sql_translator/steps/text.py
  server/src/weaverbird/backends/sql_translator/steps/todate.py
  server/src/weaverbird/backends/sql_translator/steps/top.py
  server/src/weaverbird/backends/sql_translator/steps/totals.py
  server/src/weaverbird/backends/sql_translator/steps/uniquegroups.py
  server/src/weaverbird/backends/sql_translator/steps/unpivot.py
  server/src/weaverbird/backends/sql_translator/steps/uppercase.py
  server/src/weaverbird/backends/sql_translator/types.py
Labels: need review

#1241 chore(version): bump weaverbird 0.10.2
  server/CHANGELOG.md
  server/setup.cfg
Labels: need review
