Repository ToucanToco/weaverbird, pull requests merged in 2021-01, with the labels that each got.

#807 fix(if then else widget): remove z-index context on dropdowns
  src/components/stepforms/widgets/IfThenElseWidget.vue
Labels: need review

#811 fix(getters): bound active step index to pipeline size
  CHANGELOG.md
  src/store/getters.ts
  tests/unit/statistics-step-form.spec.ts
  tests/unit/store.spec.ts
Labels: bug, need review

#812 v0.35.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: need review, release

#816 fix(server): some retrocompatibility fixes
  server/pyproject.toml
  server/tests/steps/test_fillna.py
  server/tests/steps/test_rename.py
  server/tests/steps/test_totals.py
  server/tests/test_utils.py
  server/weaverbird/conditions.py
  server/weaverbird/steps/fillna.py
  server/weaverbird/steps/ifthenelse.py
  server/weaverbird/steps/join.py
  server/weaverbird/steps/rename.py
  server/weaverbird/steps/totals.py
  server/weaverbird/utils/__init__.py
  server/weaverbird/utils/cleaning.py
Labels: bug

#818 fix(mongo): "not in" (`nin`) in if/then/else conditions
  CHANGELOG.md
  src/lib/translators/mongo.ts
  tests/unit/mongo.spec.ts
Labels: bug, mongo

#819 v0.35.1
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#817 fix(server): fix util rename_duplicated_columns
  .github/workflows/ci-server.yml
  server/pyproject.toml
  server/tests/test_utils.py
  server/weaverbird/utils/cleaning.py
Labels: bug

#820 feat(convert step): support cast from string to integer and vice versa
  CHANGELOG.md
  src/components/DataTypesMenu.vue
  src/components/stepforms/ToDateStepForm.vue
  src/lib/translators/mongo4.ts
  tests/unit/data-types-menu.spec.ts
  tests/unit/mongo.spec.ts
  tests/unit/todate-step-form.spec.ts
Labels: querytranslate

#821 v0.36.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#824 v0.37.0
  CHANGELOG.md
  package.json
  server/pyproject.toml
  sonar-project.properties
Labels: release

#825 Fix movingaverage
  server/pyproject.toml
  server/weaverbird/steps/moving_average.py
Labels: bug
