Repository ToucanToco/weaverbird, pull requests merged in 2021-08, with the labels that each got.

#966 feat(resizable): adapt col width to fit max char per col option
  src/components/DataViewer.vue
  src/directives/resizable/ResizableTable.ts
  tests/unit/resizable.spec.ts
Labels: need review, javascript

#967 v0.54.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#973 feat(vqb-step): added sort translator step
  server/tests/steps/sql_translator/test_sort.py
  server/weaverbird/backends/sql_translator/steps/__init__.py
  server/weaverbird/backends/sql_translator/steps/sort.py
Labels: need review

#974 chore(bump): new version from 0.5.6 to 0.5.7
  server/pyproject.toml
Labels: need review

#972 feat(tabs): add new tabs component
  .storybook/bundle.ts
  src/components/Tabs.vue
  stories/tabs.js
  tests/unit/tabs.spec.ts
Labels: javascript

#976 feat(calendar): add a new calendar component
  .storybook/bundle.ts
  package.json
  src/components/Calendar.vue
  src/lib/dates.ts
  stories/calendar.js
  tests/unit/calendar.spec.ts
  yarn.lock
Labels: need review, javascript

#978 fix(tabs): fix sonar empty props issue
  tests/unit/tabs.spec.ts
Labels: bug

#979 fix(vqb-step): fix rename/sort step [KeyError - table1]
  server/tests/steps/sql_translator/test_rename.py
  server/tests/steps/sql_translator/test_sort.py
  server/weaverbird/backends/sql_translator/steps/rename.py
  server/weaverbird/backends/sql_translator/steps/sort.py
Labels: need review

#977 feat(range-calendar): add a new range calendar component
  .storybook/bundle.ts
  src/components/Calendar.vue
  src/components/RangeCalendar.vue
  src/lib/dates.ts
  stories/calendar.js
  stories/range-calendar.js
  tests/unit/calendar.spec.ts
  tests/unit/range-calendar.spec.ts
Labels: javascript

#981 feat(vqb-step): added convert (CAST) translator step
  server/tests/steps/sql_translator/test_convert.py
  server/weaverbird/backends/sql_translator/steps/__init__.py
  server/weaverbird/backends/sql_translator/steps/convert.py
Labels: need review

#983 chore(esjson): remove all occurencies to esjson
  src/components/FilterEditor.vue
  src/components/stepforms/convert-filter-step-tree.ts
  src/components/stepforms/widgets/FilterSimpleCondition.vue
  src/lib/helpers.ts
  tests/unit/filter-simple-condition-widget.spec.ts
  tests/unit/helpers.spec.ts
Labels: :recycle: cleaning :recycle:, javascript

#975 feat(vqb-step): added if-then-else translator step
  server/tests/steps/sql_translator/test_ifthenelse.py
  server/weaverbird/backends/sql_translator/steps/__init__.py
  server/weaverbird/backends/sql_translator/steps/ifthenelse.py
Labels: need review

#984 v0.55.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#991 chore(bump): from version 0.6.1 to 0.6.2
  server/tests/steps/sql_translator/test_ifthenelse.py
  server/weaverbird/backends/sql_translator/steps/ifthenelse.py
  server/weaverbird/backends/sql_translator/steps/sort.py
  server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
Labels: need review, Tortank

#995 chore(bump): from version 0.6.2 to 0.6.3
  server/pyproject.toml
Labels: Tortank

#996 feat: update metadata storage and usage in steps
  server/pyproject.toml
  server/tests/steps/sql_translator/conftest.py
  server/tests/steps/sql_translator/test_aggregate.py
  server/tests/steps/sql_translator/test_convert.py
  server/tests/steps/sql_translator/test_filter.py
  server/tests/steps/sql_translator/test_ifthenelse.py
  server/tests/steps/sql_translator/test_lowercase.py
  server/tests/steps/sql_translator/test_rename.py
  server/tests/steps/sql_translator/test_select.py
  server/tests/steps/sql_translator/test_sort.py
  server/tests/steps/sql_translator/test_text.py
  server/tests/steps/sql_translator/test_uppercase.py
  server/tests/steps/sql_translator/utils/test_query_transformation.py
  server/tests/test_pipeline_translator.py
  server/weaverbird/backends/sql_translator/steps/aggregate.py
  server/weaverbird/backends/sql_translator/steps/convert.py
  server/weaverbird/backends/sql_translator/steps/filter.py
  server/weaverbird/backends/sql_translator/steps/ifthenelse.py
  server/weaverbird/backends/sql_translator/steps/lowercase.py
  server/weaverbird/backends/sql_translator/steps/rename.py
  server/weaverbird/backends/sql_translator/steps/select.py
  server/weaverbird/backends/sql_translator/steps/sort.py
  server/weaverbird/backends/sql_translator/steps/table.py
  server/weaverbird/backends/sql_translator/steps/text.py
  server/weaverbird/backends/sql_translator/steps/uppercase.py
  server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
  server/weaverbird/backends/sql_translator/types.py
Labels: Tortank

#997 feat(vqb): added step replace + unit tests
  server/tests/steps/sql_translator/test_lowercase.py
  server/tests/steps/sql_translator/test_replace.py
  server/weaverbird/backends/sql_translator/steps/__init__.py
  server/weaverbird/backends/sql_translator/steps/replace.py
Labels: need review, Tortank

#998 feat: add formula step
  server/pyproject.toml
  server/setup.cfg
  server/tests/steps/sql_translator/test_formula.py
  server/tests/steps/sql_translator/utils/test_query_transformation.py
  server/weaverbird/backends/sql_translator/steps/__init__.py
  server/weaverbird/backends/sql_translator/steps/formula.py
  server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
Labels: Tortank

#1001 fix(vqb): remove unecesary code from convert step
  server/weaverbird/backends/sql_translator/steps/convert.py
Labels: need review, Tortank

#1000 feat(vqb): added step text to date + unit tests
  server/tests/steps/sql_translator/test_todate.py
  server/tests/steps/sql_translator/utils/test_query_transformation.py
  server/weaverbird/backends/sql_translator/steps/__init__.py
  server/weaverbird/backends/sql_translator/steps/todate.py
  server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
Labels: need review, Tortank

#1005 ci: use only snowflake password from en variables
  .github/workflows/ci-server.yml
  server/README.md
  server/tests/backends/sql_translator/test_snowflake_translator_steps.py
Labels: Tortank

#1006 fix: fix white space in agg column names
  server/pyproject.toml
  server/tests/steps/sql_translator/test_aggregate.py
  server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
Labels: bug, Tortank

#988 feat(relative-date-form): add new component
  .storybook/bundle.ts
  src/components/stepforms/widgets/DateComponents/RelativeDateForm.vue
  src/lib/dates.ts
  stories/dates/relative-date-form.js
  tests/unit/relative-date-form-widget.spec.ts
Labels: need review, javascript

#994 feat(relative-date-range-form): add new component
  .storybook/bundle.ts
  src/components/stepforms/widgets/DateComponents/RelativeDateForm.vue
  src/components/stepforms/widgets/DateComponents/RelativeDateRangeForm.vue
  src/lib/dates.ts
  stories/dates/relative-date-form.js
  stories/dates/relative-date-range-form.js
  tests/unit/relative-date-form-widget.spec.ts
  tests/unit/relative-date-range-form-widget.spec.ts
Labels: need review, javascript

#1003 feat(vqb): added step date to text + unit tests
  server/tests/steps/sql_translator/test_fromdate.py
  server/weaverbird/backends/sql_translator/steps/__init__.py
  server/weaverbird/backends/sql_translator/steps/fromdate.py
Labels: need review, Tortank

#1002 feat(new-date-input): add a new component to select a date
  .storybook/bundle.ts
  src/components/Tabs.vue
  src/components/stepforms/widgets/DateComponents/NewDateInput.vue
  src/lib/dates.ts
  stories/dates/new-date-input.js
  tests/unit/lib/dates.spec.ts
  tests/unit/new-date-input.spec.ts
Labels: need review, javascript

#1010 build(ui): create github action workflow and remove circle
  .circleci/config.yml
  .github/workflows/ci-ui.yml
  README.md
Labels: build

#1015 chore: register snowflake translator & available steps
  src/lib/translators/index.ts
  src/lib/translators/snowflake.ts
  tests/unit/translator.spec.ts
Labels: Tortank

#1018 build(sonar): fix sonar analysis
  .github/workflows/ci-ui.yml
  jest.config.js
  package.json
  sonar-project.properties
  yarn.lock
Labels: need review, build

#1019 chore: bump v.0.56.0
  CHANGELOG.md
  package.json
Labels: need review

#1014 feat(vqb): TOP-N rows step
  server/tests/backends/fixtures_sql/top/top.json
  server/tests/backends/sql_translator/test_sql_translator_steps.py
  server/tests/steps/sql_translator/test_top.py
  server/weaverbird/backends/sql_translator/steps/__init__.py
  server/weaverbird/backends/sql_translator/steps/top.py
  server/weaverbird/backends/sql_translator/types.py
Labels: need review, Tortank

#1023 chore(bump): from version 1.0.0.a1 to 1.0.0.a2
  server/pyproject.toml
Labels: need review, Tortank

#1026 build(server): v0.7.0
  server/pyproject.toml
Labels: release

#1039 feat(vqb): added percentage step on snowflake translator
  src/lib/translators/snowflake.ts
Labels: need review, Tortank

#1042 feat(vqb): added percentage step
  server/pyproject.toml
  server/tests/backends/fixtures/percentage/simple.json
  server/tests/steps/sql_translator/test_percentage.py
  server/weaverbird/backends/sql_translator/steps/__init__.py
  server/weaverbird/backends/sql_translator/steps/percentage.py
Labels: need review, Tortank

#1043 Release/0.59.0
  CHANGELOG.md
  package.json
Labels: need review, Tortank

#1038 feat(sql pivot): add pivot step & unit tests
  CHANGELOG.md
  docs/_docs/user-interface/pivot.md
  package.json
  server/pyproject.toml
  server/tests/backends/fixtures/pivot/simple.json
  server/tests/fixtures/fixtures_templating/pivot.json
  server/tests/steps/sql_translator/test_pivot.py
  server/tests/steps/test_pivot.py
  server/weaverbird/backends/sql_translator/metadata.py
  server/weaverbird/backends/sql_translator/steps/__init__.py
  server/weaverbird/backends/sql_translator/steps/pivot.py
  server/weaverbird/pipeline/steps/pivot.py
  sonar-project.properties
  src/components/stepforms/PivotStepForm.vue
  src/components/stepforms/schemas/pivot.ts
  src/lib/steps.ts
  tests/unit/labeller.spec.ts
  tests/unit/mongo.spec.ts
  tests/unit/pivot-step-form.spec.ts
  tests/unit/templating.spec.ts
Labels: help wanted, need review, Tortank
