Repository ToucanToco/weaverbird, pull requests merged in 2021-09, with the labels that each got.

#1037 refactor(popover): prefix css class to avoid collision
  CHANGELOG.md
  src/components/Popover.vue
  tests/unit/action-menu.spec.ts
  tests/unit/data-types-menu.spec.ts
Labels: ui

#1046 v0.60.1
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#1044 feat(vqb): added step date extract
  server/tests/backends/fixtures/dateextract/snowflake_all_cases.json
  server/tests/steps/sql_translator/test_dateextract.py
  server/weaverbird/backends/sql_translator/steps/__init__.py
  server/weaverbird/backends/sql_translator/steps/dateextract.py
  server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
  src/lib/translators/snowflake.ts
Labels: need review, Tortank

#1045 fix(sql unpivot, pivot): fix many issues
  CHANGELOG.md
  package.json
  server/pyproject.toml
  server/tests/backends/fixtures/pivot/simple.json
  server/tests/backends/sql_translator/test_snowflake_translator_steps.py
  server/tests/fixtures/fixtures_templating/pivot.json
  server/tests/steps/sql_translator/conftest.py
  server/tests/steps/sql_translator/test_aggregate.py
  server/tests/steps/sql_translator/test_join.py
  server/tests/steps/sql_translator/test_pivot.py
  server/tests/steps/sql_translator/test_table.py
  server/tests/steps/test_pivot.py
  server/tests/test_pipeline_translator.py
  server/weaverbird/backends/sql_translator/sql_pipeline_translator.py
  server/weaverbird/backends/sql_translator/steps/aggregate.py
  server/weaverbird/backends/sql_translator/steps/convert.py
  server/weaverbird/backends/sql_translator/steps/dateextract.py
  server/weaverbird/backends/sql_translator/steps/filter.py
  server/weaverbird/backends/sql_translator/steps/formula.py
  server/weaverbird/backends/sql_translator/steps/fromdate.py
  server/weaverbird/backends/sql_translator/steps/ifthenelse.py
  server/weaverbird/backends/sql_translator/steps/join.py
  server/weaverbird/backends/sql_translator/steps/lowercase.py
  server/weaverbird/backends/sql_translator/steps/percentage.py
  server/weaverbird/backends/sql_translator/steps/pivot.py
  server/weaverbird/backends/sql_translator/steps/rename.py
  server/weaverbird/backends/sql_translator/steps/replace.py
  server/weaverbird/backends/sql_translator/steps/select.py
  server/weaverbird/backends/sql_translator/steps/sort.py
  server/weaverbird/backends/sql_translator/steps/table.py
  server/weaverbird/backends/sql_translator/steps/text.py
  server/weaverbird/backends/sql_translator/steps/todate.py
  server/weaverbird/backends/sql_translator/steps/top.py
  server/weaverbird/backends/sql_translator/steps/uniquegroups.py
  server/weaverbird/backends/sql_translator/steps/unpivot.py
  server/weaverbird/backends/sql_translator/steps/uppercase.py
  server/weaverbird/backends/sql_translator/steps/utils/combination.py
  server/weaverbird/backends/sql_translator/types.py
  server/weaverbird/pipeline/steps/pivot.py
  sonar-project.properties
  src/components/stepforms/PivotStepForm.vue
  src/components/stepforms/UnpivotStepForm.vue
  src/components/stepforms/schemas/pivot.ts
  src/lib/steps.ts
  tests/unit/labeller.spec.ts
  tests/unit/mongo.spec.ts
  tests/unit/pivot-step-form.spec.ts
  tests/unit/templating.spec.ts
Labels: Tortank, fix

#1049 fix(join): fix join step
  server/weaverbird/backends/sql_translator/steps/join.py
Labels: need review, Tortank, fix

#1041 feat: sql append step
  server/tests/backends/fixtures/append/simple.json
  server/tests/backends/fixtures/append/with_domain_name.json
  server/tests/backends/sql_translator/test_metadata.py
  server/tests/backends/sql_translator/test_snowflake_translator_steps.py
  server/tests/steps/sql_translator/test_append.py
  server/tests/steps/sql_translator/test_join.py
  server/tests/steps/sql_translator/utils/test_query_transformation.py
  server/weaverbird/backends/sql_translator/metadata.py
  server/weaverbird/backends/sql_translator/sql_pipeline_translator.py
  server/weaverbird/backends/sql_translator/steps/__init__.py
  server/weaverbird/backends/sql_translator/steps/aggregate.py
  server/weaverbird/backends/sql_translator/steps/append.py
  server/weaverbird/backends/sql_translator/steps/concatenate.py
  server/weaverbird/backends/sql_translator/steps/convert.py
  server/weaverbird/backends/sql_translator/steps/dateextract.py
  server/weaverbird/backends/sql_translator/steps/filter.py
  server/weaverbird/backends/sql_translator/steps/formula.py
  server/weaverbird/backends/sql_translator/steps/fromdate.py
  server/weaverbird/backends/sql_translator/steps/ifthenelse.py
  server/weaverbird/backends/sql_translator/steps/join.py
  server/weaverbird/backends/sql_translator/steps/lowercase.py
  server/weaverbird/backends/sql_translator/steps/percentage.py
  server/weaverbird/backends/sql_translator/steps/pivot.py
  server/weaverbird/backends/sql_translator/steps/rename.py
  server/weaverbird/backends/sql_translator/steps/replace.py
  server/weaverbird/backends/sql_translator/steps/select.py
  server/weaverbird/backends/sql_translator/steps/sort.py
  server/weaverbird/backends/sql_translator/steps/table.py
  server/weaverbird/backends/sql_translator/steps/text.py
  server/weaverbird/backends/sql_translator/steps/todate.py
  server/weaverbird/backends/sql_translator/steps/top.py
  server/weaverbird/backends/sql_translator/steps/uniquegroups.py
  server/weaverbird/backends/sql_translator/steps/unpivot.py
  server/weaverbird/backends/sql_translator/steps/uppercase.py
  server/weaverbird/backends/sql_translator/steps/utils/combination.py
  server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
  server/weaverbird/backends/sql_translator/types.py
Labels: need review, Tortank

#1051 chore(backend version): 0.7.5
  server/pyproject.toml
Labels: need review, Tortank

#1052 chore(front version): 0.60.3
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: Tortank

#1054 fix(sql append): use union all in append step
  server/tests/backends/fixtures/append/simple.json
  server/tests/steps/sql_translator/test_append.py
  server/tests/steps/sql_translator/utils/test_query_transformation.py
  server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
Labels: bug, need review, Tortank

#1053 fix(vqb): top-n-rows
  server/tests/steps/sql_translator/test_top.py
  server/weaverbird/backends/sql_translator/steps/top.py
Labels: bug, need review

#1055 chore(backend version): bump to 0.7.6
  server/pyproject.toml
Labels: Tortank

#1056 feat(sql vqb): delete step
  CHANGELOG.md
  package.json
  server/pyproject.toml
  server/tests/steps/sql_translator/test_delete.py
  server/weaverbird/backends/sql_translator/steps/__init__.py
  server/weaverbird/backends/sql_translator/steps/delete.py
  sonar-project.properties
  src/lib/translators/snowflake.ts
Labels: need review, Tortank

#1057 feat(vqb): added rank step
  server/tests/backends/fixtures/rank/pandas.json
  server/tests/backends/fixtures/rank/snowflake.json
  server/tests/steps/sql_translator/test_rank.py
  server/weaverbird/backends/sql_translator/steps/__init__.py
  server/weaverbird/backends/sql_translator/steps/rank.py
  src/lib/translators/snowflake.ts
Labels: need review, Tortank

#1058 feat(vqb): added substring step
  server/tests/backends/fixtures/substring/simple.json
  server/tests/steps/sql_translator/test_substring.py
  server/weaverbird/backends/sql_translator/steps/__init__.py
  server/weaverbird/backends/sql_translator/steps/substring.py
  src/lib/translators/snowflake.ts
Labels: need review, Tortank

#1059 feat(vqb): added split step to snowflake
  server/tests/backends/fixtures/split/simple.json
  server/tests/steps/sql_translator/test_split.py
  server/weaverbird/backends/sql_translator/steps/__init__.py
  server/weaverbird/backends/sql_translator/steps/split.py
  src/lib/translators/snowflake.ts
Labels: :hammer: wip :hammer:, Tortank

#1060 feat(sql vqb): add fillna step
  server/tests/backends/fixtures/fillna/date.json
  server/tests/backends/fixtures/fillna/fillinteger.json
  server/tests/backends/fixtures/fillna/simple.json
  server/tests/steps/sql_translator/test_fillna.py
  server/tests/steps/sql_translator/utils/test_query_transformation.py
  server/weaverbird/backends/sql_translator/steps/__init__.py
  server/weaverbird/backends/sql_translator/steps/fillna.py
  server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
  src/lib/translators/snowflake.ts
Labels: need review, Tortank

#1061 chore(bump): back 0.7.7->0.7.8, front 0.60.4->0.60.5
  CHANGELOG.md
  package.json
  server/pyproject.toml
  sonar-project.properties
Labels: release

#1065 fix(sql vqb): fix sql vqb rank step + unit tests
  server/tests/backends/fixtures/rank/pandas.json
  server/tests/backends/fixtures/rank/snowflake.json
  server/tests/steps/sql_translator/test_rank.py
  server/weaverbird/backends/sql_translator/steps/aggregate.py
  server/weaverbird/backends/sql_translator/steps/rank.py
  server/weaverbird/backends/sql_translator/steps/top.py
  server/weaverbird/backends/sql_translator/steps/utils/aggregation.py
  server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
Labels: Tortank, fix

#1066 fix(dates): use default toString
  CHANGELOG.md
  src/components/DataViewerCell.vue
  src/components/stepforms/widgets/VariableInputs/VariableListOption.vue
  tests/unit/data-viewer-cell.spec.ts
  tests/unit/variable-list-option.spec.ts
Labels: fix

#1063 feat(sql custom): sql custom step
  server/tests/backends/fixtures/custom/simple.json
  server/tests/steps/sql_translator/test_customsql.py
  server/weaverbird/backends/sql_translator/steps/__init__.py
  server/weaverbird/backends/sql_translator/steps/customsql.py
  server/weaverbird/pipeline/pipeline.py
  server/weaverbird/pipeline/steps/__init__.py
  server/weaverbird/pipeline/steps/customsql.py
  src/components/constants.ts
  src/components/stepforms/CustomSqlStepForm.vue
  src/components/stepforms/index.ts
  src/components/stepforms/schemas/customsql.ts
  src/components/stepforms/schemas/index.ts
  src/lib/labeller.ts
  src/lib/steps.ts
  src/lib/templating.ts
  src/lib/translators/base.ts
  src/lib/translators/snowflake.ts
  tests/unit/customsql-step-form.spec.ts
  tests/unit/labeller.spec.ts
  tests/unit/store.spec.ts
  tests/unit/templating.spec.ts
Labels: :hammer: wip :hammer:, Tortank

#1062 fix(vqb): snowflake granularity + group_by on aggregate, top-n-rows, rank + some refactos + fixtures/unit tests
  server/tests/backends/fixtures/aggregate/snowflake.json
  server/tests/backends/fixtures/aggregate/snowflake_with_original_granularity.json
  server/tests/backends/fixtures/aggregate/snowflake_with_original_granularity_multiple_aggregations.json
  server/tests/backends/fixtures/aggregate/snowflake_with_original_granularity_multiple_aggregations_multiple_columns.json
  server/tests/backends/fixtures/rank/pandas.json
  server/tests/backends/fixtures/rank/snowflake.json
  server/tests/backends/fixtures/top/pandas.json
  server/tests/backends/fixtures/top/snowflake.json
  server/tests/backends/sql_translator/test_snowflake_translator_steps.py
  server/tests/steps/sql_translator/test_aggregate.py
  server/tests/steps/sql_translator/test_rank.py
  server/tests/steps/sql_translator/test_top.py
  server/tests/steps/sql_translator/utils/test_query_transformation.py
  server/weaverbird/backends/sql_translator/steps/aggregate.py
  server/weaverbird/backends/sql_translator/steps/rank.py
  server/weaverbird/backends/sql_translator/steps/top.py
  server/weaverbird/backends/sql_translator/steps/utils/aggregation.py
  server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
  server/weaverbird/backends/sql_translator/types.py
Labels: bug, need review, Tortank

#1069 fix(vqb): fix granularity aggregate + unit tests
  server/tests/backends/sql_translator/test_snowflake_translator_steps.py
  server/tests/steps/sql_translator/test_aggregate.py
  server/tests/steps/sql_translator/utils/test_query_transformation.py
  server/weaverbird/backends/sql_translator/steps/aggregate.py
  server/weaverbird/backends/sql_translator/steps/utils/aggregation.py
  server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
Labels: bug, need review, Tortank

#1074 feat(vqb): Snowflake added argmin + argmax steps
  server/tests/backends/fixtures/argmax/simple.json
  server/tests/backends/fixtures/argmax/with_group.json
  server/tests/backends/fixtures/argmin/simple.json
  server/tests/backends/fixtures/argmin/with_group.json
  server/tests/steps/sql_translator/test_argmax.py
  server/tests/steps/sql_translator/test_argmin.py
  server/weaverbird/backends/sql_translator/steps/__init__.py
  server/weaverbird/backends/sql_translator/steps/argmax.py
  server/weaverbird/backends/sql_translator/steps/argmin.py
  src/lib/translators/snowflake.ts
Labels: need review, Tortank

#1073 feat(sql evolution): add evolution step & unit tests
  server/tests/backends/fixtures/evolution/abs_nogroups.json
  server/tests/backends/fixtures/evolution/perc_groups.json
  server/tests/backends/fixtures/evolution/perc_nogroups.json
  server/tests/steps/sql_translator/test_evolution.py
  server/weaverbird/backends/sql_translator/steps/__init__.py
  server/weaverbird/backends/sql_translator/steps/evolution.py
  src/lib/translators/snowflake.ts
Labels: need review, Tortank

#1078 chore: front 0.60.7 & back 0.8.1 release
  CHANGELOG.md
  package.json
  server/pyproject.toml
  sonar-project.properties
Labels: need review

#1080 feat(sql rollup): create sql vqb rollup step
  server/tests/backends/fixtures/rollup/groupby.json
  server/tests/backends/fixtures/rollup/simple.json
  server/tests/steps/sql_translator/test_rollup.py
  server/tests/steps/sql_translator/utils/test_query_transformation.py
  server/weaverbird/backends/sql_translator/steps/__init__.py
  server/weaverbird/backends/sql_translator/steps/rollup.py
  server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
  src/lib/translators/snowflake.ts
Labels: need review, Tortank

#1082 fix(join): allow join tables with same name
  server/tests/backends/sql_translator/test_metadata.py
  server/weaverbird/backends/sql_translator/metadata.py
Labels: bug

#1084 chore: add data-cy to needed elements for e2e tests
  src/components/DeleteConfirmationModal.vue
  src/components/Pipeline.vue
  src/components/Step.vue
  src/components/stepforms/StepFormHeader.vue
Labels: need review

#1086 v0.60.9
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#1087 feat(vqb): kill residuals tables + job to kill all old tables
  server/tests/backends/sql_translator/test_snowflake_translator_steps.py
Labels: need review, Tortank

#1088 fix(sql vqb): types handling
  server/tests/backends/fixtures/convert/to_integer_only_floats.json
  server/tests/steps/sql_translator/conftest.py
  server/tests/steps/sql_translator/test_aggregate.py
  server/tests/steps/sql_translator/test_append.py
  server/tests/steps/sql_translator/test_argmax.py
  server/tests/steps/sql_translator/test_argmin.py
  server/tests/steps/sql_translator/test_concatenate.py
  server/tests/steps/sql_translator/test_convert.py
  server/tests/steps/sql_translator/test_cumsum.py
  server/tests/steps/sql_translator/test_customsql.py
  server/tests/steps/sql_translator/test_dateextract.py
  server/tests/steps/sql_translator/test_duplicate.py
  server/tests/steps/sql_translator/test_duration.py
  server/tests/steps/sql_translator/test_evolution.py
  server/tests/steps/sql_translator/test_fillna.py
  server/tests/steps/sql_translator/test_filter.py
  server/tests/steps/sql_translator/test_join.py
  server/tests/steps/sql_translator/test_pivot.py
  server/tests/steps/sql_translator/test_rank.py
  server/tests/steps/sql_translator/test_rename.py
  server/tests/steps/sql_translator/test_rollup.py
  server/tests/steps/sql_translator/test_split.py
  server/tests/steps/sql_translator/test_substring.py
  server/tests/steps/sql_translator/test_totals.py
  server/tests/steps/sql_translator/test_unpivot.py
  server/tests/steps/sql_translator/utils/test_query_transformation.py
  server/tests/utils.py
  server/weaverbird/backends/sql_translator/steps/convert.py
  server/weaverbird/backends/sql_translator/steps/split.py
  server/weaverbird/backends/sql_translator/steps/substring.py
  server/weaverbird/backends/sql_translator/steps/table.py
  server/weaverbird/backends/sql_translator/steps/text.py
  server/weaverbird/backends/sql_translator/steps/unpivot.py
  server/weaverbird/backends/sql_translator/steps/utils/aggregation.py
Labels: bug, Tortank

#1090 fix(sql pivot): clean selected cols
  server/tests/steps/sql_translator/test_pivot.py
  server/weaverbird/backends/sql_translator/steps/pivot.py
Labels: bug, Tortank

#1091 fix(sql pivot): handle pivot with illegal characters in value
  server/pyproject.toml
  server/tests/backends/fixtures/pivot/columns_cleaning.json
  server/tests/steps/sql_translator/test_pivot.py
  server/tests/steps/sql_translator/utils/test_query_transformation.py
  server/weaverbird/backends/sql_translator/steps/pivot.py
  server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
Labels: need review, Tortank
