Repository ToucanToco/weaverbird, pull requests merged in 2022-06, with the labels that each got.

#1344 feat: added a monitoring log for steps in pandas executor [TCTC-2844]
  server/src/weaverbird/backends/pandas_executor/pipeline_executor.py
Labels: need review

#1346 fix: logs steps objects [TCTC-2844]
  server/CHANGELOG.md
  server/setup.cfg
  server/src/weaverbird/backends/pandas_executor/pipeline_executor.py
Labels: bug, need review

#1348 chore: move to poetry
  .github/workflows/ci-server.yml
  server/.flake8
  server/CHANGELOG.md
  server/Makefile
  server/README.md
  server/poetry.lock
  server/pyproject.toml
  server/setup.cfg
Labels: need review

#1351 fix(Dockerfile): Set python version in Dockerfile to 3.10
  Dockerfile
Labels: need review, fix

#1352 feat(playground/pandas): Add a geographic pipeline TCTC-2969
  playground/app.js
  playground/datastore/departements-france.geojson
  playground/datastore/departements-regions-france.csv
  playground/datastore/doses-vaccin-departement-france.csv
  server/playground.py
  server/poetry.lock
  server/pyproject.toml
  server/src/weaverbird/backends/pandas_executor/pipeline_executor.py
Labels: enhancement, playground

#1355 chore(server): v0.13.1
  server/CHANGELOG.md
  server/pyproject.toml
Labels: py pandas, release, sql

#1354 feat(server/backends/pandas): Implement geographic dissolve step TCTC-2630
  server/src/weaverbird/backends/pandas_executor/geo_utils.py
  server/src/weaverbird/backends/pandas_executor/steps/__init__.py
  server/src/weaverbird/backends/pandas_executor/steps/dissolve.py
  server/src/weaverbird/pipeline/pipeline.py
  server/src/weaverbird/pipeline/steps/__init__.py
  server/src/weaverbird/pipeline/steps/dissolve.py
  server/tests/backends/fixtures/dissolve/pandas_advanced.json
  server/tests/backends/fixtures/dissolve/pandas_simple.json
  server/tests/backends/pandas_executor/test_pandas_executor_steps.py
Labels: enhancement

#1356 fix(server/pandas): Fix df_to_geodf
  server/src/weaverbird/backends/pandas_executor/geo_utils.py
  server/src/weaverbird/backends/pandas_executor/steps/dissolve.py
  server/tests/backends/pandas_executor/test_pandas_executor_steps.py
Labels: bug, need review, py pandas

#1357 fix(tests/pandas): Allow other_inputs to also be geodata
  server/tests/backends/fixtures/dissolve/pandas_advanced.json
  server/tests/backends/fixtures/dissolve/pandas_simple.json
  server/tests/backends/pandas_executor/test_pandas_executor_steps.py
Labels: bug, need review, py pandas

#1361 refactor(server/pandas/dissolve): Allow to use dissolve without aggregations
  server/src/weaverbird/backends/pandas_executor/steps/dissolve.py
  server/src/weaverbird/pipeline/steps/dissolve.py
  server/tests/backends/fixtures/dissolve/pandas_no_aggs.json
Labels: enhancement, py pandas

#1363 feat(server/backends/pandas): Implement geographic hierarchy step TCTC-2941
  server/src/weaverbird/backends/pandas_executor/steps/__init__.py
  server/src/weaverbird/backends/pandas_executor/steps/hierarchy.py
  server/src/weaverbird/pipeline/pipeline.py
  server/src/weaverbird/pipeline/steps/__init__.py
  server/src/weaverbird/pipeline/steps/hierarchy.py
  server/tests/backends/fixtures/hierarchy/pandas_advanced.json
Labels: enhancement, py pandas

#1366 chore: add ff for basemap as usual datasource [TCTC-3016]
  playground/app.js
  src/store/state.ts
Labels: need review, javascript

#1367 feat(steps): add an icon for geo steps [TCTC-2965]
  src/assets/FA-ICONS.ts
  src/components/ActionToolbar.vue
  src/components/constants.ts
  tests/unit/action-toolbar.spec.ts
Labels: javascript, TO MERGE

#1373 docs: Update server changelog
  server/CHANGELOG.md
Labels: documentation

#1375 chore: pypika translate typing
  server/src/weaverbird/backends/pypika_translator/translate.py
Labels: fix

#1377 feat(sql pypika): handle code mode query as customsqlstep
  server/src/weaverbird/backends/pypika_translator/translators/base.py
Labels: need review

#1378 chore(bump): v0.16.0
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review

#1381 chore: rename postgres dialect
  server/src/weaverbird/backends/pypika_translator/dialects.py
  server/src/weaverbird/backends/pypika_translator/translators/postgresql.py
  server/tests/backends/sql_translator/test_sql_postgres_pypika_translator_steps.py
Labels: need review

#1382 chore(version): v0.16.1
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review

#1383 Various fixes for pypika top step
  server/CHANGELOG.md
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/tests/backends/pypika_translator/test_redshift_translator.py
Labels: bug, pypika

#1385 deps: poetry lock update
  server/poetry.lock
Labels: need review

#1387 chore(front): v0.84.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release, javascript

#1392 fix(docker-compose): Add missing POSTGRESQL_CONNECTION_STRING
  docker-compose.yml
Labels: need review, fix

#1394 fix(backend/fixtures/athena): Update fixtures according to recent dataset update
  server/tests/backends/fixtures/aggregate/with_original_granularity_athena.json
  server/tests/backends/fixtures/argmax/simple_athena.json
  server/tests/backends/fixtures/argmax/with_group_athena.json
  server/tests/backends/fixtures/argmin/with_group_athena.json
  server/tests/backends/fixtures/delete/simple_athena.json
  server/tests/backends/fixtures/duplicate/simple_athena.json
  server/tests/backends/fixtures/fillna/simple_athena.json
  server/tests/backends/fixtures/filter/eq_athena.json
  server/tests/backends/fixtures/formula/division_athena.json
  server/tests/backends/fixtures/formula/nested_athena.json
  server/tests/backends/fixtures/formula/simple_athena.json
  server/tests/backends/fixtures/ifthenelse/combinations_athena.json
  server/tests/backends/fixtures/ifthenelse/nested_athena.json
  server/tests/backends/fixtures/ifthenelse/simple_athena.json
  server/tests/backends/fixtures/lowercase/simple_athena.json
  server/tests/backends/fixtures/rename/edge_case_athena.json
  server/tests/backends/fixtures/rename/multiple_athena.json
  server/tests/backends/fixtures/rename/simple_athena.json
  server/tests/backends/fixtures/replace/simple_athena.json
  server/tests/backends/fixtures/sort/simple_athena.json
  server/tests/backends/fixtures/split/simple_athena.json
  server/tests/backends/fixtures/substring/simple_athena.json
  server/tests/backends/fixtures/text/simple_athena.json
  server/tests/backends/fixtures/top/simple_athena.json
  server/tests/backends/fixtures/trim/multiple_columns_athena.json
  server/tests/backends/fixtures/trim/single_column_athena.json
  server/tests/backends/fixtures/uppercase/simple_athena.json
Labels: tech, pypika

#1395 Enable Athena and Google Big Query in the playground TCTC-3102
  .gitignore
  README.md
  docker-compose.yml
  playground/app.js
  server/playground.py
  server/poetry.lock
  server/pyproject.toml
  src/lib/translators/athena.ts
  src/lib/translators/google-big-query.ts
  tests/unit/translator.spec.ts
Labels: playground, pypika
