Repository ToucanToco/weaverbird, pull requests merged in 2022-09, with the labels that each got.

#1463 feat(sql): add source_rows_subset option on translate sql
  server/src/weaverbird/backends/pypika_translator/translate.py
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/tests/backends/sql_translator_unit_tests/test_base_translator.py
Labels: enhancement

#1464 chore(server): v0.24.0
  server/CHANGELOG.md
  server/pyproject.toml
Labels: tech

#1465 feat(playground): run front-end against a remote server
  README.md
  playground/app.js
  server/playground.py
  server/poetry.lock
  server/pyproject.toml
Labels: need review, playground

#1468 chore(server): SQLDialect now uses the same values than frontend translator names
  server/CHANGELOG.md
  server/pyproject.toml
  server/src/weaverbird/backends/pypika_translator/dialects.py
Labels: pypika

#1469 feat(server/pypika): Implement dateextract step for all backends excetp MySQL
  server/src/weaverbird/backends/pypika_translator/translators/athena.py
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py
  server/src/weaverbird/backends/pypika_translator/translators/mysql.py
  server/src/weaverbird/backends/pypika_translator/translators/postgresql.py
  server/src/weaverbird/backends/pypika_translator/translators/redshift.py
  server/src/weaverbird/backends/pypika_translator/translators/snowflake.py
  server/tests/backends/fixtures/dateextract/pypika_all_cases.json
  server/tests/backends/fixtures/dateextract/snowflake_all_cases.json
  server/tests/backends/sql_translator_unit_tests/test_snowflake_translator.py
Labels: need review, pypika

#1471 chore(deps): Enable dependabot for the backend
  .github/dependabot.yml
  server/poetry.lock
  server/pyproject.toml
Labels: need review, tech

#1470 feat(backend-service): retrieve translator from execute pipeline meta [TCTC-3370]
  playground/app.js
  src/lib/backend.ts
  src/store/actions.ts
  src/store/state.ts
  tests/unit/store.spec.ts
Labels: DO NOT MERGE, javascript

#1480 chore(front): v0.90.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#1478 feat(server/pypika): Implement cumsum step TCTC-3801
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/tests/backends/fixtures/cumsum/simple_pypika.json
  server/tests/backends/fixtures/cumsum/with_groups_pypika.json
  server/tests/backends/fixtures/cumsum/with_multiple_values_pypika.json
  server/tests/backends/sql_translator_unit_tests/test_base_translator.py
  src/lib/translators/pypika.ts
Labels: need review, pypika

#1481 fix(ci): Pin python version to 3.10.6
  .github/workflows/ci-server.yml
Labels: need review, tech

#1482 chore(front): v0.91.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: need review, release

#1483 chore(back): v0.25.0
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review, release

#1489 fix(resizable-columns): disable directive when columns count is too big [TCTC-3887]
  src/directives/resizable/ResizableTable.ts
  src/directives/resizable/resizable.ts
  tests/unit/resizable.spec.ts
Labels: need review, DO NOT MERGE, javascript

#1491 chore(front): v0.91.1
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#1493 chore(front): v0.91.2
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#1495 fix(server/pandas): Fix "matches" operator for IfThenElse with pandas.NA values TCTC-4154
  server/src/weaverbird/backends/pandas_executor/steps/utils/condition.py
  server/tests/steps/test_ifthenelse.py
Labels: bug, need review

#1502 chore: bump mypy 0.971 -> 0.981
  .github/workflows/ci-server.yml
  server/poetry.lock
  server/pyproject.toml
Labels: need review, tech
