Repository ToucanToco/weaverbird, pull requests merged in 2022-07, with the labels that each got.

#1398 Fix playground dependencies
  server/CHANGELOG.md
  server/poetry.lock
  server/pyproject.toml
Labels: playground, release

#1399 chore(front): v0.85.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: need review, release

#1403 chore: enable redshift integration tests
  server/tests/backends/sql_translator_integration_tests/test_sql_redshift_translator_steps.py
Labels: need review

#1396 pypika unittest [TCTC-3120]
  server/tests/backends/sql_translator_unit_tests/test_base_translator.py
  server/tests/backends/sql_translator_unit_tests/test_date_format_translators.py
  server/tests/backends/sql_translator_unit_tests/test_filter_translators.py
  server/tests/backends/sql_translator_unit_tests/test_row_number_translators.py
  server/tests/backends/sql_translator_unit_tests/test_split_part_translators.py
  server/tests/backends/sql_translator_unit_tests/test_type_mapping_translators.py
Labels: need review, pypika

#1405 tests(pypika): upper & lower case edge case
  server/tests/backends/fixtures/lowercase/simple_pypika_null.json
  server/tests/backends/fixtures/uppercase/simple_pypika_null.json
  server/tests/backends/sql_translator_integration_tests/test_sql_postgres_pypika_translator_steps.py
Labels: need review

#1411 test(server/pypika): Add concatenate fixture for pypika
  server/tests/backends/fixtures/concatenate/simple_pypika.yaml
Labels: bug, pypika

#1409 feat: pypika formula divsisions [TCTC-3293]
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/tests/backends/fixtures/formula/division_zero_pypika.json
  server/tests/backends/fixtures/formula/nested_divisions_pypika.json
  server/tests/backends/sql_translator_unit_tests/test_base_translator.py
Labels: need review

#1415 feat(bigquery): split step
  server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py
  server/tests/backends/fixtures/split/simple_pypika.json
Labels: need review

#1407 feat(backend/pypika): Implement JOIN step TCTC-3156
  docs/_docs/tech/known_limitations.md
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/tests/backends/fixtures/join/inner_nested_pypika.yaml
  server/tests/backends/fixtures/join/inner_simple_pypika.yaml
  server/tests/backends/fixtures/join/left_customsql_pypika.yaml
  server/tests/backends/fixtures/join/left_customsql_pypika_bigquery.yaml
  server/tests/backends/sql_translator_unit_tests/test_base_translator.py
  server/tests/backends/sql_translator_unit_tests/test_base_translator_strings.py
Labels: need review, pypika

#1414 feat(backend/pypika): Implement APPEND step TCTC-3157
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/tests/backends/fixtures/append/different_columns_pypika.yaml
  server/tests/backends/fixtures/append/different_columns_tricky_pypika.yaml
  server/tests/backends/fixtures/append/multiple_pypika.yaml
  server/tests/backends/fixtures/append/nested_pypika.yaml
  server/tests/backends/fixtures/append/simple_pypika.yaml
  server/tests/backends/sql_translator_unit_tests/test_base_translator.py
Labels: need review, pypika

#1413 feat: filter date pypika [TCTC-3292]
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py
  server/tests/backends/fixtures/filter/dates_from_until_pypika.json
  server/tests/backends/fixtures/filter/relative_dates_pypika.json
  server/tests/backends/sql_translator_unit_tests/test_filter_translators.py
Labels: need review

#1419 chore(frontend): Enable join and append steps for pypika-based translators
  src/lib/translators/pypika.ts
  tests/unit/translator.spec.ts
Labels: javascript, pypika

#1410 feat(aggregate): implement first & last in pypika's aggregate
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/tests/backends/fixtures/aggregate/first_avg_pypika.json
  server/tests/backends/fixtures/aggregate/first_avg_sum_pypika.json
  server/tests/backends/fixtures/aggregate/first_pypika.json
  server/tests/backends/fixtures/aggregate/first_two_aggs_avg_pypika.json
  server/tests/backends/fixtures/aggregate/first_two_aggs_pypika.json
  server/tests/backends/fixtures/aggregate/first_two_cols_pypika.json
  server/tests/backends/fixtures/aggregate/last_pypika.json
  server/tests/backends/fixtures/aggregate/multiple_aggregations_with_window_func_pypika.json
  server/tests/backends/fixtures/aggregate/with_original_granularity_multiple_aggregations_with_window_func_pypika.json
  server/tests/backends/fixtures/aggregate/with_original_granularity_multiple_window_func_pypika.json
  server/tests/backends/fixtures/aggregate/with_original_granularity_pypika.json
  server/tests/backends/sql_translator_unit_tests/test_base_translator.py
  server/tests/backends/sql_translator_unit_tests/test_base_translator_strings.py
Labels: need review

#1416 feat(pypika convert) TCTC-3291
  server/src/weaverbird/backends/pypika_translator/translators/athena.py
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py
  server/src/weaverbird/backends/pypika_translator/translators/mysql.py
  server/src/weaverbird/backends/pypika_translator/translators/postgresql.py
  server/src/weaverbird/backends/pypika_translator/translators/redshift.py
  server/src/weaverbird/backends/pypika_translator/translators/snowflake.py
  server/tests/backends/fixtures/convert/from_datetime_to_text_athena_bq.json
  server/tests/backends/fixtures/convert/from_datetime_to_text_pypika.json
  server/tests/backends/fixtures/convert/to_bool_pypika.json
  server/tests/backends/fixtures/convert/to_text_pypika.json
  server/tests/backends/sql_translator_integration_tests/test_postgres_translator_steps.py
  server/tests/backends/sql_translator_unit_tests/test_type_mapping_translators.py
Labels: need review

#1418 feat: ifthenelse pypika [TCTC-3294]
  server/src/weaverbird/backends/pypika_translator/operators.py
  server/src/weaverbird/backends/pypika_translator/translators/athena.py
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py
  server/tests/backends/fixtures/filter/dates_from_until_tz_offset_pypika.json
  server/tests/backends/fixtures/ifthenelse/dates_conditions_pypika.json
  server/tests/backends/fixtures/ifthenelse/regex_pypika.json
  server/tests/backends/sql_translator_integration_tests/test_sql_postgres_pypika_translator_steps.py
  server/tests/backends/sql_translator_unit_tests/test_filter_translators.py
  server/tests/utils.py
Labels: need review

#1425 fix: formula step pypika [TCTC-3293]
  server/src/weaverbird/backends/pypika_translator/translators/athena.py
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py
  server/src/weaverbird/backends/pypika_translator/translators/mysql.py
  server/src/weaverbird/backends/pypika_translator/translators/postgresql.py
  server/src/weaverbird/backends/pypika_translator/translators/snowflake.py
  server/tests/backends/fixtures/formula/special_brackets_pypika.json
  server/tests/backends/sql_translator_unit_tests/test_base_translator.py
Labels: need review

#1426 ci: parallelize tests
  .github/workflows/ci-server.yml
  server/Makefile
  server/poetry.lock
  server/pyproject.toml
  server/tests/backends/sql_translator_integration_tests/test_postgres_translator_steps.py
  server/tests/backends/sql_translator_integration_tests/test_sql_mysql_translator_steps.py
  server/tests/backends/sql_translator_integration_tests/test_sql_postgres_pypika_translator_steps.py
Labels: enhancement

#1427 feat: optimize regex on formula step for edge cases
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/tests/backends/fixtures/formula/special_brackets_pypika.json
Labels: need review

#1434 feat(pypika evol): evolution step TCTC-2751
  server/src/weaverbird/backends/pypika_translator/translators/athena.py
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py
  server/src/weaverbird/backends/pypika_translator/translators/mysql.py
  server/src/weaverbird/backends/pypika_translator/translators/postgresql.py
  server/src/weaverbird/backends/pypika_translator/translators/redshift.py
  server/src/weaverbird/backends/pypika_translator/translators/snowflake.py
  server/tests/backends/fixtures/evolution/abs_nogroups_pypika.json
  server/tests/backends/fixtures/evolution/perc_groups_pypika.json
  server/tests/backends/fixtures/evolution/perc_nogroups_pypika.json
  server/tests/backends/sql_translator_unit_tests/test_snowflake_translator.py
Labels: pypika

#1436 chore(server): Remove legacy snowflake tests
  server/tests/backends/sql_translator_integration_tests/test_snowflake_translator_steps.py
Labels: need review, python

#1435 chore: bump v0.18.0
  server/CHANGELOG.md
  server/poetry.lock
  server/pyproject.toml
Labels: need review

#1437 feat(domain-step): enable to label domain step with query name when query is referenced behind an uid [TCTC-3100]
  src/components/Step.vue
  src/lib/labeller.ts
  src/store/mutations.ts
  src/store/state.ts
  tests/unit/labeller.spec.ts
  tests/unit/step.spec.ts
  tests/unit/store.spec.ts
Labels: ui, javascript

#1438 chore(front): v0.86.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: ui, release
