Repository ToucanToco/weaverbird, pull requests merged in 2022-01, with the labels that each got.

#1213 refactor(store): refine code comments and removed unused stuff
  CHANGELOG.md
  src/lib/backend.ts
  src/store/getters.ts
  src/store/mutations.ts
  src/store/state.ts
  tests/unit/store.spec.ts
Labels: need review, tech, ui

#1244 fix: add missing translator to date conversion components [TCTC-1607]
  src/components/stepforms/FromDateStepForm.vue
  src/components/stepforms/ToDateStepForm.vue
Labels: fix

#1245 feat(rollup): no longer needing aggregations TCTC-1552
  CHANGELOG.md
  docs/_docs/user-interface/rollup.md
  server/src/weaverbird/backends/pandas_executor/steps/aggregate.py
  server/src/weaverbird/backends/pandas_executor/steps/rollup.py
  server/src/weaverbird/pipeline/steps/__init__.py
  server/tests/backends/fixtures/rollup/no_aggregation.json
  server/tests/steps/test_rollup.py
  src/components/stepforms/RollupStepForm.vue
  src/components/stepforms/schemas/aggregations.ts
  tests/unit/mongo.spec.ts
  tests/unit/rollup-step-form.spec.ts
Labels: need review, ui, mongo, py pandas

#1248 feat(mongo): concatenate won't fail on non-string columns TCTC-1552
  CHANGELOG.md
  src/lib/translators/mongo.ts
  src/lib/translators/mongo4.ts
  tests/unit/mongo.spec.ts
Labels: mongo

#1247 feat(mongo): division by zero and null in formulas TCTC-1552
  CHANGELOG.md
  server/tests/steps/test_formula.py
  src/lib/translators/mongo.ts
  tests/unit/mongo.spec.ts
Labels: mongo

#1249 feat(ui): select columns from the right dataset in the join step TCTC-1552
  CHANGELOG.md
  src/components/stepforms/JoinStepForm.vue
  src/components/stepforms/widgets/JoinColumns.vue
  src/store/actions.ts
  src/store/state.ts
  tests/unit/join-columns.spec.ts
  tests/unit/join-step-form.spec.ts
  tests/unit/store.spec.ts
Labels: ui

#1251 fix(ui): cumsumstep migration should delete old properties TCTC-1552
  src/components/stepforms/CumSumStepForm.vue
  tests/unit/cumsum-step-form.spec.ts
Labels: ui, mongo, fix

#1255 test(mysql, pgsql): exclude cumsum from test cases
  server/tests/backends/fixtures/cumsum/simple.json
  server/tests/backends/fixtures/cumsum/with_groups.json
  server/tests/backends/fixtures/cumsum/with_multiple_values.json
Labels: tech

#1252 chore(ui): add data cy for date components, pagination and source subset preview TCTC-1515
  src/components/DataViewer.vue
  src/components/DatePicker/Calendar.vue
  src/components/Pagination.vue
  src/components/PreviewSourceSubset.vue
  src/components/stepforms/widgets/DateComponents/CustomVariableList.vue
  src/components/stepforms/widgets/DateComponents/DateRangeInput.vue
  src/components/stepforms/widgets/DateComponents/NewDateInput.vue
  src/components/stepforms/widgets/DateComponents/RelativeDateForm.vue
Labels: tech, ui

#1256 v0.80.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#1258 fix(step): avoid display previous error when creating a new step TCTC-1343
  src/components/QueryBuilder.vue
Labels: fix

#1253 feat: domains can be replaced by references to other queries TCTC-1548
  playground/app.js
  server/src/weaverbird/backends/pandas_executor/steps/utils/combination.py
  server/src/weaverbird/backends/pandas_executor/types.py
  server/src/weaverbird/pipeline/steps/append.py
  server/src/weaverbird/pipeline/steps/domain.py
  server/src/weaverbird/pipeline/steps/join.py
  server/src/weaverbird/pipeline/steps/utils/combination.py
  src/components/QueryBuilder.vue
  src/lib/dereference-pipeline.ts
  src/lib/labeller.ts
  src/lib/steps.ts
  src/lib/templating.ts
  src/lib/translators/mongo.ts
  src/store/actions.ts
  src/store/index.ts
  src/store/mutations.ts
  src/store/state.ts
  tests/unit/labeller.spec.ts
  tests/unit/lib/dereference-pipeline.spec.ts
  tests/unit/mongo.spec.ts
  tests/unit/query-builder.spec.ts
  tests/unit/store.spec.ts
Labels: ui, mongo, py pandas

#1260 v0.81.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#1263 fix(ui): trully load all unique column values TCTC-1688
  CHANGELOG.md
  src/lib/backend.ts
  src/store/actions.ts
  tests/unit/store.spec.ts
Labels: need review, ui, fix

#1264 v0.82.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#1265 fix: fix import path for render
  server/src/weaverbird/backends/sql_translator/steps/append.py
Labels: bug

#1266 doc: add sql pipeline sequence diagram
  server/doc/README.md
  server/doc/sql_pipeline.png
Labels: need review, documentation
