Repository ToucanToco/weaverbird, pull requests merged in 2022-05, with the labels that each got.

#1312 feat(python-mongo-translator): delete step [TCTC-2656]
  server/src/weaverbird/backends/mongo_translator/steps/__init__.py
  server/src/weaverbird/backends/mongo_translator/steps/delete.py
  server/tests/backends/fixtures/delete/simple.json
Labels: need review

#1310 feat(python-mongo-translator): rank step [TCTC-2656]
  server/src/weaverbird/backends/mongo_translator/steps/__init__.py
  server/src/weaverbird/backends/mongo_translator/steps/rank.py
  server/tests/backends/fixtures/rank/group_by.json
  server/tests/backends/fixtures/rank/simple.json
Labels: need review

#1316 fix(tests/mongo_translator): Sanitize pandas dataframes before inserting them into mongo TCTC-2688
  server/tests/backends/fixtures/convert/to_bool.json
  server/tests/backends/fixtures/convert/to_text.json
  server/tests/backends/mongo_translator/test_mongo_translator_steps.py
Labels: need review, fix

#1315 Mongo fill null
  server/src/weaverbird/backends/mongo_translator/steps/__init__.py
  server/src/weaverbird/backends/mongo_translator/steps/fillna.py
  server/tests/backends/fixtures/fillna/date.json
  server/tests/backends/fixtures/fillna/fillinteger.json
  server/tests/backends/fixtures/fillna/simple.json
Labels: need review, mongo

#1319 feat(python-mongo-translator): added duplicate step [TCTC-2657]
  server/src/weaverbird/backends/mongo_translator/steps/__init__.py
  server/src/weaverbird/backends/mongo_translator/steps/duplicate.py
  server/tests/backends/fixtures/duplicate/simple.json
Labels: need review

#1318 feat(python-mongo-translator): evolution step [TCTC-2657]
  server/src/weaverbird/backends/mongo_translator/steps/__init__.py
  server/src/weaverbird/backends/mongo_translator/steps/evolution.py
  server/tests/backends/fixtures/evolution/abs_nogroups.json
  server/tests/backends/fixtures/evolution/perc_groups_mongo.json
  server/tests/backends/fixtures/evolution/perc_nogroups.json
Labels: need review

#1327 fix(backend/pandas_executor): Do not normalize standard deviation and variance in statistics step TCTC-2701
  server/src/weaverbird/backends/pandas_executor/steps/statistics.py
  server/tests/backends/fixtures/statistics/all.json
Labels: need review, fix

#1328 feat(python-mongo-translator): comparetext step [TCTC-2695]
  server/src/weaverbird/backends/mongo_translator/steps/__init__.py
  server/src/weaverbird/backends/mongo_translator/steps/comparetext.py
  server/tests/backends/fixtures/comparetext/simple.json
Labels: need review

#1329 feat(python-mongo-translator): added trim step [TCTC-2695]
  server/src/weaverbird/backends/mongo_translator/steps/__init__.py
  server/src/weaverbird/backends/mongo_translator/steps/trim.py
  server/tests/backends/fixtures/trim/multiple_columns.json
  server/tests/backends/fixtures/trim/single_column.json
Labels: need review

#1332 feat(python-mongo-translator): new dataset to test the waterfall step on the playground [TCTC-2695]
  playground/datastore/revenue-product-dataset.json
  playground/init-mongo/01-import-files.sh
  playground/init-mongo/02-adjust-types.js
Labels: need review

#1334 fix(mongo_translator/evolution): Replace manual date substraction with mongo's operator TCTC-2704
  server/src/weaverbird/backends/mongo_translator/steps/evolution.py
  server/tests/backends/fixtures/evolution/perc_groups.json
  server/tests/backends/fixtures/evolution/perc_groups_mongo.json
Labels: need review, fix

#1338 chore(server): handle cumsum legacy syntax aliases
  server/setup.cfg
  server/src/weaverbird/pipeline/steps/cumsum.py
  server/tests/steps/test_cumsum.py
Labels: bug
