Repository ToucanToco/weaverbird, pull requests merged in 2022-12, with the labels that each got.

#1628 feat(ui/labeller): Improve label for geographical hierarchy step
  ui/CHANGELOG.md
  ui/src/lib/labeller.ts
  ui/tests/unit/labeller.spec.ts
Labels: enhancement, need review

#1634 chore(ui): v0.98.0
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: need review, tech, ui

#1635 docs(ui): storybook downgrade to 6
  ui/.storybook/main.ts
  ui/package.json
  ui/vite.config.ts
  ui/vitest.config.ts
  ui/yarn.lock
Labels: documentation, ui

#1633 fix(mongo-front): added a null default value on switch for mongo date transformations [TCTC-4622]
  CHANGELOG.md
  src/lib/translators/mongo.ts
  src/lib/translators/mongo4.ts
  tests/unit/mongo.spec.ts
Labels: need review

#1637 chore: bump weaverbird ui from 0.92.1 to 0.92.2
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: need review

#1645 [cherry-pick] fix(backend/pandas/addmissingdates): Ensure we always insert pd.Timestamp objects (#1644)
  server/CHANGELOG.md
  server/src/weaverbird/backends/pandas_executor/steps/addmissingdates.py
  server/tests/backends/fixtures/addmissingdates/simple.json
  server/tests/backends/fixtures/addmissingdates/simple_with_tz.yaml
  server/tests/steps/test_addmissingdates.py
Labels: bug, need review, py pandas

#1641 chore(server): bump weaverbird from 0.27.2 to 0.27.3
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review

#1655 fix(new-date-input): popover position [TCTC-4324]
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
  ui/src/components/Popover.vue
  ui/src/components/domutil.ts
  ui/src/components/stepforms/widgets/DateComponents/NewDateInput.vue
  ui/tests/unit/domutil.spec.ts
Labels: ui, fix

#1656 fix(new-date-input): popover position [TCTC-4324] (backport of #1655)
  CHANGELOG.md
  README.md
  package.json
  sonar-project.properties
  src/components/Popover.vue
  src/components/domutil.ts
  src/components/stepforms/widgets/DateComponents/NewDateInput.vue
  tests/unit/domutil.spec.ts
Labels: ui, fix

#1657 feat(labeller): rename queries to availableDomains [TCTC-4877]
  ui/src/components/Step.vue
  ui/src/lib/labeller.ts
  ui/src/store/mutations.ts
  ui/src/store/state.ts
  ui/tests/unit/step.spec.ts
  ui/tests/unit/store.spec.ts
Labels: need review, javascript

#1658 chore(ui): v0.99.0
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: release

#1666 fix(backend/pandas): Convert target column to datetime before extracting datetime information TCTC-4825
  server/CHANGELOG.md
  server/src/weaverbird/backends/pandas_executor/steps/date_extract.py
  server/tests/steps/test_date_extract.py
Labels: bug, need review, py pandas

#1668 fix(backend/pandas): Convert target columns to timestamps before operating on them in evolution step TCTC-4826
  server/CHANGELOG.md
  server/src/weaverbird/backends/pandas_executor/steps/evolution.py
  server/tests/steps/test_evolution.py
Labels: bug, need review, py pandas

#1667 fix(backend/pandas): Convert target columns to timestamps before operating on them in duration step TCTC-4823
  server/CHANGELOG.md
  server/src/weaverbird/backends/pandas_executor/steps/duration.py
  server/tests/steps/test_duration.py
Labels: bug, need review, py pandas

#1669 refactor(backend/pandas): Make previous quarter logic more explicit
  server/src/weaverbird/backends/pandas_executor/steps/date_extract.py
Labels: TO MERGE

#1670 chore(server): v0.26.4
  server/CHANGELOG.md
  server/pyproject.toml
Labels: TO MERGE

#1673 chore(deps): Avoid yanked releases
  server/poetry.lock
  server/pyproject.toml
Labels: need review, tech, python

#1674 chore(deps): Avoid yanked releases
  server/poetry.lock
Labels: need review, tech, python

#1675 fix(backend/mongo/aggregate): Rename `_id` to `__id` in case it's part of an aggregation's new columns
  server/src/weaverbird/backends/mongo_translator/steps/aggregate.py
  server/tests/backends/fixtures/aggregate/first_with_special_column_name_mongo.json
Labels: bug, need review, python

#1676 chore: v0.26.5
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review, tech
