Repository ToucanToco/weaverbird, pull requests merged in 2022-10, with the labels that each got.

#1507 fix(server/pypika/filter): Fix "notmatches" operator for backends using REGEXP
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/tests/backends/fixtures/filter/notmatches_pypika.yaml
  server/tests/backends/sql_translator_unit_tests/test_filter_translators.py
Labels: bug, need review

#1511 chore(server): v0.25.3
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review, tech

#1515 chore(ci/server): Bump ubuntu version 20.04 -> latest
  .github/workflows/ci-server.yml
Labels: need review, tech

#1517 fix(server/pypika): Fix convert step when converting to float
  server/CHANGELOG.md
  server/src/weaverbird/backends/pypika_translator/translators/athena.py
  server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py
  server/src/weaverbird/backends/pypika_translator/translators/mysql.py
  server/tests/backends/fixtures/convert/to_float_pypika.json
Labels: bug, need review

#1525 chore(front): v0.91.3
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: release

#1530 clean: removed replacetext for the old sql_translator
  server/src/weaverbird/backends/sql_translator/steps/replacetext.py
  server/tests/backends/fixtures/replacetext/snowflake_simple.json
  server/tests/steps/sql_translator/test_replacetext.py
Labels: :hammer: wip :hammer:

#1538 feat(textstep): allow to create columns of other types [TCTC-4365]
  server/CHANGELOG.md
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/src/weaverbird/backends/pypika_translator/translators/mysql.py
  server/src/weaverbird/pipeline/steps/text.py
  server/tests/backends/fixtures/text/simple.json
  server/tests/backends/fixtures/text/simple_pypika.json
  server/tests/backends/mongo_translator/test_mongo_translator_steps.py
  server/tests/backends/pandas_executor/test_pandas_executor_steps.py
  server/tests/backends/sql_translator_integration_tests/test_sql_athena_translator_steps.py
  server/tests/backends/sql_translator_integration_tests/test_sql_bigquery_translator_steps.py
  server/tests/backends/sql_translator_integration_tests/test_sql_mysql_translator_steps.py
  server/tests/backends/sql_translator_integration_tests/test_sql_postgres_translator_steps.py
  server/tests/backends/sql_translator_integration_tests/test_sql_redshift_translator_steps.py
  server/tests/backends/sql_translator_integration_tests/test_sql_snowflake_translator_steps.py
  server/tests/backends/sql_translator_unit_tests/test_base_translator.py
  server/tests/conftest.py
  server/tests/steps/test_text.py
Labels: python

#1537 chore: bump v0.26.0
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review

#1541 refactor(front/PyPika): Make Snowflake translator inherit PypikaTranslator
  src/lib/translators/snowflake.ts
Labels: enhancement, need review, pypika

#1540 chore(front): added dependabot for weaverbird frontend
  .github/dependabot.yml
Labels: need review

#1549 chore: prevent CustomSqlStepWithVariables
  server/src/weaverbird/pipeline/steps/__init__.py
  server/src/weaverbird/pipeline/steps/customsql.py
  server/tests/test_pipeline.py
Labels: python

#1556 feat(front): Implement front-end for replacetext step TCTC-4368
  server/src/weaverbird/pipeline/steps/replacetext.py
  src/components/constants.ts
  src/components/stepforms/ReplaceTextStepForm.vue
  src/components/stepforms/index.ts
  src/components/stepforms/schemas/index.ts
  src/components/stepforms/schemas/replaceText.ts
  src/lib/labeller.ts
  src/lib/steps.ts
  src/lib/templating.ts
  src/lib/translators/base.ts
  src/lib/translators/mysql.ts
  src/lib/translators/pandas-no_joins.ts
  src/lib/translators/pandas.ts
  src/lib/translators/pypika.ts
  tests/unit/labeller.spec.ts
  tests/unit/replace-text-step-form.spec.ts
  tests/unit/store.spec.ts
  tests/unit/templating.spec.ts
Labels: enhancement, need review

#1561 chore(back): Release 0.26.1
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review

#1560 chore(front): Release 0.92.0
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: need review

#1562 fix(playground): Allow playground to work even if snowflake is not available
  server/playground.py
Labels: need review, tech, fix

#1550 feat(playground): Added support for MySQL TCTC-3401
  docker-compose.yml
  playground/app.js
  playground/datastore-mysql/default-dataset.csv
  playground/datastore-mysql/sales.csv
  playground/init-mysql/default-dataset.sql
  playground/init-mysql/enable_local_files.cnf
  playground/init-mysql/sales.sql
  server/playground.py
Labels: need review, playground

#1563 feat(frontend): Added support for replacetext to mongo5 translator
  src/lib/translators/mongo5.ts
  tests/unit/action-toolbar-button.spec.ts
Labels: need review

#1564 chore(front): v0.92.1
  CHANGELOG.md
  package.json
  sonar-project.properties
Labels: need review

#1565 feat(frontend): Added support for replacetext to mongo5 translator (#1563) [backport]
  src/lib/translators/mongo5.ts
  tests/unit/action-toolbar-button.spec.ts
Labels: need review

#1566 fix(playground): _SNOWFLAKE_CONNECTION needs to be defined
  server/playground.py
Labels: bug, need review

#1559 feat: Allow all steps to be populated with camelCase fields
  server/src/weaverbird/pipeline/steps/addmissingdates.py
  server/src/weaverbird/pipeline/steps/aggregate.py
  server/src/weaverbird/pipeline/steps/comparetext.py
  server/src/weaverbird/pipeline/steps/cumsum.py
  server/src/weaverbird/pipeline/steps/date_extract.py
  server/src/weaverbird/pipeline/steps/dissolve.py
  server/src/weaverbird/pipeline/steps/duration.py
  server/src/weaverbird/pipeline/steps/evolution.py
  server/src/weaverbird/pipeline/steps/hierarchy.py
  server/src/weaverbird/pipeline/steps/ifthenelse.py
  server/src/weaverbird/pipeline/steps/moving_average.py
  server/src/weaverbird/pipeline/steps/percentage.py
  server/src/weaverbird/pipeline/steps/rank.py
  server/src/weaverbird/pipeline/steps/rename.py
  server/src/weaverbird/pipeline/steps/replacetext.py
  server/src/weaverbird/pipeline/steps/rollup.py
  server/src/weaverbird/pipeline/steps/statistics.py
  server/src/weaverbird/pipeline/steps/substring.py
  server/src/weaverbird/pipeline/steps/totals.py
  server/src/weaverbird/pipeline/steps/utils/base.py
Labels: need review, python

#1490 chore: try to fix sonar issue
  src/directives/resizable/resizable.ts
Labels: tech
