Repository ToucanToco/weaverbird, pull requests merged in 2022-11, with the labels that each got.

#1571 chore(front): remove feature flag hiding geo category TCTC-4234
  playground/app.js
  src/components/constants.ts
  src/store/state.ts
  tests/unit/action-toolbar.spec.ts
Labels: javascript, TO MERGE

#1573 chore(front): v0.93.0
  CHANGELOG.md
  package.json
Labels: release, javascript

#1575 docs: Update the links for todate format strings TCTC-4349
  docs/_docs/user-interface/todate.md
Labels: need review

#1570 chore(front): upgrade to FontAwesome 6
  package.json
  src/assets/FA-ICONS.ts
  yarn.lock
Labels: dependencies, javascript

#1574 feat: from single quote to escaped quote [TCTC-3948]
  server/CHANGELOG.md
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py
  server/tests/backends/fixtures/text/single_quote_pypika.yaml
Labels: need review

#1577 chore(server): 0.27.0
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review

#1578 chore(front): upgrade node to LTS (v18)
  .github/workflows/ci-ui.yml
  .github/workflows/npm-publish.yml
  Dockerfile
  README.md
Labels: javascript

#1583 chore: v0.26.2
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review

#1589 feat(server/playground): Add support for "geometry" dtype for the pandas executor
  server/playground.py
Labels: need review, playground

#1591 docs: Add user and tech documentation for geo steps TCTC-4332
  docs/_docs/tech/steps.md
  docs/_docs/user-interface/dissolve.md
  docs/_docs/user-interface/hierarchy.md
  docs/_docs/user-interface/simplify.md
  docs/img/docs/user-interface/dissolve_step_form.jpg
  docs/img/docs/user-interface/hierarchy_step_form.jpg
  docs/img/docs/user-interface/simplify_step_form.jpg
Labels: need review, documentation

#1594 fix(docs): Add missing menu entries for geo steps
  docs/_data/docs.yml
Labels: bug, need review, documentation

#1593 chore(deps-dev): Bump mypy 0.982 -> 0.990
  server/poetry.lock
  server/pyproject.toml
  server/src/weaverbird/backends/mongo_translator/steps/filter.py
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/src/weaverbird/pipeline/steps/text.py
Labels: need review, dependencies, python

#1590 feat(data-viewer): use map icon when column type is geometry [TCTC-4376]
  src/components/DataViewer.vue
  src/lib/dataset/index.ts
  src/lib/dataset/pandas.ts
  tests/unit/data-viewer.spec.ts
Labels: enhancement, need review

#1599 chore(ui): v0.94.0
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: ui, release

#1602 test(ui): fixes default values not set TCTC-4635
  ui/.eslintrc.js
  ui/.storybook/main.ts
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
  ui/src/components/stepforms/widgets/DateComponents/TabbedRangeCalendars.vue
  ui/src/components/stepforms/widgets/FilterSimpleCondition.vue
  ui/tests/unit/filter-simple-condition-widget.spec.ts
  ui/tests/unit/filter-step-form.spec.ts
  ui/tests/unit/ifthenelse-step-form.spec.ts
  ui/yarn.lock
Labels: ui

#1604 build(ui): use more standard exports for UI lib
  ui/.eslintrc.cjs
  ui/.prettierrc.cjs
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: need review, build, ui

#1606 chore(ui): depencies security updates
  ui/package.json
  ui/yarn.lock
Labels: ui, dependencies

#1616 chore(ui): v0.96.0
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: ui, release

#1617 refactor: Adapt playground response format to new pagination
  server/playground.py
  server/poetry.lock
  server/pyproject.toml
Labels: need review, playground, dependencies

#1621 fix(server/pypika/filter): Ensure column to match with a regex is first casted to text
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/tests/backends/fixtures/filter/matches_with_float_pypika.yaml
  server/tests/backends/fixtures/filter/notmatches_with_float_pypika.yaml
  server/tests/backends/sql_translator_unit_tests/test_filter_translators.py
Labels: bug, need review, pypika

#1622 chore(server): v0.27.2
  server/CHANGELOG.md
  server/poetry.lock
  server/pyproject.toml
Labels: need review, tech

#1624 fix(playground): Adapt pagination_info responses for mongo & postgres
  server/playground.py
Labels: playground, fix

#1625 fix(playground): Add pagination_info for pandas
  server/playground.py
Labels: need review, playground, fix

#1623 feat(pagination): update model and use new arrow pagination [TCTC-4735]
  playground/dist/app.js
  ui/Playground.vue
  ui/src/assets/FA-ICONS.ts
  ui/src/components/ArrowPagination.vue
  ui/src/components/DataViewer.vue
  ui/src/components/Pagination.vue
  ui/src/lib/dataset/helpers.ts
  ui/src/lib/dataset/pagination.ts
  ui/src/main.ts
  ui/src/store/actions.ts
  ui/src/store/getters.ts
  ui/src/store/mutations.ts
  ui/src/store/state.ts
  ui/stories/DataViewer.stories.ts
  ui/tests/arrow-pagination.spec.ts
  ui/tests/unit/data-viewer.spec.ts
  ui/tests/unit/dataset.spec.ts
  ui/tests/unit/pagination-component.spec.ts
  ui/tests/unit/pagination.spec.ts
  ui/tests/unit/pipeline.spec.ts
  ui/tests/unit/store.spec.ts
Labels: enhancement

#1626 deps: dependabot from daily to weekly checks
  .github/dependabot.yml
Labels: need review

#1627 chore(ui): v0.97.0
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: ui
