Repository ToucanToco/weaverbird, pull requests merged in 2023-06, with the labels that each got.

#1789 feat(nativeSQL): we want to cast to integer a column resulting from a date extract
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/tests/backends/sql_translator_unit_tests/test_base_translator.py
  server/tests/backends/sql_translator_unit_tests/test_snowflake_translator.py
Labels: need review

#1792 chore: bump from 0.26.7 to 0.26.8 [TCTC-6089]
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review

#1793 feat: we want to cast to integer a column resulting from a date extract (#1789)
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/tests/backends/sql_translator_unit_tests/test_base_translator.py
  server/tests/backends/sql_translator_unit_tests/test_snowflake_translator.py
Labels: need review

#1795 feat(server/pypika): Merge first two steps when possible
  server/CHANGELOG.md
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py
  server/src/weaverbird/backends/pypika_translator/translators/mysql.py
  server/src/weaverbird/backends/pypika_translator/translators/postgresql.py
  server/src/weaverbird/backends/pypika_translator/translators/redshift.py
  server/tests/backends/sql_translator_unit_tests/conftest.py
  server/tests/backends/sql_translator_unit_tests/test_base_translator_strings.py
  server/tests/backends/sql_translator_unit_tests/test_translation_with_mergeable_first_step.py
Labels: enhancement, need review, pypika, python

#1797 feat: add remove void from mongo step [TCTC-6102]
  server/CHANGELOG.md
  server/src/weaverbird/pipeline/pipeline.py
  server/tests/test_pipeline.py
Labels: need review

#1802 chore: bump from 0.31.1 to 0.32.0
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review, release

#1810 chore(server): v0.33.0
  server/CHANGELOG.md
  server/pyproject.toml
Labels: release, python

#1811 chore(ui): v0.103.0
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: release

#1812 feat(labeller): enable to override retrieveDomainName by passing a custom method to store state
  ui/src/components/Step.vue
  ui/src/store/actions.ts
  ui/src/store/state.ts
  ui/tests/unit/step.spec.ts
  ui/tests/unit/store.spec.ts
Labels: need review

#1813 chore(ui): v0.104.0
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: release
