Repository ToucanToco/weaverbird, pull requests merged in 2023-10, with the labels that each got.

#1909 fix: backport fixes from #1857 TCTC-6992
  server/CHANGELOG.md
  server/src/weaverbird/backends/pypika_translator/translators/athena.py
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py
  server/src/weaverbird/backends/pypika_translator/translators/mysql.py
  server/src/weaverbird/backends/pypika_translator/translators/postgresql.py
  server/src/weaverbird/backends/pypika_translator/translators/redshift.py
  server/src/weaverbird/backends/pypika_translator/translators/snowflake.py
  server/tests/backends/fixtures/todate/simple_y_m_d_formatting_pypika.yaml
  server/tests/backends/sql_translator_unit_tests/test_adapt_date_format.py
  server/tests/backends/sql_translator_unit_tests/test_date_format_translators.py
Labels: bug, need review, backport, pypika, python

#1910 chore: v0.26.9
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review

#1911 feat(server): added a backfill option to the waterfall step TCTC-6931
  server/CHANGELOG.md
  server/src/weaverbird/backends/mongo_translator/steps/waterfall.py
  server/src/weaverbird/backends/pandas_executor/steps/waterfall.py
  server/src/weaverbird/pipeline/steps/waterfall.py
  server/tests/backends/fixtures/waterfall/simple.json
  server/tests/backends/fixtures/waterfall/with_aggregation.json
  server/tests/backends/fixtures/waterfall/with_backfill.yaml
  server/tests/backends/fixtures/waterfall/with_groups.json
  server/tests/backends/fixtures/waterfall/without_backfill.yaml
  server/tests/backends/mongo_translator/test_mongo_translator_steps.py
  server/tests/steps/test_waterfall.py
Labels: need review, mongo, py pandas, python

#1912 feat(ui): Added support for backfill option in waterfall step
  ui/CHANGELOG.md
  ui/src/components/stepforms/WaterfallStepForm.vue
  ui/src/components/stepforms/schemas/waterfall.ts
  ui/src/lib/steps.ts
  ui/tests/unit/waterfall-step-form.spec.ts
Labels: ui

#1914 chore(ui): v0.111.0
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: need review

#1920 fix(server/waterfall): Make the first milestone the first element of the dataset
  server/CHANGELOG.md
  server/src/weaverbird/backends/mongo_translator/steps/waterfall.py
  server/src/weaverbird/backends/pandas_executor/steps/waterfall.py
  server/tests/backends/fixtures/waterfall/simple.json
  server/tests/backends/fixtures/waterfall/with_aggregation.json
  server/tests/backends/fixtures/waterfall/with_backfill.yaml
  server/tests/backends/fixtures/waterfall/with_groups.json
  server/tests/backends/fixtures/waterfall/without_backfill.yaml
  server/tests/steps/test_waterfall.py
Labels: bug, need review

#1921 chore(server): v0.38.1
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review, tech

#1924 chore(ui): remove engine
  ui/package.json
Labels: need review, tech, ui
