Repository ToucanToco/weaverbird, pull requests merged in 2023-09, with the labels that each got.

#1879 fix(server/pandas): Preserve row order in rank step sort
  server/CHANGELOG.md
  server/src/weaverbird/backends/pandas_executor/steps/rank.py
  server/tests/steps/test_rank.py
Labels: bug, need review, py pandas, python

#1878 feat(server/pypika): Add support for the duration step TCTC-6158
  server/CHANGELOG.md
  server/src/weaverbird/backends/pypika_translator/translators/athena.py
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py
  server/src/weaverbird/backends/pypika_translator/translators/postgresql.py
  server/src/weaverbird/backends/pypika_translator/translators/snowflake.py
  server/tests/backends/fixtures/duration/all_cases_pypika.yaml
  server/tests/backends/sql_translator_unit_tests/conftest.py
  server/tests/backends/sql_translator_unit_tests/test_base_translator.py
  server/tests/backends/sql_translator_unit_tests/test_date_format_translators.py
  server/tests/backends/sql_translator_unit_tests/test_filter_translators.py
  server/tests/backends/sql_translator_unit_tests/test_row_number_translators.py
  server/tests/backends/sql_translator_unit_tests/test_split_part_translators.py
  server/tests/backends/sql_translator_unit_tests/test_type_mapping_translators.py
  ui/CHANGELOG.md
  ui/src/lib/translators/pypika.ts
Labels: enhancement, need review, pypika, python

#1881 feat(ui): Disable customsql step in pypika translator TCTC-6722
  ui/CHANGELOG.md
  ui/src/lib/translators/pypika.ts
Labels: need review, ui, pypika

#1882 chore(server): v0.37.0
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review

#1883 chore(ui): v0.108.0
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: need review

#1885 feat(ui): Disable join and append steps in pypika translator TCTC-6732
  ui/CHANGELOG.md
  ui/src/lib/translators/pypika.ts
  ui/tests/unit/translator.spec.ts
Labels: need review

#1884 fix(server/pypika): Ensure the duration step converts columns to floats before dividing
  server/CHANGELOG.md
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/tests/backends/fixtures/evolution/perc_nogroups_integers_pypika.yaml
Labels: bug, need review

#1886 fix(server/pypika): fix `firstDayOfPreviousMonth` for dateextract step TCTC-6735
  server/CHANGELOG.md
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py
  server/tests/backends/fixtures/dateextract/first_day_of_previous_month_pypika.yaml
Labels: bug, need review

#1887 chore(server): v0.37.1
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review

#1888 chore(ui): v0.109.0
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: need review

#1900 fix(ui): remove relative date filtering feature flag and related code [TCTC-6755]
  playground/dist/app.js
  ui/Playground.vue
  ui/src/components/stepforms/widgets/FilterSimpleCondition.vue
  ui/src/store/state.ts
  ui/tests/unit/filter-simple-condition-widget.spec.ts
Labels: enhancement, need review

#1901 chore(ui): v.0.110.0
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: release
