Repository ToucanToco/weaverbird, pull requests merged in 2023-11, with the labels that each got.

#1948 feat(sql): customsql step can contains a column list TCTC-7280
  server/CHANGELOG.md
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/src/weaverbird/pipeline/steps/customsql.py
  ui/src/components/stepforms/CustomSqlStepForm.vue
  ui/src/components/stepforms/schemas/customsql.ts
  ui/src/lib/steps.ts
Labels: need review, sql

#1949 ci(server): v0.39.0
  server/CHANGELOG.md
  server/pyproject.toml
Labels: release, python

#1953 fix(filter-condition): display all variables for date component not only date type once [TCTC-7312]
  ui/src/components/stepforms/widgets/FilterSimpleCondition.vue
  ui/tests/unit/filter-simple-condition-widget.spec.ts
Labels: bug, need review

#1954 chore(ui): v0.111.1
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: release
