Repository ToucanToco/weaverbird, pull requests merged in 2023-07, with the labels that each got.

#1816 chore(ui): v0.105.0
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: release

#1817 fix: add case insensitive on matches/notmatches filter steps [TCTC-6338]
  server/CHANGELOG.md
  server/src/weaverbird/backends/mongo_translator/steps/filter.py
  server/tests/backends/mongo_translator/steps/test_filter.py
Labels: need review

#1818 fix: keep None/null on $ne and $eq direct value to fix isnull/isnotnull filter step condition for mongo [TCTC-6339]
  server/CHANGELOG.md
  server/src/weaverbird/pipeline/pipeline.py
  server/tests/test_pipeline.py
Labels: need review

#1819 chore: bump from 0.33.0 to 0.33.1 [TCTC-6339, TCTC-6338]
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review

#1821 chore: bump from 0.33.1 to 0.33.2
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review

#1826 chore(server): v0.34.0
  server/CHANGELOG.md
  server/pyproject.toml
Labels: release

#1833 chore(ui): v0.105.1
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: release

#1835 test(server): how to re-create the BigQuery test DB
  server/tests/backends/sql_translator_integration_tests/test_sql_bigquery_translator_steps.py
Labels: tech, pypika

#1838 fix: keep empty list to make mongo steps still working as before [TCTC-6370]
  server/CHANGELOG.md
  server/src/weaverbird/pipeline/pipeline.py
  server/tests/test_pipeline.py
Labels: need review

#1839 chore: bump from 0.34.0 to 0.34.1
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review

#1841 fix(server/mongo): Fix join step on columns with weird names TCTC-6412
  server/src/weaverbird/backends/mongo_translator/steps/join.py
  server/tests/backends/fixtures/join/left_weird_name.json
  server/tests/backends/mongo_translator/test_mongo_translator_steps.py
Labels: bug, mongo, python

#1840 feat(server/translators/pypika): Implement rank step TCTC-6452
  server/CHANGELOG.md
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/tests/backends/fixtures/rank/grouped_standard_pypika.yaml
  server/tests/backends/fixtures/rank/simple_dense_pypika.yaml
  server/tests/backends/fixtures/rank/simple_standard_pypika.yaml
Labels: enhancement, need review, pypika

#1842 chore(server): v0.35.0
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review, build, python
