Repository ToucanToco/weaverbird, pull requests merged in 2023-01, with the labels that each got.

#1681 chore: cleaning of translate and deferences unused methods [TCTC-4934]
  playground/dist/app.js
  ui/Playground.vue
  ui/src/components/stepforms/AppendStepForm.vue
  ui/src/components/stepforms/JoinStepForm.vue
  ui/src/lib/dereference-pipeline.ts
  ui/src/lib/translators/mongo.ts
  ui/src/main.ts
  ui/src/store/getters.ts
  ui/tests/unit/append-step-form.spec.ts
  ui/tests/unit/join-step-form.spec.ts
  ui/tests/unit/lib/dereference-pipeline.spec.ts
  ui/tests/unit/mongo.spec.ts
  ui/tests/unit/store.spec.ts
  ui/tests/unit/translator.spec.ts
Labels: need review, playground, :recycle: cleaning :recycle:, javascript

#1680 fix(new-date-input): show all options for relative date dropdown [TCTC-3428] [TCTC-2484]
  ui/src/components/stepforms/widgets/Autocomplete.vue
  ui/src/components/stepforms/widgets/DateComponents/NewDateInput.vue
  ui/src/components/stepforms/widgets/DateComponents/RelativeDateForm.vue
  ui/tests/unit/autocomplete-widget.spec.ts
Labels: bug

#1687 refactor(backend/pypika): Prevent the usage of wildcards in column lists TCTC-4241
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/src/weaverbird/backends/pypika_translator/translators/exceptions.py
  server/tests/backends/sql_translator_unit_tests/test_base_translator.py
  server/tests/backends/sql_translator_unit_tests/test_base_translator_strings.py
Labels: need review, pypika, python

#1689 fix(backend/pandas): Add support for non-numeric columns to "top" step TCTC-4604
  server/CHANGELOG.md
  server/src/weaverbird/backends/pandas_executor/steps/top.py
  server/tests/backends/fixtures/top/simple_strings.json
  server/tests/backends/fixtures/top/with_groups_and_dates.json
Labels: bug, need review, py pandas

#1690 chore(server): v0.26.6
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review, tech

#1695 fix(new-date-input): show all options for relative date dropdown (2nd fix) [TCTC-3428] [TCTC-2484]
  ui/src/components/stepforms/widgets/Autocomplete.vue
  ui/src/components/stepforms/widgets/DateComponents/RelativeDateForm.vue
Labels: bug

#1698 fix(ui): specify which node version is supported
  ui/package.json
Labels: need review, build, ui

#1699 fix(server/pypika): Allow queries consisting of a single CustomSQL step to be materialized when no columns are specified
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/tests/backends/sql_translator_unit_tests/test_base_translator.py
Labels: bug, need review

#1701 chore(server): v0.28.1
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review, tech

#1685 fix(new-date-input): show all options for relative date dropdown [TCTC-3428] [TCTC-2484]
  CHANGELOG.md
  package.json
  sonar-project.properties
  src/components/stepforms/widgets/Autocomplete.vue
  src/components/stepforms/widgets/DateComponents/NewDateInput.vue
  src/components/stepforms/widgets/DateComponents/RelativeDateForm.vue
  tests/unit/autocomplete-widget.spec.ts
Labels: bug

#1710 chore(server): v0.28.2
  server/CHANGELOG.md
  server/poetry.lock
  server/pyproject.toml
Labels: need review, tech, python
