Repository ToucanToco/weaverbird, pull requests merged in 2023-08, with the labels that each got.

#1848 feat(ui): Added concatenate step to pypika translator TCTC-6155
  ui/CHANGELOG.md
  ui/src/lib/translators/pypika.ts
Labels: need review, ui

#1849 feat(ui): Added fromdate step to pypika translator
  ui/CHANGELOG.md
  ui/src/lib/translators/pypika.ts
Labels: need review, ui

#1853 fix: escape properly column names on GBQ [TCTC-6519]
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py
  server/tests/backends/sql_translator_unit_tests/test_google_big_query.py
Labels: bug

#1854 chore: bump weaverbird to 0.35.2 to include fix for TCTC-6519
  server/CHANGELOG.md
  server/pyproject.toml
Labels: release, python

#1858 chore: bump from 0.35.2 to 0.35.3
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review

#1860 chore(server): v0.35.4
  server/CHANGELOG.md
  server/pyproject.toml
Labels: release, python

#1862 chore(ui): v0.107.0
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: need review

#1863 fix(server/pipeline): Preserve falsy values in remove_void_conditions_from_mongo_steps TCTC-6570
  server/CHANGELOG.md
  server/src/weaverbird/pipeline/pipeline.py
  server/tests/test_pipeline.py
Labels: bug, python

#1867 refactor(server/pypika): Make the percentage step return values between 0 and 1 TCTC-6157
  server/CHANGELOG.md
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/tests/backends/fixtures/percentage/simple_pypika.yaml
  server/tests/backends/fixtures/percentage/with_groups_pypika.yaml
Labels: enhancement, need review, pypika, python

#1868 chore(server): v0.36.0
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review, tech

#1869 fix(server/pipeline): Only apply remove_void_conditions_from_mongo_steps to $match steps TCTC-6597
  server/CHANGELOG.md
  server/src/weaverbird/pipeline/pipeline.py
  server/tests/backends/fixtures/aggregate/without_on.yaml
  server/tests/test_pipeline.py
Labels: bug, need review, python

#1873 fix(server/pypika): Various improvements on the fromdate step TCTC-6156
  server/CHANGELOG.md
  server/src/weaverbird/backends/pypika_translator/operators.py
  server/src/weaverbird/backends/pypika_translator/translators/athena.py
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py
  server/src/weaverbird/backends/pypika_translator/translators/postgresql.py
  server/src/weaverbird/backends/pypika_translator/translators/redshift.py
  server/tests/backends/fixtures/fromdate/day_longmonth_year_space_pypika.yaml
  server/tests/backends/fixtures/fromdate/day_shortmonth_year_dash_pypika.yaml
  server/tests/backends/fixtures/fromdate/day_shortmonth_year_space_pypika.yaml
  server/tests/backends/fixtures/fromdate/longmonth_year_space_pypika.yaml
  server/tests/backends/fixtures/fromdate/shortmonth_year_dash_pypika.yaml
  server/tests/backends/fixtures/fromdate/simple_pypika.yaml
  server/tests/backends/sql_translator_unit_tests/test_adapt_date_format.py
Labels: bug, need review, pypika, python

#1874 chore(server): 0.36.2
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review, tech
