Repository ToucanToco/weaverbird, pull requests merged in 2023-05, with the labels that each got.

#1767 feat(code-editor-widget): remove watch flacky logic [TCTC-6012]
  ui/src/components/stepforms/widgets/CodeEditorWidget.vue
Labels: bug

#1768 chore(ui): v0.102.1
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: release

#1775 feat(ci): Enabled dependabot on github actions
  .github/dependabot.yml
Labels: need review, tech

#1773 chore: quote column names in "OVER(PARTITION BY xxx" [TCTC-5844]
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/tests/backends/fixtures/aggregate/multiple_aggregations_with_window_func_pypika.json
Labels: bug, need review

#1763 feat: avoid filter step having __VOID__ in it (AND, OR or simple condition) recursivelly [TCTC-5480, TCTC-6102]
  server/src/weaverbird/pipeline/pipeline.py
  server/tests/test_pipeline.py
Labels: DO NOT MERGE, POC

#1777 fix: we need to cast to integer a column resulting from a date extract when needed [TCTC-6089]
  server/src/weaverbird/backends/pandas_executor/steps/date_extract.py
  server/src/weaverbird/pipeline/steps/date_extract.py
  server/tests/backends/fixtures/dateextract/all_cases.json
  server/tests/backends/sql_translator_unit_tests/test_base_translator.py
  server/tests/steps/test_date_extract.py
Labels: need review

#1783 fix: we need to cast to integer a column resulting from a date extract when needed [TCTC-6089] (#1777)
  server/src/weaverbird/backends/pandas_executor/steps/date_extract.py
  server/src/weaverbird/pipeline/steps/date_extract.py
  server/tests/backends/fixtures/dateextract/all_cases.json
  server/tests/backends/sql_translator_unit_tests/test_base_translator.py
  server/tests/steps/test_date_extract.py
Labels: need review

#1784 chore: bump weaverbird from 0.26.6 to 0.26.7
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review

#1786 fix(pipeline): render should only render
  server/src/weaverbird/pipeline/pipeline.py
  server/tests/test_pipeline.py
Labels: bug, need review
