Repository ToucanToco/weaverbird, pull requests merged in 2024-07, with the labels that each got.

#2170 fix: don't aggregate multiple times the same column (TCTC-8351)
  server/CHANGELOG.md
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/tests/backends/fixtures/aggregate/multiple_aggregations_with_same_columns.yaml
Labels: bug, need review, build, pypika

#2171 chore(server): v0.45.8
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review, release

#2177 fix(server/pandas): reindex rows at the end of rollup step (TCTC-8689)
  server/CHANGELOG.md
  server/src/weaverbird/backends/pandas_executor/steps/rollup.py
  server/tests/backends/fixtures/rollup/datetime_followed_by_dateextract.yaml
Labels: bug, py pandas, :eye: review ongoing :eye:

#2178 chore(server): v0.45.10
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review, release

#2188 chore: bump geopandas version on branch backend/release/v0.26
  server/CHANGELOG.md
  server/poetry.lock
  server/pyproject.toml
  server/tests/backends/fixtures/dissolve/pandas_advanced.json
  server/tests/backends/fixtures/dissolve/pandas_no_aggs.json
  server/tests/backends/sql_translator_integration_tests/test_sql_redshift_translator_steps.py
Labels: dependencies
