Repository ToucanToco/weaverbird, pull requests merged in 2024-09, with the labels that each got.

#2042 feat(deps): support pandas>=2 [TCTC-7546]
  .github/workflows/ci-server.yml
  server/poetry.lock
  server/pyproject.toml
  server/src/weaverbird/backends/pandas_executor/steps/append.py
  server/src/weaverbird/backends/pandas_executor/steps/duration.py
  server/src/weaverbird/backends/pandas_executor/steps/moving_average.py
  server/src/weaverbird/backends/pandas_executor/steps/utils/cast.py
  server/tests/backends/fixtures/addmissingdates/simple_with_tz.yaml
  server/tests/backends/fixtures/append/different_columns_tricky_pypika.yaml
  server/tests/backends/fixtures/convert/to_datetime.json
  server/tests/backends/fixtures/convert/to_datetime_from_timestamp.json
  server/tests/backends/fixtures/convert/to_integer_from_datetime.json
  server/tests/backends/fixtures/dateextract/after_add_missing_dates_duplicate_values.json
  server/tests/backends/fixtures/dateextract/google_big_query_datetimes.yaml
  server/tests/backends/fixtures/dateextract/google_big_query_timestamps.yaml
  server/tests/backends/fixtures/fillna/date.json
  server/tests/backends/fixtures/filter/date_eq_pypika.yaml
  server/tests/backends/fixtures/filter/date_in_pypika.yaml
  server/tests/backends/fixtures/filter/date_in_with_null_pypika.yaml
  server/tests/backends/fixtures/filter/dates_from_until_too_wide.json
  server/tests/backends/fixtures/join/inner_nested_pypika.yaml
  server/tests/backends/fixtures/join/inner_simple_pypika.yaml
  server/tests/backends/fixtures/join/left_customsql_pypika.yaml
  server/tests/backends/fixtures/join/left_customsql_pypika_bigquery.yaml
  server/tests/backends/fixtures/movingaverage/with_groups.json
  server/tests/backends/fixtures/todate/automatic_guess.json
  server/tests/backends/fixtures/todate/from_timestamp.json
  server/tests/backends/fixtures/todate/int_as_year_with_automatic_guess.json
  server/tests/backends/fixtures/todate/simple.json
  server/tests/backends/fixtures/todate/simple_gbq_pypika.yaml
  server/tests/backends/fixtures/todate/simple_non_percent_formatting_pypika.yaml
  server/tests/backends/fixtures/todate/simple_percent_formatting_pypika.yaml
  server/tests/backends/fixtures/todate/str_as_year_with_automatic_guess.json
  server/tests/backends/mongo_translator/test_mongo_translator_steps.py
  server/tests/backends/pandas_executor/test_pandas_executor_steps.py
  server/tests/backends/sql_translator_integration_tests/test_sql_athena_translator_steps.py
  server/tests/backends/sql_translator_integration_tests/test_sql_bigquery_translator_steps.py
  server/tests/backends/sql_translator_integration_tests/test_sql_mysql_translator_steps.py
  server/tests/backends/sql_translator_integration_tests/test_sql_postgres_translator_steps.py
  server/tests/backends/sql_translator_integration_tests/test_sql_redshift_translator_steps.py
  server/tests/backends/sql_translator_integration_tests/test_sql_snowflake_translator_steps.py
  server/tests/steps/test_evolution.py
  server/tests/steps/test_join.py
Labels: need review, dependencies, python

#2226 chore(server): bump version to v0.26.18
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review, release

#2227 chore(server): bump version to v0.47.0
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review, release

#2228 fix(ui): add total step rows does not require any aggregation TCTC-9199
  ui/src/components/stepforms/AddTotalRowsStepForm.vue
  ui/stories/AddTotalRowsStepForm.stories.ts
  ui/tests/unit/totals-step-form.spec.ts
Labels: ui, fix

#2229 feat(ui): allow to type custom columns in step forms TCTC-9216
  ui/src/components/stepforms/AddMissingDatesStepForm.vue
  ui/src/components/stepforms/AddTotalRowsStepForm.vue
  ui/src/components/stepforms/AggregateStepForm.vue
  ui/src/components/stepforms/ArgmaxStepForm.vue
  ui/src/components/stepforms/ArgminStepForm.vue
  ui/src/components/stepforms/ColumnPicker.vue
  ui/src/components/stepforms/ConvertStepForm.vue
  ui/src/components/stepforms/CumSumStepForm.vue
  ui/src/components/stepforms/DeleteColumnStepForm.vue
  ui/src/components/stepforms/DissolveStepForm.vue
  ui/src/components/stepforms/EvolutionStepForm.vue
  ui/src/components/stepforms/FillnaStepForm.vue
  ui/src/components/stepforms/MovingAverageStepForm.vue
  ui/src/components/stepforms/PercentageStepForm.vue
  ui/src/components/stepforms/PivotStepForm.vue
  ui/src/components/stepforms/RankStepForm.vue
  ui/src/components/stepforms/RollupStepForm.vue
  ui/src/components/stepforms/SelectColumnStepForm.vue
  ui/src/components/stepforms/StatisticsStepForm.vue
  ui/src/components/stepforms/TopStepForm.vue
  ui/src/components/stepforms/TrimStepForm.vue
  ui/src/components/stepforms/UniqueGroupsStepForm.vue
  ui/src/components/stepforms/UnpivotStepForm.vue
  ui/src/components/stepforms/WaterfallStepForm.vue
  ui/src/components/stepforms/widgets/Aggregation.vue
  ui/src/components/stepforms/widgets/Autocomplete.vue
  ui/src/components/stepforms/widgets/JoinColumns.vue
  ui/src/components/stepforms/widgets/Multiselect.vue
  ui/stories/AggregateStepForm.stories.ts
  ui/stories/Autocomplete.stories.ts
  ui/stories/ColumnPicker.stories.ts
  ui/stories/Multiselect.stories.ts
  ui/tests/unit/autocomplete-widget.spec.ts
Labels: ui

#2230 fix(server): prevent custom SQL queries finishing with comments to fail
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/tests/backends/sql_translator_unit_tests/test_base_translator.py
  server/tests/backends/sql_translator_unit_tests/test_base_translator_strings.py
  server/tests/backends/sql_translator_unit_tests/test_translation_with_mergeable_first_step.py
Labels: sql, python

#2231 chore(ui): v0.114.0
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: ui, release

#2232 chore(server): v0.47.1
  server/CHANGELOG.md
  server/pyproject.toml
Labels: release, python

#2233 fix(ui): wrong package version v0.114.0
  ui/package.json
  ui/sonar-project.properties
Labels: ui, release

#2236 chore(ui): v0.114.1
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: ui, release

#2238 feat: unify weaverbird pipeline failure exceptions (TCTC-9178)
  server/CHANGELOG.md
  server/src/weaverbird/backends/mongo_translator/mongo_pipeline_translator.py
  server/src/weaverbird/backends/pandas_executor/pipeline_executor.py
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/src/weaverbird/exceptions.py
  server/tests/backends/sql_translator_unit_tests/test_base_translator.py
Labels: enhancement, need review, build, DO NOT MERGE

#2239 chore(server): bump to v0.48.0
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review, release

#2240 fix: ifthenelse step must return an unique list of column names (TCTC-9145)
  server/CHANGELOG.md
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/tests/backends/fixtures/ifthenelse/override_column_name_pypika.yaml
Labels: bug, need review, build, pypika

#2249 chore(ui): v0.115.0
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: release

#2251 fix(step-form-component): provide step form defaults and preselect column if necessary in complex steps [TCTC-9437]
  ui/src/components/stepforms/StepFormComponent.vue
  ui/src/components/stepforms/StoreStepFormComponent.vue
  ui/stories/StepForm.stories.ts
Labels: bug, need review
