Repository ToucanToco/weaverbird, pull requests merged in 2024-03, with the labels that each got.

#2032 fix(gbq translator): todate now produces DATETIME cols, not TIMESTAMP [TCTC-7994]
  server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py
Labels: bug

#2030 fix(mongo translator): fix typo in ifthenelse "$or" combination [TCTC-8007]
  server/CHANGELOG.md
  server/pyproject.toml
  server/src/weaverbird/backends/mongo_translator/utils.py
  server/tests/backends/fixtures/ifthenelse/combination_or.json
Labels: bug

#2031 [backport] fix(mongo translator): fix typo in ifthenelse "$or" combination
  server/CHANGELOG.md
  server/pyproject.toml
  server/src/weaverbird/backends/mongo_translator/utils.py
  server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py
  server/tests/backends/fixtures/ifthenelse/combination_or.json
Labels: bug

#2036 feat(dependabot): group python dependencies bumps
  .github/dependabot.yml
Labels: enhancement, need review, dependencies, python

#2037 fix(date-inputs): use correct variables delimiters for default variables [TCTC-8076]
  ui/CHANGELOG.md
  ui/src/components/stepforms/widgets/DateComponents/DateRangeInput.vue
  ui/src/components/stepforms/widgets/DateComponents/NewDateInput.vue
  ui/tests/unit/date-range-input.spec.ts
  ui/tests/unit/new-date-input.spec.ts
Labels: bug, need review

#2038 chore(ui): v0.111.3
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: ui, release

#2041 fix(pypika translator): cannot select null in filterstep with operators in / nin / eq / ne [TCTC-7943]
  server/CHANGELOG.md
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/src/weaverbird/pipeline/steps/filter.py
  server/tests/backends/fixtures/filter/eq_with_null_pypika.yaml
  server/tests/backends/fixtures/filter/isin_with_null_pypika.yaml
Labels: bug, need review

#2040 chore(server): v0.42.2
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review, python

#2053 chore(ui): declare types as export in package.json
  ui/package.json
Labels: need review, ui
