Repository ToucanToco/weaverbird, pull requests merged in 2024-08, with the labels that each got.

#2198 fix(server/mongo): make fields of all document issued by the rollup step consistent [TCTC-8989]
  server/CHANGELOG.md
  server/src/weaverbird/backends/mongo_translator/steps/rollup.py
  server/tests/backends/fixtures/rollup/groupby_and_limit.yaml
Labels: bug, need review

#2199 chore(server): v0.45.11
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review

#2204 fix(ui): only result of the last request should be used TCTC-8992
  ui/src/store/actions.ts
  ui/src/store/state.ts
  ui/tests/unit/store.spec.ts
Labels: need review, ui, fix

#2207 chore(ui): v0.113.1
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
  ui/tests/unit/store.spec.ts
Labels: ui, release

#2209 chore(server): v0.45.12
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review

#2217 fix(server/pypika): support datetimes in filter step with Athena [TCTC-9146]
  server/CHANGELOG.md
  server/Makefile
  server/src/weaverbird/backends/pypika_translator/translators/athena.py
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/tests/backends/fixtures/filter/date_eq_pypika.yaml
  server/tests/backends/fixtures/filter/date_in_pypika.yaml
  server/tests/backends/fixtures/filter/date_in_with_null_pypika.yaml
  server/tests/backends/sql_translator_unit_tests/test_filter_translators.py
  server/tests/utils.py
Labels: bug, need review, pypika

#2218 docs: add a warning indicating that accents are not supported by mongo for the `uppercase` and `lowercase` steps [TCTC-9132]
  README.md
  docs/Dockerfile
  docs/Gemfile.lock
  docs/_docs/tech/steps.md
Labels: bug, mongo, DO NOT MERGE, python

#2219 chore(server): v0.45.13
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review
