Repository ToucanToco/weaverbird, pull requests merged in 2024-10, with the labels that each got.

#2260 fix(ui): declare css export
  ui/CHANGELOG.md
  ui/package.json
Labels: ui, fix

#2262 chore(ui): v0.115.3
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: release

#2235 feat(ui): disable variables for column names that affect the schema
  ui/src/components/stepforms/AbsoluteValueStepForm.vue
  ui/src/components/stepforms/AddMissingDatesStepForm.vue
  ui/src/components/stepforms/AddTextColumnStepForm.vue
  ui/src/components/stepforms/AggregateStepForm.vue
  ui/src/components/stepforms/FormulaStepForm.vue
  ui/src/components/stepforms/RenameStepForm.vue
  ui/src/components/stepforms/SplitStepForm.vue
  ui/src/components/stepforms/UnpivotStepForm.vue
  ui/src/components/stepforms/WaterfallStepForm.vue
  ui/src/components/stepforms/widgets/Aggregation.vue
  ui/src/components/stepforms/widgets/CumSum.vue
  ui/src/components/stepforms/widgets/Rename.vue
Labels: enhancement, ui
