Repository ToucanToco/weaverbird, pull requests merged in 2024-01, with the labels that each got.

#1987 fix(deps): pytest-asyncio should be a test requirement only
  server/poetry.lock
  server/pyproject.toml
Labels: bug, need review, dependencies

#1988 fix(relative-date-form): use correct delimiters depending on if variable is trusted or not [TCTC-7581]
  ui/CHANGELOG.md
  ui/src/components/stepforms/widgets/DateComponents/RelativeDateForm.vue
  ui/tests/unit/custom-granularity-calendar.spec.ts
  ui/tests/unit/relative-date-form-widget.spec.ts
Labels: bug, need review

#1989 chore(ui): v0.111.2
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: release

#1995 fix(server/steps/append): correctly resolve pipeline with refs [TCTC-7450]
  server/CHANGELOG.md
  server/src/weaverbird/pipeline/steps/utils/combination.py
  server/tests/pipeline/test_references.py
Labels: bug, python

#1997 fix(server/steps): Allow IfThenElseStepWithVariables to be used with RelativeDateConditionWithVariables
  server/CHANGELOG.md
  server/src/weaverbird/pipeline/steps/ifthenelse.py
  server/tests/steps/test_ifthenelse.py
Labels: bug, need review

#1998 chore(server): v0.41.2
  server/CHANGELOG.md
  server/pyproject.toml
Labels: need review

#2001 fix(server): accept variables in combined pipelines TCTC-7763
  server/CHANGELOG.md
  server/src/weaverbird/pipeline/steps/utils/combination.py
  server/tests/test_pipeline.py
Labels: bug, python
