Repository ToucanToco/weaverbird, pull requests merged in 2025-01, with the labels that each got.

#2315 fix(server): count null values as well in `count` aggregation [TCTC-9967]
  server/CHANGELOG.md
  server/src/weaverbird/backends/pandas_executor/steps/aggregate.py
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/tests/backends/fixtures/aggregate/count_nulls.yaml
  server/tests/backends/fixtures/aggregate/count_nulls_pypika.yaml
  server/tests/backends/sql_translator_unit_tests/test_base_translator.py
  server/tests/backends/sql_translator_unit_tests/test_base_translator_strings.py
Labels: bug, need review, py pandas, pypika

#2314 fix: keep null values in pivot index columns (TCTC-9902)
  server/CHANGELOG.md
  server/src/weaverbird/backends/pandas_executor/steps/pivot.py
  server/tests/backends/fixtures/pivot/with_nulls.yaml
  server/tests/steps/test_pivot.py
Labels: bug, need review, py pandas

#2324 feat: switch from poetry to uv
  .github/dependabot.yml
  .github/workflows/ci-server.yml
  server/CHANGELOG.md
  server/Makefile
  server/README.md
  server/poetry.lock
  server/pyproject.toml
  server/uv.lock
Labels: enhancement, need review, build

#2325 fix(ci): fix dependabot github actions schedule
  .github/dependabot.yml
Labels: bug, need review

#2334 chore(ui): v0.115.4
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: release

#2336 fix(server): raise a ValidationError for issues with the aggregate step
  server/CHANGELOG.md
  server/src/weaverbird/exceptions.py
  server/src/weaverbird/pipeline/steps/aggregate.py
  server/src/weaverbird/pipeline/steps/utils/validation.py
  server/tests/steps/test_aggregate.py
  server/uv.lock
Labels: bug, need review, python

#2337 chore(server): v0.49.0
  server/CHANGELOG.md
  server/pyproject.toml
  server/uv.lock
Labels: need review, python
