Repository ToucanToco/weaverbird, pull requests merged in 2025-05, with the labels that each got.

#2428 feat: remove playground feature
  Dockerfile
  README.md
  docker-compose.yml
  server/CHANGELOG.md
  server/Makefile
  server/README.md
  server/playground.py
  server/pyproject.toml
  server/uv.lock
Labels: need review, documentation, build, playground

#2427 fix: display properly multiselect options (TCTC-10585)
  ui/CHANGELOG.md
  ui/src/components/stepforms/widgets/Multiselect.vue
Labels: bug, need review, build, ui

#2429 fix(server/mongo): step adds empty columns to values without match (TCTC-10693)
  server/CHANGELOG.md
  server/src/weaverbird/backends/mongo_translator/steps/join.py
  server/tests/backends/fixtures/filter/join_geojson_null_values.yaml
  server/tests/backends/mongo_translator/test_mongo_translator_steps.py
Labels: bug, need review, build, mongo

#2431 chore(ui): v0.117.2
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: need review, build, ui, release

#2433 feat(tests): re-enable Snowflake tests [TCTC-10628]
  .github/workflows/ci-server.yml
  server/CHANGELOG.md
  server/src/weaverbird/backends/pypika_translator/translators/snowflake.py
  server/tests/backends/fixtures/join/left_customsql_pypika.yaml
  server/tests/backends/sql_translator_integration_tests/test_sql_bigquery_translator_steps.py
  server/tests/backends/sql_translator_integration_tests/test_sql_mysql_translator_steps.py
  server/tests/backends/sql_translator_integration_tests/test_sql_postgres_translator_steps.py
  server/tests/backends/sql_translator_integration_tests/test_sql_snowflake_translator_steps.py
  server/tests/backends/sql_translator_unit_tests/test_adapt_date_format.py
  server/tests/utils.py
Labels: bug, enhancement
