Repository ToucanToco/weaverbird, pull requests merged in 2025-04, with the labels that each got.

#2381 chore(server): v0.53.0
  server/CHANGELOG.md
  server/pyproject.toml
  server/uv.lock
Labels: need review

#2380 fix(ui): dont show whole variable value in tooltip (TCTC-10517)
  ui/CHANGELOG.md
  ui/src/components/stepforms/widgets/VariableInputs/VariableListOption.vue
  ui/tests/unit/variable-list-option.spec.ts
Labels: need review, build, ui, fix

#2396 chore(ui): v0.115.7
  ui/CHANGELOG.md
  ui/package.json
  ui/sonar-project.properties
Labels: need review, build, release

#2403 chore(server): v0.54.0
  server/CHANGELOG.md
  server/pyproject.toml
  server/uv.lock
Labels: need review

#2404 feat(ui): added support for countNulls in aggregate step [TCTC-10573]
  ui/CHANGELOG.md
  ui/package.json
  ui/src/components/stepforms/AggregateStepForm.vue
  ui/src/components/stepforms/schemas/aggregate.ts
  ui/src/lib/steps.ts
  ui/tests/unit/aggregate-step-form.spec.ts
Labels: enhancement, need review

#2408 feat(dateextract): add currentDay to match previousDay [TCTC-10223]
  docs/_docs/tech/steps.md
  server/CHANGELOG.md
  server/src/weaverbird/backends/mongo_translator/steps/date_extract.py
  server/src/weaverbird/backends/pandas_executor/steps/date_extract.py
  server/src/weaverbird/backends/pypika_translator/translators/base.py
  server/src/weaverbird/pipeline/steps/date_extract.py
  server/tests/backends/fixtures/dateextract/all_cases.json
  server/tests/backends/fixtures/dateextract/mongo_all_cases.json
  server/tests/backends/fixtures/dateextract/pypika_all_cases.json
  server/tests/steps/test_date_extract.py
  ui/src/components/stepforms/DateExtractStepForm.vue
  ui/src/components/stepforms/schemas/dateextract.ts
  ui/src/lib/steps.ts
  ui/src/lib/translators/mongo-dates.ts
Labels: enhancement, need review

#2418 feat(server, dategranularity): support variables in `granularity` field
  server/CHANGELOG.md
  server/src/weaverbird/pipeline/steps/date_granularity.py
Labels: enhancement

#2417 fix(ui, dategranularity): `granularity` handle both enum values and variables
  ui/CHANGELOG.md
  ui/src/components/stepforms/DateGranularityStepForm.vue
  ui/src/components/stepforms/schemas/dategranularity.ts
  ui/tests/unit/dategranularity-step-form.spec.ts
Labels: bug

#2421 fix(mongo, todate): support dates with two-digit years [TCTC-10523]
  server/CHANGELOG.md
  server/src/weaverbird/backends/mongo_translator/steps/todate.py
  server/tests/backends/fixtures/todate/simple_two_digit_year.yaml
Labels: enhancement
